POR/RefEdge/src/objects/Account_Attribute__c.object
<CustomObject>
    <description>Junction object for Account and Attribute.</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Account Attributes</relationshipLabel>
        <relationshipName>Account_Attributes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Attributes</relationshipLabel>
        <relationshipName>Account_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Basic_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Profile</label>
        <referenceTo>Reference_Basic_Information__c</referenceTo>
        <relationshipLabel>Account Attributes</relationshipLabel>
        <relationshipName>Account_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Attribute</label>
    <nameField>
        <displayFormat>AA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Attribute__c.object
<CustomObject>
    <description>An object that contains various Attributes.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Contact_Attribute__c.object
<CustomObject>
    <description>Junction object for Contact and Attribute.</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Contact Attributes</relationshipLabel>
        <relationshipName>Contact_Attributes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Attribute</relationshipLabel>
        <relationshipName>Contact_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_Basic_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Profile</label>
        <referenceTo>Reference_Basic_Information__c</referenceTo>
        <relationshipLabel>Contact Attributes</relationshipLabel>
        <relationshipName>Contact_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Attribute</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Label__c.object
<CustomObject>
    <description>An object that contains the various  Labels.</description>
    <label>Filter</label>
    <nameField>
        <label>Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</description>
        <inlineHelpText>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</inlineHelpText>
        <label>Reference Program Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Program_Candidate__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This Account or Contact is being considered for membership in the Customer Reference Program.</inlineHelpText>
        <label>Reference Program Candidate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referenceability_Status__c</fullName>
        <inlineHelpText>The Reference Status for an Account or Contact, in combination with Reference Program Membership, determines if a record may be included in Reference Search results. Only records with Active or Caution status may be included.</inlineHelpText>
        <label>Reference Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referenceability__c</fullName>
        <inlineHelpText>The types reference activities this Account or Contact has approved.</inlineHelpText>
        <label>Referenceability</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request__c.object
<CustomObject>
    <description>This object holds the information necessary for a reference request</description>
    <fields>
        <fullName>Reference_Request_Status__c</fullName>
        <label>Reference Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Legal Won&apos;t Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Left Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Request</label>
    <nameField>
        <displayFormat>RR-{000000000}</displayFormat>
        <label>Reference Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account__c.object
<CustomObject>
    <description>Junction table associating Reference Requests with accounts</description>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <description>Reference request association</description>
        <inlineHelpText>Reference request association</inlineHelpText>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Request</label>
    <nameField>
        <displayFormat>RRA-{000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account_Contact__c.object
<CustomObject>
    <description>This object holds all the reference request for contacts</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Request_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Requests</label>
        <referenceTo>Reference_Request_Account__c</referenceTo>
        <relationshipLabel>Contact Requests</relationshipLabel>
        <relationshipName>Reference_Request_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenceability Type</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Referenceability_Type__c.Project_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Referenceability_Type__c.Request_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Contact Requests</relationshipLabel>
        <relationshipName>Contact_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Request</label>
    <nameField>
        <displayFormat>RRAC-{000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability__c.object
<CustomObject>
    <description>An object that contains the various Referenceabilities.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referenceability</relationshipLabel>
        <relationshipName>Referenceabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenceability Type</label>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Referenceabilities</relationshipLabel>
        <relationshipName>Referenceabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referenceability</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referenceability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referenceability</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestContactSearchController.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public class TestContactSearchController {
    
    //Contact Search Results
    public static testMethod void RefsAttrsAndTextSearchContactTest() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List < Account > accounts = TestDataFactory.createAccounts();
        insert accounts;
        TestDataFactory.setUpAccountRBI(accounts);
        List < Contact > contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        TestDataFactory.setUpContactRBI(contacts);
        List < Referenceability_Type__c > rfTypes = TestDataFactory.createReferenceabilityType();
        insert rfTypes;
        List < Referenceability__c > refers = TestDataFactory.createReferenceability(new list<Account>(), contacts, rfTypes);
        insert refers;
        List < Label__c > labels = TestDataFactory.createLabels();
        insert labels;
        List < Attribute__c > attributes = TestDataFactory.createAttribute();
        insert attributes;
        TestDataFactory.createAttributeLabels(labels, attributes);
        
        List < Account_Attribute__c > accAtts = TestDataFactory.createAccountAttributes(accounts, attributes, false);
        List < Contact_Attribute__c > conAtts = TestDataFactory.createContactAttributes(contacts, attributes);
       
        Contact c = [select AccountId from Contact where Id = : contacts.get(0).Id];
        
        RfSearchController rfsearchCon = new RfSearchController();
        rfsearchCon.attributeWrapper.selectedLabelId = labels[0].Id;
        rfsearchCon.attributeWrapper.selectAllAttributeTypes();
        rfsearchCon.referenceabilityWrapper.selectAllReferenceabilityTypes();
        rfsearchCon.inputTextValue = 'con';
        Id[] fixedSearchResults = new Id[contacts.size()];
        for (Integer i = 0; i < contacts.size(); i++) {
            fixedSearchResults[i] = contacts[i].Id;
        }
        Test.setFixedSearchResults(fixedSearchResults);
        rfsearchCon.search();
        system.assertEquals(rfsearchCon.getContacts().size(),5);
    }
    //Candidate Contact Search Results
    public static testMethod void RefsAttrsAndTextSearchInactiveContactTest() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List < Account > accounts = TestDataFactory.createAccounts();
        insert accounts;
        TestDataFactory.setUpAccountRBI(accounts);
        List < Contact > contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        TestDataFactory.setUpContactRBI(contacts);
        List<Reference_Basic_Information__c> RBIAccList = [select Referenceability_Status__c,Is_Referenceable__c,Reference_Program_Candidate__c from Reference_Basic_Information__c where Contact__c IN : contacts];
        for(Reference_Basic_Information__c rbi : RBIAccList){
        	rbi.Referenceability_Status__c = 'Inactive';
        }
        update RBIAccList;
        List < Label__c > labels = TestDataFactory.createLabels();
        insert labels;
        List < Attribute__c > attributes = TestDataFactory.createAttribute();
        insert attributes;
        TestDataFactory.createAttributeLabels(labels, attributes);
        
        List < Account_Attribute__c > accAtts = TestDataFactory.createAccountAttributes(accounts, attributes, false);
        List < Contact_Attribute__c > conAtts = TestDataFactory.createContactAttributes(contacts, attributes);
        
        RfSearchController rfsearchCon = new RfSearchController();
        for(String str : rfsearchCon.filterLogics.keySet()){
        	rfsearchCon.filterLogics.get(str).operatorSelected = 'And';
        }
        rfsearchCon.contactSearch.selectedType = 'Inactive';
        system.assertEquals(rfsearchCon.getContacts().size(), 5);
        rfsearchCon.attributeWrapper.selectedLabelId = labels[0].Id;
        rfsearchCon.attributeWrapper.selectAllAttributeTypes();
        rfsearchCon.referenceabilityWrapper.selectAllReferenceabilityTypes();
        rfsearchCon.inputTextValue = 'con';
        Id[] fixedSearchResults = new Id[contacts.size()];
        for (Integer i = 0; i < contacts.size(); i++) {
            fixedSearchResults[i] = contacts[i].Id;
        }
        Test.setFixedSearchResults(fixedSearchResults);
        rfsearchCon.search();
        system.assertEquals(rfsearchCon.getContacts().size(), 5);
    }
	//Candidate Contact Search Results
    public static testMethod void RefsAttrsAndTextSearchCandidateContactTest() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List < Account > accounts = TestDataFactory.createAccounts();
        insert accounts;
        TestDataFactory.setUpAccountRBI(accounts);
        List < Contact > contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        TestDataFactory.setUpContactRBI(contacts);
        List<Reference_Basic_Information__c> RBIAccList = [select Referenceability_Status__c,Is_Referenceable__c,Reference_Program_Candidate__c from Reference_Basic_Information__c where Contact__c IN : contacts];
        for(Reference_Basic_Information__c rbi : RBIAccList){
        	rbi.Referenceability_Status__c = '';
        	rbi.Is_Referenceable__c = false;
        	rbi.Reference_Program_Candidate__c = true;
        }
        update RBIAccList;
        List < Label__c > labels = TestDataFactory.createLabels();
        insert labels;
        List < Attribute__c > attributes = TestDataFactory.createAttribute();
        insert attributes;
        TestDataFactory.createAttributeLabels(labels, attributes);
        
        List < Account_Attribute__c > accAtts = TestDataFactory.createAccountAttributes(accounts, attributes, false);
        List < Contact_Attribute__c > conAtts = TestDataFactory.createContactAttributes(contacts, attributes);
        
        RfSearchController rfsearchCon = new RfSearchController();
        rfsearchCon.contactSearch.selectedType = 'Candidate';
        system.assertEquals(rfsearchCon.getContacts().size(), 5);
        rfsearchCon.attributeWrapper.selectedLabelId = labels[0].Id;
        rfsearchCon.attributeWrapper.selectAllAttributeTypes();
        rfsearchCon.referenceabilityWrapper.selectAllReferenceabilityTypes();
        rfsearchCon.inputTextValue = 'con';
        Id[] fixedSearchResults = new Id[contacts.size()];
        for (Integer i = 0; i < contacts.size(); i++) {
            fixedSearchResults[i] = contacts[i].Id;
        }
        Test.setFixedSearchResults(fixedSearchResults);
        rfsearchCon.search();
        system.assertEquals(rfsearchCon.getContacts().size(), 5);
    }
    //Contact Search Results
    public static testMethod void refReqAccountContactsSearchTest() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List < Account > accounts = TestDataFactory.createAccounts();
        insert accounts;
        TestDataFactory.setUpAccountRBI(accounts);
        List < Contact > contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        TestDataFactory.setUpContactRBI(contacts);
        List < Referenceability_Type__c > rfTypes = TestDataFactory.createReferenceabilityType();
        insert rfTypes;
        
        Reference_Request__c refReq = new Reference_Request__c(Requester__c = UserInfo.getUserId(), Reference_Request_Status__c = 'In Progress');
        insert refReq;
        List < Reference_Request_Account__c > refReqAccs = TestDataFactory.createAccountRequests(accounts, new list<Reference_Request__c>{refReq},rfTypes);
        insert refReqAccs;
        List < Reference_Request_Account_Contact__c > refReqAccConts = TestDataFactory.createContactRequests(contacts,refReqAccs,rfTypes);
        insert refReqAccConts;
        Contacts.addAll(TestDataFactory.createContactsMore(accounts[0]));
        upsert Contacts;
        TestDataFactory.setUpMoreContactRBI(Contacts);
        
        ContactSearchController cscon = new ContactSearchController();
        system.assertEquals(true, Contacts.size() > 0);
        cscon.accountId = accounts[0].Id;
        cscon.pageIndex = 1;
        cscon.listAccountContacts();
        cscon.showMoreContactRecords = true;
        cscon.listAccountContacts();
        cscon.next();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listAccountContacts();
        cscon.next();
        system.assertEquals(3, cscon.pageIndex);
        cscon.listAccountContacts();
        cscon.previous();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listAccountContacts();
        system.assertEquals(true, Contacts.size() > 0);
        cscon.getItems();
        
        List<Reference_Basic_Information__c> RBIAccList = [select Referenceability_Status__c,Is_Referenceable__c,Reference_Program_Candidate__c from Reference_Basic_Information__c];
        for(Reference_Basic_Information__c rbi : RBIAccList){
        	rbi.Referenceability_Status__c = 'Inactive';
        }
        update RBIAccList;
        cscon = new ContactSearchController();
        cscon.selectedType = 'Inactive';
        system.assertEquals(true, Contacts.size() > 0);
        cscon.accountId = accounts[0].Id;
        cscon.pageIndex = 1;
        cscon.listAccountContacts();
        cscon.showMoreContactRecords = true;
        cscon.listAccountContacts();
        cscon.next();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listAccountContacts();
        cscon.next();
        system.assertEquals(3, cscon.pageIndex);
        cscon.listAccountContacts();
        cscon.previous();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listAccountContacts();
        system.assertEquals(true, Contacts.size() > 0);
        
        
        //RBIAccList = [select Referenceability_Status__c,Is_Referenceable__c,Reference_Program_Candidate__c from Reference_Basic_Information__c where Contact__c IN : contacts];
        for(Reference_Basic_Information__c rbi : RBIAccList){
        	rbi.Referenceability_Status__c = '';
        	rbi.Is_Referenceable__c = false;
        	rbi.Reference_Program_Candidate__c = true;
        }
        update RBIAccList;
        
        cscon = new ContactSearchController();
        cscon.selectedType = 'Candidate';
        system.assertEquals(true, Contacts.size() > 0);
        cscon.accountId = accounts[0].Id;
        cscon.pageIndex = 1;
        cscon.listAccountContacts();
        cscon.showMoreContactRecords = true;
        cscon.listAccountContacts();
        cscon.next();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listAccountContacts();
        cscon.next();
        system.assertEquals(3, cscon.pageIndex);
        cscon.listAccountContacts();
        cscon.previous();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listAccountContacts();
        system.assertEquals(true, Contacts.size() > 0);
    }
    
    // showMoreContactRecords is true and no. of Contacts are more than twice of SHOWMORE_PAGE_SIZE
    public static testMethod void contactsGetNextAndPrevTestCandidate() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List < Account > accounts = TestDataFactory.createAccounts();
        insert accounts;
        TestDataFactory.setUpAccountRBI(accounts);
        List < Contact > contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        TestDataFactory.setUpContactRBI(contacts);
       	Contacts.addAll(TestDataFactory.createContactsMore(accounts[0]));
        upsert Contacts;
        TestDataFactory.setUpMoreContactRBI(Contacts);
        List<Reference_Basic_Information__c> RBIAccList = [select Referenceability_Status__c,Is_Referenceable__c,Reference_Program_Candidate__c from Reference_Basic_Information__c where Contact__c IN : contacts];
        for(Reference_Basic_Information__c rbi : RBIAccList){
        	rbi.Referenceability_Status__c = '';
        	rbi.Is_Referenceable__c = false;
        	rbi.Reference_Program_Candidate__c = true;
        }
        update RBIAccList;
        ContactSearchController cscon = new ContactSearchController();
        cscon.selectedType = 'Candidate';
        cscon.pageIndex = 1;
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        cscon.showMoreContactRecords = true;
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        system.assertEquals(25, cscon.SHOWMORE_PAGE_SIZE);
        cscon.next();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        cscon.next();
        system.assertEquals(3, cscon.pageIndex);
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        cscon.previous();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, true);
        system.assertEquals(true, Contacts.size() > 0);
    }
    
    // showMoreContactRecords is true and no. of Contacts are more than twice of SHOWMORE_PAGE_SIZE
    public static testMethod void contactsGetNextAndPrevTestInactive() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List < Account > accounts = TestDataFactory.createAccounts();
        insert accounts;
        TestDataFactory.setUpAccountRBI(accounts);
        List < Contact > contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        TestDataFactory.setUpContactRBI(contacts);
       	Contacts.addAll(TestDataFactory.createContactsMore(accounts[0]));
        upsert Contacts;
        TestDataFactory.setUpMoreContactRBI(Contacts);
        List<Reference_Basic_Information__c> RBIAccList = [select Referenceability_Status__c,Is_Referenceable__c,Reference_Program_Candidate__c from Reference_Basic_Information__c where Contact__c IN : contacts];
        for(Reference_Basic_Information__c rbi : RBIAccList){
        	rbi.Referenceability_Status__c = 'Inactive';
        }
        update RBIAccList;
        ContactSearchController cscon = new ContactSearchController();
        cscon.selectedType = 'Inactive';
        cscon.pageIndex = 1;
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        cscon.showMoreContactRecords = true;
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        system.assertEquals(25, cscon.SHOWMORE_PAGE_SIZE);
        //system.assertEquals(false, cscon.isContactLimitExceed);
        cscon.next();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        cscon.next();
        system.assertEquals(3, cscon.pageIndex);
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        cscon.previous();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, true);
        system.assertEquals(true, Contacts.size() > 0);
    }
    
    // showMoreContactRecords is true and no. of Contacts are more than twice of SHOWMORE_PAGE_SIZE
    public static testMethod void contactsGetNextAndPrevTestActive() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List < Account > accounts = TestDataFactory.createAccounts();
        insert accounts;
        TestDataFactory.setUpAccountRBI(accounts);
        List < Contact > contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        TestDataFactory.setUpContactRBI(contacts);
       	Contacts.addAll(TestDataFactory.createContactsMore(accounts[0]));
        upsert Contacts;
        TestDataFactory.setUpMoreContactRBI(Contacts);
        ContactSearchController cscon = new ContactSearchController();
        cscon.pageIndex = 1;
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        cscon.showMoreContactRecords = true;
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        system.assertEquals(25, cscon.SHOWMORE_PAGE_SIZE);
        /*
        cscon.mapContact.get(1)[0].isSelected = true;
        cscon.mapContact.get(1)[1].isSelected = true;
        cscon.mapContact.get(1)[2].isSelected = true;
        cscon.mapContact.get(1)[3].isSelected = true;
        */
        //system.assertEquals(false, cscon.isContactLimitExceed);
        cscon.next();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        /*
        cscon.mapContact.get(2)[0].isSelected = true;
        cscon.mapContact.get(2)[1].isSelected = true;
        */
        cscon.next();
        system.assertEquals(3, cscon.pageIndex);
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, false);
        cscon.previous();
        system.assertEquals(2, cscon.pageIndex);
        cscon.listContacts('', new AttributeWrapper(), new ReferenceabilityWrapper(), new Set<String>(), false, true);
        /*
        cscon.mapContact.get(2)[0].isSelected = true;
        cscon.mapContact.get(2)[1].isSelected = true;
        */
        system.assertEquals(true, Contacts.size() > 0);
        cscon.previous();
    }
}