POR/RefEdge/src/objects/Account_Attribute__c.object
<CustomObject>
    <description>Junction object for Account and Attribute.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Attributes</relationshipLabel>
        <relationshipName>Account_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Account Attributes</relationshipLabel>
        <relationshipName>Account_Attributes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Attributes</relationshipLabel>
        <relationshipName>Account_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inheritable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this checkbox is selected this attribute will be automatically inherited by related Contacts and Reference Content.</description>
        <inlineHelpText>When this checkbox is selected this attribute will be automatically inherited by related Contacts and Reference Content.</inlineHelpText>
        <label>Inheritable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_fromMapping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mapped</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Content</label>
        <referenceTo>Reference_Content__c</referenceTo>
        <relationshipLabel>Account Attributes</relationshipLabel>
        <relationshipName>Account_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Attribute</label>
    <nameField>
        <displayFormat>AA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Attribute__c.object
<CustomObject>
    <description>An object that contains various Attributes.</description>
    <fields>
        <fullName>Attribute_Mapping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attribute Mapping</label>
        <referenceTo>Attribute_Mapping__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inheritable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Can Only Be Selected for Level 0 Attributes.</description>
        <inlineHelpText>Can Only Be Selected for Level 0 Attributes.</inlineHelpText>
        <label>Inheritable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <description>Level of this attribute in the tree</description>
        <inlineHelpText>Level of this attribute in the tree</inlineHelpText>
        <label>Level</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of the attribute</description>
        <inlineHelpText>If Parent not selected then the attribute is a root attribute</inlineHelpText>
        <label>Parent</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <label>Attribute  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Attribute_Mapping__c.object
<CustomObject>
    <description>Attribute Mapping(Bound 5)</description>
    <fields>
        <fullName>Auto_populate__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically populates a record&apos;s attributes with mapped picklst values at the time the Reference Program Member checkbox is selected.</inlineHelpText>
        <label>Auto-Populate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Api_Name__c</fullName>
        <label>Field Api Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inheritable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this picklist is mapped to an Account attribute then all related Contact and Reference Content records will inherit this attribute.</inlineHelpText>
        <label>Inheritable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Related_Mapping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Related Mapping</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Select the Object containing the field that is to be mapped.</description>
        <inlineHelpText>Select the Object containing the field that is to be mapped.</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Attribute Mapping</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Attribute Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attribute Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attributes__c</fullName>
        <label>Attributes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Generic_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generic Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</description>
        <inlineHelpText>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</inlineHelpText>
        <label>Reference Program Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Program_Candidate__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This Account or Contact is being considered for membership in the Customer Reference Program.</inlineHelpText>
        <label>Reference Program Candidate</label>
        <type>Checkbox</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Content__c.object
<CustomObject>
    <description>This object holds all the Custom Content.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reference Content</relationshipLabel>
        <relationshipName>Reference_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attributes__c</fullName>
        <label>Attributes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Reference Content</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/Batch_AddAttributesToAccount.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */
/**
* Class: AttributeMappingTriggerHandler
* Description : This Batch called from AttributeMappingTriggerHandler for Account Attribute update
* Modified by: Rekha Jangir @Nov/16/2016
*/
global with sharing class Batch_AddAttributesToAccount implements Database.Batchable < sObject > , Database.stateful {
    /**
     * Properties and variables
     */
    private string soqlQuery = '';
    private list < Attribute_Mapping__c > attMappingAssociatedToContent;
    private Map < String, Schema.SObjectField > fieldMap;
    /**
     * Constructor
     */
    global Batch_AddAttributesToAccount() {
        fieldMap = schema.SObjectType.Account.fields.getMap();
        List < Schema.SObjectField > fldObjMapValues = fieldMap.values();
        attMappingAssociatedToContent = new list < Attribute_Mapping__c > ();
        
        for (Attribute_Mapping__c attM: [select Field_Api_Name__c, Inheritable__c, Auto_populate__c from Attribute_Mapping__c
                where Object__c =: ConstantsController.ACCOUNT and Auto_populate__c = true and Is_Related_Mapping__c = false
            ]) {
            	
            if (fieldMap.containsKey(attM.Field_Api_Name__c.tolowerCase())) {
                attMappingAssociatedToContent.add(attM);
            }
        }
        soqlQuery = 'SELECT ';

        for (Schema.SObjectField s: fldObjMapValues) {
            Schema.DescribeFieldResult fieldDesc = s.getDescribe();
            
            if (fieldDesc.getType() == Schema.DisplayType.PICKLIST || fieldDesc.getType() == Schema.DisplayType.MULTIPICKLIST) {
                String theName = fieldDesc.getName();
                // Continue building your dynamic query string
                soqlQuery += theName + ',';
            }

        }
        soqlQuery = soqlQuery.subString(0, soqlQuery.length() - 1);
        soqlQuery += ',(select Id,Is_Referenceable__c,Reference_Program_Candidate__c from Reference_Basic_Informations__r where Generic_Account__c = false AND contact__c = null ) FROM Account';
        Decimal recordCount = 0;
        
        if (attMappingAssociatedToContent.size() > 0) {
            soqlQuery += ' where ';
            recordCount = 1;
            
            for (Attribute_Mapping__c attMap: attMappingAssociatedToContent) {
                soqlQuery += attMap.Field_Api_Name__c + ' != null';
                
                if (recordCount < attMappingAssociatedToContent.size()) {
                    soqlQuery += ' Or ';
                    recordCount++;
                }

            }
        }
    }

    /**
     * Method to get the data to be proceesed   
     */
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(soqlQuery);
    }

    /**
     * Method to execute the batch
     */
    global void execute(Database.BatchableContext BC, List < Account > scope) {
        list < Account_Attribute__c > accountAttributes = new list < Account_Attribute__c > ();
        set < String > preventDuplicacy = new set < String > ();
        map < Id, map < Id, Account_Attribute__c >> accountAttributesAssociated = new map < Id, map < Id, Account_Attribute__c >> ();
        
        for (Account acc: scope) {
            accountAttributesAssociated.put(acc.Id, new map < Id, Account_Attribute__c > ());
        }
        
        for (Account_Attribute__c conAtt: [select name, Id, attribute__r.Name, account__r.Id, Attribute__r.Id, Is_fromMapping__c, Inheritable__c from Account_Attribute__c where account__c In:
                accountAttributesAssociated.keySet() and Contact__c = null and Reference_Content__c = null
            ]) {
            accountAttributesAssociated.get(conAtt.account__r.Id).put(conAtt.Attribute__r.Id, conAtt);
        }
        //query all the parent along with child attributes of the mapping
        list < Attribute__c > listAttribute = [select Id, name, Attribute_Mapping__r.Id, Attribute_Mapping__r.Field_Api_Name__c, Attribute_Mapping__r.Auto_populate__c,
            (Select Id, Name From Attributes__r), Attribute_Mapping__r.Inheritable__c from Attribute__c where Attribute_Mapping__c In:
            attMappingAssociatedToContent and level__c = 0
        ];
        
        for (Attribute__c att: listAttribute) {
            
            for (Account acc: scope) {
                
                if (acc.Reference_Basic_Informations__r.size() > 0 && (acc.Reference_Basic_Informations__r[0].Is_Referenceable__c || acc.Reference_Basic_Informations__r[
                        0].Reference_Program_Candidate__c)) {
                    
                    for (Attribute__c childAtt: att.Attributes__r) {
                        
                        if (acc.get(att.Attribute_Mapping__r.Field_Api_Name__c) != null) {
                            
                            for (String attStr: string.valueOf(acc.get(att.Attribute_Mapping__r.Field_Api_Name__c)).split(';')) {
                                
                                if (attStr == childAtt.Name && !preventDuplicacy.contains(acc.Id + '' + childAtt.Id) && accountAttributesAssociated.containsKey(
                                        acc.Id) && !accountAttributesAssociated.get(acc.Id).containsKey(childAtt.Id)) {
                                    accountAttributes.add(new Account_Attribute__c(Account__c = acc.Id, Attribute__c = childAtt.Id, Is_fromMapping__c =
                                        true, Inheritable__c = att.Attribute_Mapping__r.Inheritable__c));
                                    preventDuplicacy.add(acc.Id + '' + childAtt.Id);
                                }
                            }
                            
                            if (accountAttributesAssociated.containsKey(acc.Id) && accountAttributesAssociated.get(acc.Id).containsKey(childAtt.Id) &&
                                accountAttributesAssociated.get(acc.Id).get(childAtt.Id).Inheritable__c != att.Attribute_Mapping__r.Inheritable__c) {
                                
                                if (att.Attribute_Mapping__r.Inheritable__c) {
                                    accountAttributesAssociated.get(acc.Id).get(childAtt.Id).Inheritable__c = att.Attribute_Mapping__r.Inheritable__c;
                                    accountAttributes.add(accountAttributesAssociated.get(acc.Id).get(childAtt.Id));
                                }
                            }
                        }
                    }
                }
            }
        }
        
        if (!accountAttributes.isEmpty())
            Database.upsert(accountAttributes, false);
    }
    /**
     * Method to be called after the excute
     */
    global void finish(Database.BatchableContext BC) {}
}