POR/RefEdge/src/objects/Account_Reference_Content__c.object
<CustomObject>
    <description>Junction object for Account and Reference Content.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Reference Content</relationshipLabel>
        <relationshipName>Account_Reference_Contents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_Content__c</fullName>
        <label>Reference Content</label>
        <referenceTo>Reference_Content__c</referenceTo>
        <relationshipName>Account_Reference_Contents</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Associated Account</label>
    <nameField>
        <displayFormat>ARC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Default_Expiration_Days__c</fullName>
        <label>Default Expiration Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Expiration_Days__c</fullName>
        <inlineHelpText>The maximum number of days that a Microsite invitation can be active. Users cannot set a date beyond this limit.</inlineHelpText>
        <label>Maximum Expiration Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Invitation__c.object
<CustomObject>
    <description>Content Sharing (Bound 4)</description>
    <fields>
        <fullName>Invitation_Expiration__c</fullName>
        <inlineHelpText>The date upon which the Microsite associated with this invitation will no longer be accessible.</inlineHelpText>
        <label>Invitation Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Microsite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Microsite</label>
        <referenceTo>Microsite__c</referenceTo>
        <relationshipLabel>Invitations</relationshipLabel>
        <relationshipName>Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invitation</label>
    <nameField>
        <label>Invitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Invitee__c.object
<CustomObject>
    <description>Content Sharing (Bound 4)</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A Contact in Salesforce.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recipients</relationshipLabel>
        <relationshipName>Invitees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invitation__c</fullName>
        <label>Invitation</label>
        <referenceTo>Invitation__c</referenceTo>
        <relationshipName>Invitees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Recipient</label>
    <nameField>
        <displayFormat>INVI-{0000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Microsite__c.object
<CustomObject>
    <description>Content Sharing (Bound 4)</description>
    <fields>
        <fullName>Available_for_Use__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available for Use?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Microsite</label>
    <nameField>
        <label>Microsite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Microsites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/POR_App_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Microsite_default_template__c</fullName>
        <label>Microsite default template</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>RefEdge Configuration</label>
</CustomObject>

POR/RefEdge/src/objects/Reference_Content__c.object
<CustomObject>
    <description>This object holds all the Custom Content.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reference Content</relationshipLabel>
        <relationshipName>Reference_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Status__c</fullName>
        <label>Content Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Custom_Reference_Content__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Custom Reference Content</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>Chinese (Simplified)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese (Traditional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dutch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finnish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese (Brazilian)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Swedish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thai</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reference Content</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestInvitationController.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public with sharing class TestInvitationController {
    
    //Unit Test Method
    static testMethod void unitTest01() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        User u = TestDataFactory.createUser();
        insert u;
        POR_App_Configuration__c appConfig = new POR_App_Configuration__c();
        insert appConfig;
        Account account = new Account(Name = 'Acc1');
        insert account;
        Contact contact = new Contact(FirstName = 'con1', LastName = 'test', AccountID = account.Id, Email = 'abc@gmail.com');
        insert contact;
        ContentVersion CV = new ContentVersion(Title = 'Content Version1', PathOnClient = 'text', VersionData = TestDataFactory.createFile());
        insert CV; 
        list<Reference_Content__c> RCList = new list<Reference_Content__c>();
        RCList.add(new Reference_Content__c(Title__c = 'cont1', Content_Status__c = 'Active',  Language__c = 'English', Content_ID__c = CV.Id,Custom_Reference_Content__c=true));
        RCList.add(new Reference_Content__c(Title__c = 'cont2', Content_Status__c = 'Active',  Language__c = 'English', Content_ID__c = CV.Id));
        insert RCList;
        List<Account_Reference_Content__c> ARCList = new list<Account_Reference_Content__c>();
        ARCList.add(new Account_Reference_Content__c(Account__c = account.Id, Reference_Content__c = RCList[0].Id));
        ARCList.add(new Account_Reference_Content__c(Account__c = account.Id, Reference_Content__c = RCList[1].Id));
        insert ARCList;
        Opportunity opprt = new Opportunity(Name = 'opp1', Account = account, CloseDate = system.today(), StageName = 'Prospecting');
        insert opprt;
        Microsite__c microsite = new Microsite__c(Name = 'test', Available_for_Use__c = true);
        insert microsite;
         
         //edit
        Case casea = new Case(Status = 'New',Origin = 'Email',Account = account);
        insert casea;
        //end
        //Start test method     
        test.startTest();
            PageReference pageRef = Page.Invitation_New;
            Test.setCurrentPage(pageRef);
            Reference_Content__c RC = RCList[0];
            InvitationController ic = new InvitationController();
            ic.defaultExpirationDays = (customSetting.Default_Expiration_Days__c != null ? customSetting.Default_Expiration_Days__c : 0);
            ic.maximumExpirationDays = (customSetting.Maximum_Expiration_Days__c != null ? customSetting.Maximum_Expiration_Days__c : 0);
            ic.onLoad();
            ic.opportunityId = opprt.Id;
        	ic.caseId=casea.id;
            ic.selectedRefContents = String.valueOf(RC.Id)+','+String.valueOf(RCList[1].Id);
            ic.createInvitation();
            ic.showCoworkers();
            ic.invitation.Invitation_Expiration__c = system.today() - 1;
            ic.createInvitation();
            ic.invitation.Invitation_Expiration__c = system.today() + Integer.valueOf(customSetting.Maximum_Expiration_Days__c) + 1;
            ic.createInvitation();
            ic.invitation.Invitation_Expiration__c = system.today() + 1;
            ic.createInvitation();
            ic.contactIds = contact.Id;
            ic.contactEmailIds = contact.Id;
            ic.coworkerIds = u.Id;
            ic.createInvitation();
            //ic.refresh();
        	ic.showRefContents();
            ic.contentIdToRemove = RCList[1].Id;
            ic.removeContent();
            ic.invitation.Subject__c = 'test subject';
            ic.invitation.Message__c = 'test message';
            ic.createInvitation();
            ic.invitation.Microsite__c = microsite.Id;
            ic.setDefaultTemplate();
            system.assertEquals(UtilityController.getMicrositeTemplete(), microsite.Id);
            ic.createInvitation();
            list<Invitee__c> invits = [select Id, URL__c From Invitee__c where Invitation__c = :ic.invitation.Id and Contact__c = :contact.Id];
            //system.assertEquals(1, invits.size());
            ic.returnOpportunity();
        	ic.pageUrl='/';
       		ic.opportunityId=null;
        	//returnOpportunity if opporetunityId is null
        	ic.returnOpportunity();
        	ic.caseId=null;
        	//returnOpportunity if caseId and opporetunityId is null
       		ic.returnOpportunity();
        	ContentVersion cv1=[select Id from ContentVersion where id =:CV.id];
        	ic.hoverContentId=cv1.Id;
        	ic.fetchHoverContentItem();
       		Reference_Content__c refContC=[select id from Reference_content__c where id=:RCList[0].Id];
        	ic.hoverContentId=null;
        	ic.hoverRefContentId=refContC.id;
        	ic.fetchHoverContentItem();
        	ic.singleContentDownload();
        //Stop test method  
        test.stopTest();
    }
    
    //Unit Test Method
    static testMethod void unitTest02() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        User u = TestDataFactory.createUser();
        insert u;
        
        Microsite__c microsite = new Microsite__c(Name = 'test', Available_for_Use__c = true);
        insert microsite;
        
        POR_App_Configuration__c appConfig = new POR_App_Configuration__c();
        appConfig.Microsite_default_template__c = microsite.id;
        insert appConfig;
        
        Account account = new Account(Name = 'Acc1');
        insert account;
        Contact contact = new Contact(FirstName = 'con1', LastName = 'test', AccountID = account.Id, Email = 'abc@gmail.com');
        insert contact;
        ContentVersion CV = new ContentVersion(Title = 'Content Version1', PathOnClient = 'text', VersionData = TestDataFactory.createFile());
        insert CV; 
        Reference_Content__c RC = new Reference_Content__c(Title__c = 'cont1', Content_Status__c = 'Active', Language__c = 'English', Content_ID__c = CV.Id);
        insert RC;
        Opportunity opprt = new Opportunity(Name = 'opp1', Account = account, CloseDate = system.today(), StageName = 'Prospecting');
        insert opprt;
        //Start test method 
        test.startTest();
            PageReference pageRef = Page.Invitation_New;
            Test.setCurrentPage(pageRef);
            InvitationController ic = new InvitationController();
            ic.defaultExpirationDays = (customSetting.Default_Expiration_Days__c != null ? customSetting.Default_Expiration_Days__c : 0);
            ic.maximumExpirationDays = (customSetting.Maximum_Expiration_Days__c != null ? customSetting.Maximum_Expiration_Days__c : 0);
            ic.onLoad();
            ic.opportunityId = opprt.Id;
            ic.selectedRefContents = String.valueOf(RC.Id);
            ic.createInvitation();
            ic.showCoworkers();
            ic.invitation.Invitation_Expiration__c = system.today() - 1;
            ic.createInvitation();
            ic.invitation.Invitation_Expiration__c = system.today() + Integer.valueOf(customSetting.Maximum_Expiration_Days__c) + 1;
            ic.createInvitation();
            ic.invitation.Invitation_Expiration__c = system.today() + 1;
            ic.createInvitation();
            ic.contactIds = contact.Id;
            ic.coworkerIds = u.Id;
            ic.createInvitation();
            ic.invitation.Subject__c = 'test subject';
            ic.invitation.Message__c = 'test message';
            ic.previewEmail();
            ic.createInvitation();
            ic.invitation.Microsite__c = microsite.Id;
            ic.setDefaultTemplate();
            system.assertEquals(UtilityController.getMicrositeTemplete(), microsite.Id);
            ic.createInvitation();
            list<Invitee__c> invits = [select Id, URL__c From Invitee__c where Invitation__c = :ic.invitation.Id and Contact__c = :contact.Id];
            //system.assertEquals(1, invits.size());
            //ic.backToSearch();
            ic.opportunityId = '';
            //ic.backToSearch();
        //Stop test method  
        test.stopTest();
    }
}