POR/RefEdge/src/objects/Attribute_Mapping__c.object
<CustomObject>
    <description>Attribute Mapping(Bound 5)</description>
    <fields>
        <fullName>Attribute_Name__c</fullName>
        <description>Auto-populated with the Field name; can be overwritten with desired Attribute name.</description>
        <inlineHelpText>Auto-populated with the Field name; can be overwritten with desired Attribute name.</inlineHelpText>
        <label>Attribute Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auto_add__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When a new value is added to a picklist field, that value will be automatically added as an attribute value.</inlineHelpText>
        <label>Auto-Add</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_delete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When a value is deleted from a picklist field, that value will be automatically deleted as an attribute value.</inlineHelpText>
        <label>Auto-Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_populate__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically populates a record&apos;s attributes with mapped picklst values at the time the Reference Program Member checkbox is selected.</inlineHelpText>
        <label>Auto-Populate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_update__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When changes to labels are made to a picklist field, those changes will be automatically made to the mapped attribute.</inlineHelpText>
        <label>Auto-Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_Label_Name__c</fullName>
        <description>Auto-populated with the Field name; can be overwritten with desired Filter name.</description>
        <inlineHelpText>Auto-populated with the Field name; can be overwritten with desired Filter name.</inlineHelpText>
        <label>Filter Label Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inheritable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this picklist is mapped to an Account attribute then all related Contact and Reference Content records will inherit this attribute.</inlineHelpText>
        <label>Inheritable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Related_Mapping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Related Mapping</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Select the Object containing the field that is to be mapped.</description>
        <inlineHelpText>Select the Object containing the field that is to be mapped.</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Attribute Mapping</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Attribute Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attribute Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/RefContentAttMappingExtension.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */
/**
 * Page: RefContentAttMappingInlinePage
 * Description : Class used to show Attribute Mappings on Reference Content detail page.
 * Modified by: Rekha @Feb 3 2017
 */
public with sharing class RefContentAttMappingExtension extends RefEdgeEditionFeatures {
    /**
     * Properties and variables
     */
    public List<Attribute_Mapping__c> attMappings { get; set; }
    
    /**
     * Constructor
     */
    public RefContentAttMappingExtension(ApexPages.standardController controller) {
        attMappings = new List<Attribute_Mapping__c> ();
        
        for (Attribute_Mapping__c attMapping : [SELECT Object__c, Name, Inheritable__c, Filter_Label_Name__c, Field__c,
                Auto_update__c, Auto_populate__c, Auto_delete__c, Auto_add__c, Attribute_Name__c
                FROM Attribute_Mapping__c WHERE Object__c = 'Reference Content'
                AND Is_Related_Mapping__c = false
            ]) {
            attMappings.add(attMapping);
        }
    }
}