POR/RefEdge/src/objects/Attribute__c.object
<CustomObject>
    <description>An object that contains various Attributes.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Label__c.object
<CustomObject>
    <description>An object that contains the various  Labels.</description>
    <label>Filter</label>
    <nameField>
        <label>Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Nomination__c.object
<CustomObject>
    <description>Custom Object to Store Nominations.(Bound 4)</description>
    <label>Nomination</label>
    <nameField>
        <displayFormat>NM-{00000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Nomination_Label__c.object
<CustomObject>
    <description>Nominations(Bound 4)</description>
    <fields>
        <fullName>Label__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Filter</label>
        <referenceTo>Label__c</referenceTo>
        <relationshipLabel>Nomination Filters</relationshipLabel>
        <relationshipName>Nomination_Labels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nomination__c</fullName>
        <label>Nomination</label>
        <referenceTo>Nomination__c</referenceTo>
        <relationshipLabel>Nomination Filters</relationshipLabel>
        <relationshipName>Nomination_Labels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Nomination Filter</label>
    <nameField>
        <displayFormat>NML-{0000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nomination Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Nomination_Label_Attribute__c.object
<CustomObject>
    <description>Nominations(Bound 4)</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Nomination Filter Attributes</relationshipLabel>
        <relationshipName>Nomination_Label_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nomination_Label__c</fullName>
        <label>Nomination Label</label>
        <referenceTo>Nomination_Label__c</referenceTo>
        <relationshipLabel>Nomination Filter Attributes</relationshipLabel>
        <relationshipName>Nomination_Label_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Nomination Filter Attribute</label>
    <nameField>
        <displayFormat>NMLA-{0000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nomination Filter Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/NominationAttributesInlineController.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */
/** 
 * Page : Nomination Attributes
 * Description:  Class used to handle Nomination Attributes
 * Last Modified By: Rajesh @Feb 4 2017
 */
public with sharing class NominationAttributesInlineController extends RefEdgeEditionFeatures {
    /**
     * Properties and variables
     */
    public Nomination__c nomination { get; set; }
    public List<Nomination_Label__c> nominationList { get; set; }
    public Map<Id, List<String>> filterAttributes { get; set; }
    
    /**
     * Constructor
     */
    public NominationAttributesInlineController(ApexPages.StandardController controller) {
        nomination = (Nomination__c)controller.getRecord();
        nominationList = [SELECT Id, Name, Label__c, Label__r.Name FROM Nomination_Label__c WHERE Nomination__c = :nomination.Id];
        filterAttributes = new Map<Id, List<String>>();
        
        for (Nomination_Label__c nomi : nominationList) {
            filterAttributes.put(nomi.Id, new List <String>());
        }
        
        for (Nomination_Label_Attribute__c NLA : [SELECT Attribute__c, Attribute__r.Name, Nomination_Label__c 
        						FROM Nomination_Label_Attribute__c WHERE Nomination_Label__c IN :filterAttributes.keySet()]) {
            
            if (filterAttributes.containsKey(NLA.Nomination_Label__c)) {
                filterAttributes.get(NLA.Nomination_Label__c).add(NLA.Attribute__r.Name);
            }
        }
    }
}