POR/RefEdge/src/objects/Attribute__c.object
<CustomObject>
    <description>An object that contains various Attributes.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Attributes_Labels__c.object
<CustomObject>
    <description>Junction object for Attributes and Labels.</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipName>Attributes_Labels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Filter</label>
        <referenceTo>Label__c</referenceTo>
        <relationshipName>Attributes_Labels</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute Filters</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Attributes - Filters Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attribute Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Label__c.object
<CustomObject>
    <description>An object that contains the various  Labels.</description>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nomination Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Filter</label>
    <nameField>
        <label>Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Content_Type__c.object
<CustomObject>
    <description>Reference Content Type - Replace to native CRM Content (Bound 6)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Reference Content Type</label>
    <nameField>
        <displayFormat>RCT-{0000}</displayFormat>
        <label>Reference Content Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Content Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Field__c.object
<CustomObject>
    <description>Custom Object Store selected fields from &quot;Reference Setting Fields&quot; Page(Bound 3).</description>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Reference Request Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Request Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Type_Mapping__c.object
<CustomObject>
    <description>Custom Object store mapping Reference Type with Field Label or Attribute Label for &apos;visible&apos; and &apos;Required&apos; Information used in Request Matrix( Bound 3)</description>
    <fields>
        <fullName>Label__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Label</label>
        <referenceTo>Label__c</referenceTo>
        <relationshipLabel>Reference Type Mappings</relationshipLabel>
        <relationshipName>Reference_Type_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reference_Content_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Content Type</label>
        <referenceTo>Reference_Content_Type__c</referenceTo>
        <relationshipLabel>Reference Type Mappings</relationshipLabel>
        <relationshipName>Reference_Type_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenceability Type</label>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Reference Type Mappings</relationshipLabel>
        <relationshipName>Reference_Type_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Reference Type Mapping</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Type Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Controls the overall visibility of this Referenceability Type throughout ReferenceEdge – Referenceability, Requests, Projects, Nominations, Reference Use.</inlineHelpText>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestRequestSettingMatrixController.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */ 
@isTest(seeAllData = false)
public with sharing class TestRequestSettingMatrixController {
    public static Custom_Settings__c customSetting;
    public static list < Reference_Type_Mapping__c > rtmapping;
    public static list < Label__c > labels;
    public static list < Attribute__c > attributes;
    public static list < Attributes_Labels__c > attLabels;
    public static List < Referenceability_Type__c > rfTypes;
    public static List < Reference_Content_Type__c > rfContentTypes;
    public static list < Reference_Request_Field__c > refFields;
    public static RequestSettingMatrixController controllerObj;
    
    //Unit Test Method
    static testMethod void testRefTypesPicklistAndSelectedRefTypesList () {
        setUpData();
    	test.startTest();
        Pagereference pgref = Page.RequestSettingMatrix;
        Apexpages.currentPage().getParameters().put('customSettingId', customSetting.Id);
        Apexpages.currentPage().getParameters().put('isContentSetting', 'false');
        controllerObj = new RequestSettingMatrixController();
        controllerObj.passSelectedReferenceTypeToController();
        system.assertEquals(true, controllerObj.ReferenceTypesPicklist.size() > 0);
        system.assertEquals(true, controllerObj.SelectedReferenceTypesList.size() > 0);
    	test.stopTest();
    }
    
    //Unit Test Method
    static testMethod void testConTypesPicklistAndSelectedConTypesList () {
        setUpData();
    	test.startTest();
        Pagereference pgref = Page.ReferenceContentTypeSettingMatrix;
        Apexpages.currentPage().getParameters().put('customSettingId', customSetting.Id);
        Apexpages.currentPage().getParameters().put('isContentSetting', 'true');
        controllerObj = new RequestSettingMatrixController();
        controllerObj.passSelectedReferenceContentTypeToController();
        system.assertEquals(true, controllerObj.ReferenceContentTypesPicklist.size() > 0);
        system.assertEquals(true, controllerObj.SelectedReferenceContentTypesList.size() > 0);
    	test.stopTest();
    }
    
    //Unit Test Method
    static testMethod void testRequestSettingMatrixController() {
        setUpData();
        test.startTest();
            Pagereference pgref = Page.RequestSettingMatrix;
            Apexpages.currentPage().getParameters().put('customSettingId', customSetting.Id);
            Apexpages.currentPage().getParameters().put('isContentSetting', 'false');
            controllerObj = new RequestSettingMatrixController();
            controllerObj.saveMatrix();
            controllerObj.backToCustomSetting();
            controllerObj.cancelMatrix();
            controllerObj.redirectFieldPage();
            controllerObj.deleteMappings();
            system.assertEquals(false, controllerObj.isEdit);
            controllerObj.editMatrix();
            system.assertEquals(true, controllerObj.isEdit);
            delete labels;
        test.stopTest();
    }
    //Unit Test Method
    static testMethod void testRequestSettingMatrixController2() {
        setUpData();
        Reference_Content_Type__c rct = new Reference_Content_Type__c(name__c = 'test',active__c=true);
        insert rct;
        test.startTest();
            Pagereference pgref = Page.ReferenceContentTypeSettingMatrix;
            Apexpages.currentPage().getParameters().put('customSettingId', customSetting.Id);
            Apexpages.currentPage().getParameters().put('isContentSetting', 'true');
            controllerObj = new RequestSettingMatrixController();
            for (String key: controllerObj.matrixMap.keySet()) {
                controllerObj.matrixMap.get(key).Visible__c = true;
            }
            controllerObj.saveMatrix();
            controllerObj = new RequestSettingMatrixController();
            controllerObj.backToCustomSetting();
            controllerObj.cancelMatrix();
            controllerObj.redirectFieldPage();
            controllerObj.deleteMappings();
            system.assertEquals(false, controllerObj.isEdit);
            controllerObj.editMatrix();
            system.assertEquals(true, controllerObj.isEdit);
            delete labels;
        test.stopTest();
    }
    //Data Setup
    static void setUpData() {
        customSetting = TestDataFactory.createCustomSetting();
        rfTypes = setUpRFTypes();
        insert rfTypes;
        rfContentTypes = setUpRFContentTypes();
        insert rfContentTypes;
        labels = createLabels();
        insert labels;
        attributes = createAttributes();
        insert attributes;
        attLabels = createAttributeLabel();
        insert attLabels;
        refFields = createRefFields();
        insert refFields;
        rtmapping = createReferenceTypeMapping();
        insert rtmapping;
    }
    
    //Referenceability_Type Setup
    static List < Referenceability_Type__c > setUpRFTypes() {
        List < Referenceability_Type__c > rftypesLst = new List < Referenceability_Type__c > ();
        rftypesLst.add(new Referenceability_Type__c(Name = 'RFType1'));
        rftypesLst.add(new Referenceability_Type__c(Name = 'RFType2'));
        rftypesLst.add(new Referenceability_Type__c(Name = 'RFType3'));
        return rftypesLst;
    }
    
    //Reference Content Type Setup
    static List <Reference_Content_Type__c> setUpRFContentTypes() {
        List <Reference_Content_Type__c> rfContentTypeList = new List <Reference_Content_Type__c> ();
        rfContentTypeList.add(new Reference_Content_Type__c(Name__c = 'RFContentType1'));
        rfContentTypeList.add(new Reference_Content_Type__c(Name__c = 'RFContentType2'));
        rfContentTypeList.add(new Reference_Content_Type__c(Name__c = 'RFContentType3'));
        return rfContentTypeList;
    }
    
    //Label Setup
    static list < Label__c > createLabels() {
        list < Label__c > tempList = new list < Label__c > ();
        tempList.add(new Label__c(name = 'testLabel1'));
        tempList.add(new Label__c(name = 'testLabel2'));
        return tempList;
    }
    
    //Attribute Setup
    static list < Attribute__c > createAttributes() {
        list < Attribute__c > tempAtt = new list < Attribute__c > ();
        tempAtt.add(new Attribute__c(name = 'testAtt1'));
        tempAtt.add(new Attribute__c(name = 'testAtt2'));
        tempAtt.add(new Attribute__c(name = 'testAtt3'));
        tempAtt.add(new Attribute__c(name = 'testAtt4'));
        return tempAtt;
    }
    
    //Attributes_Labels Setup
    static list < Attributes_Labels__c > createAttributeLabel() {
        list < Attributes_Labels__c > tempAttLabel = new list < Attributes_Labels__c > ();
        tempAttLabel.add(new Attributes_Labels__c(Attribute__c = attributes.get(0).Id, Label__c = labels.get(0).Id));
        tempAttLabel.add(new Attributes_Labels__c(Attribute__c = attributes.get(1).Id, Label__c = labels.get(0).Id));
        tempAttLabel.add(new Attributes_Labels__c(Attribute__c = attributes.get(2).Id, Label__c = labels.get(1).Id));
        tempAttLabel.add(new Attributes_Labels__c(Attribute__c = attributes.get(3).Id, Label__c = labels.get(1).Id));
        return tempAttLabel;
    }
    
    //Reference_Type_Mapping Setup
    static list < Reference_Type_Mapping__c > createReferenceTypeMapping() {
        list < Reference_Type_Mapping__c > tempRefMapping = new list < Reference_Type_Mapping__c > ();
        tempRefMapping.add(new Reference_Type_Mapping__c(Visible__c = true, Required__c = false, Referenceability_Type__c = rfTypes.get(0).Id, Name = 'OwnerId'));
        tempRefMapping.add(new Reference_Type_Mapping__c(Visible__c = true, Required__c = false, Referenceability_Type__c = rfTypes.get(0).Id, Label__c = labels.get(0).Id));
        tempRefMapping.add(new Reference_Type_Mapping__c(Visible__c = true, Required__c = false, Referenceability_Type__c = rfTypes.get(0).Id, Label__c = labels.get(1).Id));
        return tempRefMapping;
    }
    
    //Reference_Request_Field Setup
    static list < Reference_Request_Field__c > createRefFields() {
        list < Reference_Request_Field__c > tempFields = new list < Reference_Request_Field__c > ();
        tempFields.add(new Reference_Request_Field__c(order__c = 1, Field_API_Name__c = 'OwnerId', Name = 'OwnerId'));
        return tempFields;
    }
    
}