POR/RefEdge/src/objects/Attribute__c.object
<CustomObject>
    <description>An object that contains various Attributes.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Label__c.object
<CustomObject>
    <description>An object that contains the various  Labels.</description>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nomination Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Filter</label>
    <nameField>
        <label>Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/POR_App_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RefEdge Configuration</label>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Controls the overall visibility of this Referenceability Type throughout ReferenceEdge – Referenceability, Requests, Projects, Nominations, Reference Use.</inlineHelpText>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestNominationSettingsController.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public with sharing class TestNominationSettingsController {
        
    //Unit Test Method
    static testMethod void checkNominationSettings() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        list < Attribute__c > attributes = TestDataFactory.createAttribute();
        insert attributes;
        list< Label__c > labels = TestDataFactory.createLabels();
        insert labels;
        TestDataFactory.createAttributeLabels(labels, attributes);
        List < Referenceability_Type__c > rfTypes = TestDataFactory.createReferenceabilityType();
        insert rfTypes;
        
        POR_App_Configuration__c cs = ConstantsController.setEditionCustomSetting();
        insert cs;
        //Start test method
        test.startTest();
            PageReference matrixPage = Page.NominationSettings;
            NominationSettingsController settings = new NominationSettingsController();
            for(string str : settings.nominationHeaderMap.keySet()){
                settings.nominationHeaderMap.get(str).Visible__c = true;
            }
            settings.saveNominationSettings();
            settings.editNominationSettings();        	
            settings.refTypes[0].Visible__c = false;
            settings.saveNominationSettings();
            Referenceability_Type__c ref = [Select Name, Id, Visible__c From Referenceability_Type__c WHERE Id = :settings.refTypes[0].Id];
            system.assertEquals(true, ref.Visible__c);
            settings.cancelNominationSettings();
            settings.redirectFieldPage();
            settings.returnCustomSettings();
        //Stop test method
        test.stopTest();
    }
}