POR/RefEdge/src/objects/Attribute__c.object
<CustomObject>
    <description>An object that contains various Attributes.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Label__c.object
<CustomObject>
    <description>An object that contains the various  Labels.</description>
    <label>Filter</label>
    <nameField>
        <label>Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Nomination__c.object
<CustomObject>
    <description>Custom Object to Store Nominations.(Bound 4)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Nominations</relationshipLabel>
        <relationshipName>Nominations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>notEqual</operation>
                <value>null</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Nominations</relationshipLabel>
        <relationshipName>Nominations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disposition__c</fullName>
        <label>Disposition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Nomination</label>
    <nameField>
        <displayFormat>NM-{00000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Nomination_Label__c.object
<CustomObject>
    <description>Nominations(Bound 4)</description>
    <fields>
        <fullName>Label__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Filter</label>
        <referenceTo>Label__c</referenceTo>
        <relationshipLabel>Nomination Filters</relationshipLabel>
        <relationshipName>Nomination_Labels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nomination__c</fullName>
        <label>Nomination</label>
        <referenceTo>Nomination__c</referenceTo>
        <relationshipLabel>Nomination Filters</relationshipLabel>
        <relationshipName>Nomination_Labels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Nomination Filter</label>
    <nameField>
        <displayFormat>NML-{0000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nomination Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Nomination_Label_Attribute__c.object
<CustomObject>
    <description>Nominations(Bound 4)</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Nomination Filter Attributes</relationshipLabel>
        <relationshipName>Nomination_Label_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nomination_Label__c</fullName>
        <label>Nomination Label</label>
        <referenceTo>Nomination_Label__c</referenceTo>
        <relationshipLabel>Nomination Filter Attributes</relationshipLabel>
        <relationshipName>Nomination_Label_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Nomination Filter Attribute</label>
    <nameField>
        <displayFormat>NMLA-{0000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nomination Filter Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Nomination_Referenceability__c.object
<CustomObject>
    <description>Nominations(Bound 4)</description>
    <fields>
        <fullName>Nomination__c</fullName>
        <label>Nomination</label>
        <referenceTo>Nomination__c</referenceTo>
        <relationshipLabel>Nomination Referenceabilities</relationshipLabel>
        <relationshipName>Nomination_Referenceabilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <label>Referenceability Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Referenceability_Type__c.Referenceability_Type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Nomination Referenceabilities</relationshipLabel>
        <relationshipName>Nomination_Referenceabilities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Nomination Referenceability</label>
    <nameField>
        <displayFormat>NMRT-{0000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nomination Referenceabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/POR_App_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RefEdge Configuration</label>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</description>
        <inlineHelpText>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</inlineHelpText>
        <label>Reference Program Member</label>
        <type>Checkbox</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestCopyNominationDetailsController.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public with sharing class TestCopyNominationDetailsController {
    public static List < Nomination_Label__c > nomiLabels;
    public static List < Nomination_Label_Attribute__c > nomiLabelAtts;
    public static List < Nomination_Referenceability__c > nomiRefs;
    //Unit Test Method
    static testMethod void nominateAccountwithoutData() {
        try{
            Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
            list < Attribute__c > attributes = TestDataFactory.createAttribute();
            insert attributes;
            list< Label__c > labels = new list< Label__c >{TestDataFactory.createLabels()[0]};
            insert labels;
            TestDataFactory.createAttributeLabels(labels, attributes);
            List < Referenceability_Type__c > refTypes = TestDataFactory.createReferenceabilityType();
            insert refTypes;
            List < Account > accounts = TestDataFactory.createAccounts();
            insert accounts;
            TestDataFactory.createAccountAttributes(accounts, attributes,false);
            
            POR_App_Configuration__c cs = ConstantsController.setEditionCustomSetting();
            insert cs;
            list<Nomination__c> nominations = TestDataFactory.createNominations(new list<Account>{accounts[0]}, new list<Contact>());
            nominations[0].Disposition__c = 'Approved';
            insert nominations;
            //Start test method
            test.startTest();
                PageReference pageRef = Page.CopyNominationDetails;
                pageRef.getParameters().put('isMakeAccountMember', 'false');
                Test.setCurrentPage(pageRef);
                ApexPages.StandardController sc = new ApexPages.StandardController(nominations[0]);
                CopyNominationDetailsController copynomination = new CopyNominationDetailsController(sc);
                copynomination.getOptions();
                copynomination.deSelectAll();
                copynomination.selectAll();
                copynomination.copyDetails();
                list<Reference_Basic_Information__c> rbiList = [select Id,Is_Referenceable__c from Reference_Basic_Information__c where Account__c = :accounts[0].Id and Contact__c = null];
                system.assertEquals(true, rbiList[0].Is_Referenceable__c);
                copynomination.cancelNomination();
            //Stop test method
            test.stopTest();
        }catch(Exception e){
            
        }
    }
    //Unit Test Method
    static testMethod void nominateAccount() {
        try{
            Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
            list < Attribute__c > attributes = TestDataFactory.createAttribute();
            insert attributes;
            list< Label__c > labels = new list< Label__c >{TestDataFactory.createLabels()[0]};
            insert labels;
            TestDataFactory.createAttributeLabels(labels, attributes);
            List < Referenceability_Type__c > refTypes = TestDataFactory.createReferenceabilityType();
            insert refTypes;
            List < Account > accounts = TestDataFactory.createAccounts();
            insert accounts;
            TestDataFactory.createAccountAttributes(accounts, attributes,true);
            
            POR_App_Configuration__c cs = ConstantsController.setEditionCustomSetting();
            insert cs;
            list<Nomination__c> nominations = TestDataFactory.createNominations(new list<Account>{accounts[0]}, new list<Contact>());
            nominations[0].Disposition__c = 'Approved';
            insert nominations;
            nomiRefs = TestDataFactory.createNominationReferenceability(refTypes, nominations);
            nomiLabels = TestDataFactory.createNominationLabel(labels, nominations);
            nomiLabelAtts = TestDataFactory.createNominationLabelAttributes(attributes, nomiLabels);
            //Start test method
            test.startTest();
                PageReference pageRef = Page.CopyNominationDetails;
                pageRef.getParameters().put('isMakeAccountMember', 'true');
                Test.setCurrentPage(pageRef);
                ApexPages.StandardController sc = new ApexPages.StandardController(nominations[0]);
                CopyNominationDetailsController copynomination = new CopyNominationDetailsController(sc);
                copynomination.getOptions();
                copynomination.deSelectAll();
                copynomination.selectAll();
                copynomination.copyDetails();
                list<Reference_Basic_Information__c> rbiList = [select Id,Is_Referenceable__c from Reference_Basic_Information__c where Account__c = :accounts[0].Id and Contact__c = null];
                system.assertEquals(true, rbiList[0].Is_Referenceable__c);
                copynomination.cancelNomination();
            //Stop test method
            test.stopTest();
        }catch(Exception e){
            
        }
    }
    
    //Unit Test Method
    static testMethod void nominateContact() {
        try{
            Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
            list < Attribute__c > attributes = TestDataFactory.createAttribute();
            insert attributes;
            list< Label__c > labels = new list< Label__c >{TestDataFactory.createLabels()[0]};
            insert labels;
            TestDataFactory.createAttributeLabels(labels, attributes);
            List < Referenceability_Type__c > refTypes = TestDataFactory.createReferenceabilityType();
            insert refTypes;
            List < Account > accounts = TestDataFactory.createAccounts();
            insert accounts;
            TestDataFactory.setUpAccountRBI(accounts);
            List < Contact > contacts = TestDataFactory.createContacts(accounts);
            insert contacts;
            TestDataFactory.setUpContactRBI(contacts);
            TestDataFactory.createReferenceability(accounts, contacts, refTypes);
            TestDataFactory.createAccountAttributes(accounts, attributes,true);
            
            POR_App_Configuration__c cs = ConstantsController.setEditionCustomSetting();
            insert cs;
            list<Nomination__c> nominations = TestDataFactory.createNominations(new list<Account>(), new list<Contact>{contacts[0]});
            nominations[0].Disposition__c = 'Approved';
            insert nominations;
            nomiRefs = TestDataFactory.createNominationReferenceability(refTypes, nominations);
            nomiLabels = TestDataFactory.createNominationLabel(labels, nominations);
            nomiLabelAtts = TestDataFactory.createNominationLabelAttributes(attributes, nomiLabels);
            //Start test method
            test.startTest();
                PageReference pageRef = Page.CopyNominationDetails;
                Test.setCurrentPage(pageRef);
                ApexPages.StandardController sc = new ApexPages.StandardController(nominations[0]);
                CopyNominationDetailsController copynomination = new CopyNominationDetailsController(sc);
                copynomination.getOptions();
                copynomination.deSelectAll();
                copynomination.selectAll();
                copynomination.copyDetails();
                list<Reference_Basic_Information__c> rbiList = [select Id,Is_Referenceable__c from Reference_Basic_Information__c where Contact__c = : contacts[0].Id];
                system.assertEquals(true, rbiList[0].Is_Referenceable__c);
                copynomination.cancelNomination();
            //Stop test method
            test.stopTest();
        }catch(Exception e){
            
        }
    }
    
    //Unit Test Method
    static testMethod void nominateContactwithMapping() {
        try{
            Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
            TestDataFactory.createAttributeMapping();
            TestDataFactory.createContactAttributeMapping();
            list < Attribute__c > attributes = TestDataFactory.createAttribute();
            insert attributes;
            list< Label__c > labels = new list< Label__c >{TestDataFactory.createLabels()[0]};
            insert labels;
            TestDataFactory.createAttributeLabels(labels, attributes);
            List < Referenceability_Type__c > refTypes = TestDataFactory.createReferenceabilityType();
            insert refTypes;
            List < Account > accounts = TestDataFactory.createAccounts();
            for(Account acc : accounts){
                acc.Industry = 'Finance';
                acc.Rating = 'Cold';
            }
            insert accounts;
            List < Contact > contacts = TestDataFactory.createContacts(accounts);
            for(Contact con : contacts){
                con.LeadSource = 'Partner';
            }
            insert contacts;
            TestDataFactory.setUpContactRBI(contacts);
            TestDataFactory.createAccountAttributes(accounts, attributes,false);
            TestDataFactory.createContactAttributes(contacts, attributes);
            
            POR_App_Configuration__c cs = ConstantsController.setEditionCustomSetting();
            insert cs;
            list<Nomination__c> nominations = TestDataFactory.createNominations(new list<Account>(), new list<Contact>{contacts[0]});
            nominations[0].Disposition__c = 'Approved';
            insert nominations;
            nomiRefs = TestDataFactory.createNominationReferenceability(refTypes, nominations);
            nomiLabels = TestDataFactory.createNominationLabel(labels, nominations);
            nomiLabelAtts = TestDataFactory.createNominationLabelAttributes(attributes, nomiLabels);
            //Start test method
            test.startTest();
                PageReference pageRef = Page.CopyNominationDetails;
                pageRef.getParameters().put('isMakeAccountMember', 'true');
                Test.setCurrentPage(pageRef);
                ApexPages.StandardController sc = new ApexPages.StandardController(nominations[0]);
                CopyNominationDetailsController copynomination = new CopyNominationDetailsController(sc);
                copynomination.getOptions();
                copynomination.deSelectAll();
                copynomination.selectAll();
                copynomination.copyDetails();
                list<Reference_Basic_Information__c> rbiList = [select Id,Is_Referenceable__c from Reference_Basic_Information__c where Contact__c = : contacts[0].Id];
                system.assertEquals(true, rbiList[0].Is_Referenceable__c);
                copynomination.cancelNomination();
            //Stop test method
            test.stopTest();
        }catch(Exception e){
            
        }
    }
    
    
    //Unit Test Method
    static testMethod void nominateObjectNotNull() {
        try{
            Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
            TestDataFactory.createAttributeMapping();
            TestDataFactory.createContactAttributeMapping();
            list < Attribute__c > attributes = TestDataFactory.createAttribute();
            insert attributes;
            list< Label__c > labels = new list< Label__c >{TestDataFactory.createLabels()[0]};
            insert labels;
            TestDataFactory.createAttributeLabels(labels, attributes);
            List < Referenceability_Type__c > refTypes = TestDataFactory.createReferenceabilityType();
            insert refTypes;
            List < Account > accounts = TestDataFactory.createAccounts();
            for(Account acc : accounts){
                acc.Industry = 'Finance';
                acc.Rating = 'Cold';
            }
            insert accounts;
            List < Contact > contacts = TestDataFactory.createContacts(accounts);
            for(Contact con : contacts){
                con.LeadSource = 'Partner';
            }
            insert contacts;
            TestDataFactory.setUpContactRBI(contacts);
            TestDataFactory.createAccountAttributes(accounts, attributes,false);
            TestDataFactory.createContactAttributes(contacts, attributes);
            
            POR_App_Configuration__c cs = ConstantsController.setEditionCustomSetting();
            insert cs;
            list<Nomination__c> nominations = TestDataFactory.createNominations(new list<Account>(), new list<Contact>{contacts[0]});
            nominations[0].Disposition__c = 'Approved';
            insert nominations;
            nomiRefs = TestDataFactory.createNominationReferenceability(refTypes, nominations);
            nomiLabels = TestDataFactory.createNominationLabel(labels, nominations);
            nomiLabelAtts = TestDataFactory.createNominationLabelAttributes(attributes, nomiLabels);
            //Start test method
            Nomination__c nominationObj =  nominations[0];
            Contact contact = contacts[0];
            nominationObj.Contact__c = contact.Id;
            System.debug('nomination '+nominationObj+' contact '+contact);
            test.startTest();
                PageReference pageRef = Page.CopyNominationDetails;
                pageRef.getParameters().put('isMakeAccountMember', 'true');
                Test.setCurrentPage(pageRef);
                ApexPages.StandardController sc = new ApexPages.StandardController(nominationObj);
                CopyNominationDetailsController copynomination = new CopyNominationDetailsController(sc);
            	copynomination.nominationObj =  nominationObj;
                copynomination.getOptions();
                copynomination.deSelectAll();
                copynomination.selectAll();
                copynomination.copyDetails();
                list<Reference_Basic_Information__c> rbiList = [select Id,Is_Referenceable__c from Reference_Basic_Information__c where Contact__c = : contacts[0].Id];
                system.assertEquals(true, rbiList[0].Is_Referenceable__c);
                copynomination.cancelNomination();
            //Stop test method
            test.stopTest();
        }catch(Exception e){
            
        }
    }
}