POR/RefEdge/src/objects/Attribute__c.object
<CustomObject>
    <description>An object that contains various Attributes.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Create_Nomination__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When a Reference Lead results in a Reference being provided a new Nomination is created</description>
        <inlineHelpText>When a Reference Lead results in a Reference being provided a new Nomination is created</inlineHelpText>
        <label>Create Nomination?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Reference_Profile__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When a Reference Lead results in a Reference being provided a Reference Profile is created</description>
        <inlineHelpText>When a Reference Lead results in a Reference being provided a Reference Profile is created</inlineHelpText>
        <label>Create Reference Profile?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Private_Chatter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkBox would be helpful for the users who want that the chatter and email post should be private and not public.</description>
        <inlineHelpText>Select this checkBox if you want the chatter post should be private.</inlineHelpText>
        <label>Private Chatter</label>
        <type>Checkbox</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Data_Mapping__c.object
<CustomObject>
    <description>Nominations(Bound 4)</description>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenceability Type</label>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Data Mappings</relationshipLabel>
        <relationshipName>Data_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Data Mapping</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Label__c.object
<CustomObject>
    <description>An object that contains the various  Labels.</description>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nomination Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Filter</label>
    <nameField>
        <label>Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</description>
        <inlineHelpText>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</inlineHelpText>
        <label>Reference Program Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RUL_Activities_used__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The Completed Uses is the sum of completed reference activities or uses in the specified Time Period. On a Contact record this applies to that specific Contact. On an Account it is an aggregate of all Account and related Contact uses.</inlineHelpText>
        <label>Completed Uses</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Referenceability_Status__c</fullName>
        <inlineHelpText>The Reference Status for an Account or Contact, in combination with Reference Program Membership, determines if a record may be included in Reference Search results. Only records with Active or Caution status may be included.</inlineHelpText>
        <label>Reference Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Lead__c.object
<CustomObject>
    <description>Custom Object to track Leads for the Reference Program(Bound 8)</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reference Leads</relationshipLabel>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Date__c</fullName>
        <label>Follow Up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Timeframe__c</fullName>
        <label>Follow Up Timeframe</label>
        <picklist>
            <picklistValues>
                <fullName>30 days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>180 days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Initial_Notification_Date__c</fullName>
        <description>Indicates the date that the FIRST notification was sent to the Reference Lead Owner</description>
        <inlineHelpText>Indicates the date that the FIRST notification was sent to the Reference Lead Owner</inlineHelpText>
        <label>Initial Notification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_Notification_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the FIRST notification was sent to the Reference Lead Owner</description>
        <inlineHelpText>Indicates that the FIRST notification was sent to the Reference Lead Owner</inlineHelpText>
        <label>Initial Notification Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Lead_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Lead Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reference Leads</relationshipLabel>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Lead_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Lead Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Reference Leads</relationshipLabel>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Lead_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is typically the Opportunity Owner but could be replaced with another name if the Opportunity Owner is no longer the correct contact</description>
        <inlineHelpText>This is typically the Opportunity Owner but could be replaced with another name if the Opportunity Owner is no longer the correct contact</inlineHelpText>
        <label>Reference Lead Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Project_type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when creating a new project from the Ref Workspace.</inlineHelpText>
        <label>Project type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when making a request.</inlineHelpText>
        <label>Request type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reward_points__c</fullName>
        <description>This Field Use for Colletion of Reward Point as per Ref Type</description>
        <inlineHelpText>Points that are awarded at the completion of a reference use.</inlineHelpText>
        <label>Customer Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Controls the overall visibility of this Referenceability Type throughout ReferenceEdge – Referenceability, Requests, Projects, Nominations, Reference Use.</inlineHelpText>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>max_accounts_per_request_type__c</fullName>
        <inlineHelpText>Maximum quantity of accounts that can be requested when this is the only request type in a Request.</inlineHelpText>
        <label>Max Accounts per Request</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>min_lead_time_per_request_type__c</fullName>
        <inlineHelpText>Time required by the reference team to fulfill a Managed Request.</inlineHelpText>
        <label>Lead Time</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestReferenceLeadFormController.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public with sharing class TestReferenceLeadFormController {
	//Unit Test method for Updation
    static testMethod void testRefByLeadWithProfileContact1() {
    	try{
	        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        customSetting.Create_Reference_Profile__c = true;
	        customSetting.Private_Chatter__c = true;
	        update customSetting;
	        list < Attribute__c > attributes = TestDataFactory.createAttribute();
	        insert attributes;
	        list< Label__c > labels = TestDataFactory.createLabels();
	        insert labels;
	        TestDataFactory.createAttributeLabels(labels, attributes);
	        List < Referenceability_Type__c > rfTypes = TestDataFactory.createReferenceabilityType();
	        insert rfTypes;
	        Account account  =  new Account(Name = 'test Account');
	        insert account;
	        list<Contact> contacts = new list<Contact>();
	        contacts.add(new Contact(LastName = 'contact1' , AccountId = account.Id));
	        contacts.add(new Contact(LastName = 'contact1' , AccountId = account.Id));
	        insert contacts;
	        Opportunity opportunity = new Opportunity(CloseDate = system.today()+1,StageName = 'Closed Won', Amount = 700,Name = 'opp1', AccountId = account.Id, OwnerId = UserInfo.getUserId());
	        insert opportunity;
	        list<Reference_Basic_Information__c> rbi = new list<Reference_Basic_Information__c>();
	        rbi.add(new Reference_Basic_Information__c(RUL_Activities_used__c = 5,Referenceability_Status__c = 'Active', Is_Referenceable__c = true, Account__c = account.Id));
	        rbi.add(new Reference_Basic_Information__c(RUL_Activities_used__c = 5,Referenceability_Status__c = 'Active', Is_Referenceable__c = true, Account__c = account.Id, Contact__c = contacts[0].Id));
	        insert rbi;
	        Reference_Lead__c refLead = new Reference_Lead__c(Reference_Lead_Owner__c = UserInfo.getUserId(),Initial_notification_date__c = system.today(), Initial_notification_sent__c = true,
						Follow_up_date__c = system.today(),Reference_Lead_Account__c = account.Id, Reference_Lead_Opportunity__c = opportunity.Id);
			insert refLead;
	        Test.startTest();
	        	PageReference matrixPage = Page.ReferenceLeadMappingPage;
	            ReferenceLeadMappingController settings = new ReferenceLeadMappingController();
	            for(string str : settings.referenceLeadHeaderMap.keySet()){
	            	settings.referenceLeadHeaderMap.get(str).Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            settings.editNominationSettings();
	            for(Data_Mapping__c dm : settings.filterMappingRecords){
	            	dm.Visible__c = true;
	            }
	            for(Data_Mapping__c dm : settings.refTypeMappingRecords){
	            	dm.Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            
	            MultiSelectReferenceLeadFieldsController con = new MultiSelectReferenceLeadFieldsController();
				con.selectedFields = con.availableFields;
				con.Save();
				
	        	PageReference pageRef = Page.referenceleadform;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	            pageRef.getParameters().put('option', '1');
	           	ApexPages.StandardController sc = new ApexPages.StandardController(refLead);
	            ReferenceLeadFormController form = new ReferenceLeadFormController(sc);
	            form.selectRefUseAttr();
	            form.refUseAttr.getAttributeLabels();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[1].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[1].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[2].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.backToReferenceLeadForm();
	            form.refUseAttr.backToReferenceLeadFormOnCancel();
	            
	            form.refTypeWrapperList[0].isSelected = true;
	            form.getContactList();
	            form.selectedContact = contacts[0].Id;
	            form.saveRecord();
	            system.assertEquals(form.refTypeWrapperList[0].isSelected,true);
	        Test.stopTest();
    	}catch(Exception e){
    		
    	}
    }
    //Unit Test method for Updation
    static testMethod void testRefByLeadWithProfileContact2() {
    	try{
	        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        customSetting.Create_Nomination__c = true;
	        update customSetting;
	        list < Attribute__c > attributes = TestDataFactory.createAttribute();
	        insert attributes;
	        list< Label__c > labels = TestDataFactory.createLabels();
	        insert labels;
	        TestDataFactory.createAttributeLabels(labels, attributes);
	        List < Referenceability_Type__c > rfTypes = TestDataFactory.createReferenceabilityType();
	        insert rfTypes;
	        TestDataFactory.createAttributeMapping();
	        TestDataFactory.createContactAttributeMapping();
	        Account account  =  new Account(Name = 'test Account',Industry = 'Banking');
	        insert account;
	        list<Contact> contacts = new list<Contact>();
	        contacts.add(new Contact(LastName = 'contact1' , AccountId = account.Id,LeadSource = 'Partner'));
	        contacts.add(new Contact(LastName = 'contact1' , AccountId = account.Id));
	        insert contacts;
	        Opportunity opportunity = new Opportunity(CloseDate = system.today()+1,StageName = 'Closed Won', Amount = 700,Name = 'opp1', AccountId = account.Id, OwnerId = UserInfo.getUserId());
	        insert opportunity;
	        insert new Reference_Basic_Information__c(RUL_Activities_used__c = 5,Referenceability_Status__c = 'Active', Is_Referenceable__c = true, Account__c = account.Id);
	        TestDataFactory.createContactAttributes(contacts, attributes);
	        Reference_Lead__c refLead = new Reference_Lead__c(Reference_Lead_Owner__c = UserInfo.getUserId(),Initial_notification_date__c = system.today(), Initial_notification_sent__c = true,
						Follow_up_date__c = system.today(),Reference_Lead_Account__c = account.Id, Reference_Lead_Opportunity__c = opportunity.Id);
			insert refLead;
	        Test.startTest();
	        	PageReference matrixPage = Page.ReferenceLeadMappingPage;
	            ReferenceLeadMappingController settings = new ReferenceLeadMappingController();
	            for(string str : settings.referenceLeadHeaderMap.keySet()){
	            	settings.referenceLeadHeaderMap.get(str).Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            settings.editNominationSettings();
	            settings.refTypeMappingRecords[0].Visible__c = true;
	            settings.saveReferenceLeadSettings();
	            
	        	PageReference pageRef = Page.referenceleadform;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	            pageRef.getParameters().put('option', '1');
	           	ApexPages.StandardController sc = new ApexPages.StandardController(refLead);
	            ReferenceLeadFormController form = new ReferenceLeadFormController(sc);
	            
	            form.refTypeWrapperList[0].isSelected = true;
	            form.saveRecord();
	            
	            settings.editNominationSettings();
	            settings.refTypeMappingRecords[0].Visible__c = true;
	            settings.refTypeMappingRecords[1].Visible__c = true;
	            for(Data_Mapping__c dm : settings.filterMappingRecords){
	            	dm.Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            
	        	pageRef = Page.referenceleadform;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	            pageRef.getParameters().put('option', '1');
	            form = new ReferenceLeadFormController(sc);
	            form.selectRefUseAttr();
	            form.refUseAttr.getAttributeLabels();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[1].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[1].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[2].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.backToReferenceLeadForm();
	            form.refTypeWrapperList[0].isSelected = true;
	            form.getContactList();
	            form.selectedContact = contacts[0].Id;
	            form.saveRecord();
	            system.assertEquals(form.selectedContact,contacts[0].Id);
	        Test.stopTest();
    	}catch(Exception e){
    		
    	}
    }
	//Unit Test method for Updation
    static testMethod void testRefByLeadWithProfile1() {
        try{
	        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        customSetting.Create_Reference_Profile__c = true;
	        update customSetting;
	        list < Attribute__c > attributes = TestDataFactory.createAttribute();
	        insert attributes;
	        list< Label__c > labels = TestDataFactory.createLabels();
	        insert labels;
	        TestDataFactory.createAttributeLabels(labels, attributes);
	        List < Referenceability_Type__c > rfTypes = TestDataFactory.createReferenceabilityType();
	        insert rfTypes;
	        Account account  =  new Account(Name = 'test Account');
	        insert account;
	        Opportunity opportunity = new Opportunity(CloseDate = system.today()+1,StageName = 'Closed Won', Amount = 700,Name = 'opp1', AccountId = account.Id, OwnerId = UserInfo.getUserId());
	        insert opportunity;
	        insert new Reference_Basic_Information__c(RUL_Activities_used__c = 5,Referenceability_Status__c = 'Active', Is_Referenceable__c = true, Account__c = account.Id);
	        TestDataFactory.createAccountAttributes(new list<Account>{account}, attributes, false);
	        Reference_Lead__c refLead = new Reference_Lead__c(Reference_Lead_Owner__c = UserInfo.getUserId(),Initial_notification_date__c = system.today(), Initial_notification_sent__c = true,
						Follow_up_date__c = system.today(),Reference_Lead_Account__c = account.Id, Reference_Lead_Opportunity__c = opportunity.Id);
			insert refLead;
	        Test.startTest();
	        	PageReference matrixPage = Page.ReferenceLeadMappingPage;
	            ReferenceLeadMappingController settings = new ReferenceLeadMappingController();
	            for(string str : settings.referenceLeadHeaderMap.keySet()){
	            	settings.referenceLeadHeaderMap.get(str).Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            settings.editNominationSettings();
	            for(Data_Mapping__c dm : settings.filterMappingRecords){
	            	dm.Visible__c = true;
	            }
	            for(Data_Mapping__c dm : settings.refTypeMappingRecords){
	            	dm.Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            
	            MultiSelectReferenceLeadFieldsController con = new MultiSelectReferenceLeadFieldsController();
				con.selectedFields = con.availableFields;
				con.Save();
				
	        	PageReference pageRef = Page.referenceleadform;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	            pageRef.getParameters().put('option', '1');
	           	ApexPages.StandardController sc = new ApexPages.StandardController(refLead);
	            ReferenceLeadFormController form = new ReferenceLeadFormController(sc);
	            form.selectRefUseAttr();
	            form.refUseAttr.getAttributeLabels();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[1].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[1].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[2].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.backToReferenceLeadForm();
	            form.refUseAttr.backToReferenceLeadFormOnCancel();
	            
	            form.refTypeWrapperList[0].isSelected = true;
	            form.saveRecord();
	            system.assertEquals(form.refTypeWrapperList[0].isSelected,true);
	        Test.stopTest();
        }catch(Exception e){
        	
        }
    }
    //Unit Test method for Updation
    static testMethod void testRefByLeadWithProfile2() {
        try{
	        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        customSetting.Create_Nomination__c = true;
	        //customSetting.Private_Chatter__c = true;
	        update customSetting;
	        list < Attribute__c > attributes = TestDataFactory.createAttribute();
	        insert attributes;
	        list< Label__c > labels = TestDataFactory.createLabels();
	        insert labels;
	        TestDataFactory.createAttributeLabels(labels, attributes);
	        List < Referenceability_Type__c > rfTypes = TestDataFactory.createReferenceabilityType();
	        insert rfTypes;
	        Account account  =  new Account(Name = 'test Account');
	        insert account;
	        Opportunity opportunity = new Opportunity(CloseDate = system.today()+1,StageName = 'Closed Won', Amount = 700,Name = 'opp1', AccountId = account.Id, OwnerId = UserInfo.getUserId());
	        insert opportunity;
	        insert new Reference_Basic_Information__c(RUL_Activities_used__c = 5,Referenceability_Status__c = 'Active', Is_Referenceable__c = true, Account__c = account.Id);
	        Reference_Lead__c refLead = new Reference_Lead__c(Reference_Lead_Owner__c = UserInfo.getUserId(),Initial_notification_date__c = system.today(), Initial_notification_sent__c = true,
						Follow_up_date__c = system.today(),Reference_Lead_Account__c = account.Id, Reference_Lead_Opportunity__c = opportunity.Id);
			insert refLead;
	        Test.startTest();
	        	PageReference matrixPage = Page.ReferenceLeadMappingPage;
	            ReferenceLeadMappingController settings = new ReferenceLeadMappingController();
	            for(string str : settings.referenceLeadHeaderMap.keySet()){
	            	settings.referenceLeadHeaderMap.get(str).Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            settings.editNominationSettings();
	            settings.refTypeMappingRecords[0].Visible__c = true;
	            settings.saveReferenceLeadSettings();
	            
	        	PageReference pageRef = Page.referenceleadform;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	            pageRef.getParameters().put('option', '1');
	           	ApexPages.StandardController sc = new ApexPages.StandardController(refLead);
	            ReferenceLeadFormController form = new ReferenceLeadFormController(sc);
	            
	            form.refTypeWrapperList[0].isSelected = true;
	            form.saveRecord();
	            
	            settings.editNominationSettings();
	            settings.refTypeMappingRecords[0].Visible__c = true;
	            settings.refTypeMappingRecords[1].Visible__c = true;
	            for(Data_Mapping__c dm : settings.filterMappingRecords){
	            	dm.Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            
	        	pageRef = Page.referenceleadform;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	            pageRef.getParameters().put('option', '1');
	            form = new ReferenceLeadFormController(sc);
	            form.selectRefUseAttr();
	            form.refUseAttr.getAttributeLabels();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[1].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[1].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.selectedLabelId = labels[1].Id;
	            form.refUseAttr.selectedAttributeId = attributes[2].Id;
	            form.refUseAttr.setAttributes();
	            form.refUseAttr.backToReferenceLeadForm();
	            form.refTypeWrapperList[0].isSelected = true;
	            form.saveRecord();
	            system.assertEquals(form.refTypeWrapperList[0].isSelected,true);
	        Test.stopTest();
        }catch(Exception e){
        	
        }
    }
    
    //Unit Test method for Updation
    static testMethod void testRefByLeadWithoutProfile() {
        try{
	        TestDataFactory.createCustomNotifications();
            Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        list < Attribute__c > attributes = TestDataFactory.createAttribute();
	        insert attributes;
	        list< Label__c > labels = TestDataFactory.createLabels();
	        insert labels;
	        TestDataFactory.createAttributeLabels(labels, attributes);
	        List < Referenceability_Type__c > rfTypes = TestDataFactory.createReferenceabilityType();
	        insert rfTypes;
	        Account account  =  new Account(Name = 'test Account');
	        insert account;
	        Opportunity opportunity = new Opportunity(CloseDate = system.today()+1,StageName = 'Closed Won', Amount = 700,Name = 'opp1', AccountId = account.Id, OwnerId = UserInfo.getUserId());
	        insert opportunity;
	        Reference_Lead__c refLead = new Reference_Lead__c(Reference_Lead_Owner__c = UserInfo.getUserId(),Initial_notification_date__c = system.today(), Initial_notification_sent__c = true,
						Follow_up_date__c = system.today(),Reference_Lead_Account__c = account.Id, Reference_Lead_Opportunity__c = opportunity.Id);
			insert refLead;
	        Test.startTest();
	        	
	        	PageReference pageRef = Page.referenceleadform;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	            pageRef.getParameters().put('option', '2');
	           	ApexPages.StandardController sc = new ApexPages.StandardController(refLead);
	            ReferenceLeadFormController form = new ReferenceLeadFormController(sc);
	            form.referenceLead.Follow_Up_Timeframe__c = '7 days';
	            form.saveRefLeadRecord();
	            pageRef.getParameters().put('option', '3');
	            form = new ReferenceLeadFormController(sc);
	            form.saveRefLeadRecord();
	            pageRef.getParameters().put('option', '4');
	            form = new ReferenceLeadFormController(sc);
	            form.saveRefLeadRecord();
	            system.assertEquals(form.referenceLead.Follow_Up_Timeframe__c, '7 days');
	        Test.stopTest();
        }catch(Exception e){
        	
        }
    }
    
    //Method to cover miscellaneous methods and line
    static testMethod void testMiscellaneousMethod(){
    	try{
	    	Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        customSetting.Create_Nomination__c = true;
	        //customSetting.Private_Chatter__c = true;
	        update customSetting;
	        list < Attribute__c > attributes = TestDataFactory.createAttribute();
	        insert attributes;
	        list< Label__c > labels = TestDataFactory.createLabels();
	        insert labels;
	        TestDataFactory.createAttributeLabels(labels, attributes);
	        List < Referenceability_Type__c > rfTypes = TestDataFactory.createReferenceabilityType();
	        rfTypes.add(new Referenceability_Type__c(Name = 'Analyst Call1',Referenceability_Type__c = true, Visible__c = true, Project_type__c = true, Request_type__c = true,min_lead_time_per_request_type__c = 10,max_accounts_per_request_type__c = 15,Reward_points__c = 100));
	        insert rfTypes;
	        Account account  =  new Account(Name = 'test Account');
	        insert account;
	        Opportunity opportunity = new Opportunity(CloseDate = system.today()+1,StageName = 'Closed Won', Amount = 700,Name = 'opp1', AccountId = account.Id, OwnerId = UserInfo.getUserId());
	        insert opportunity;
	        insert new Reference_Basic_Information__c(RUL_Activities_used__c = 5,Referenceability_Status__c = 'Active', Is_Referenceable__c = true, Account__c = account.Id);
	        Reference_Lead__c refLead = new Reference_Lead__c(Reference_Lead_Owner__c = UserInfo.getUserId(),Initial_notification_date__c = system.today(), Initial_notification_sent__c = true,
						Follow_up_date__c = system.today(),Reference_Lead_Account__c = account.Id, Reference_Lead_Opportunity__c = opportunity.Id);
			insert refLead;
			test.startTest();
				PageReference matrixPage = Page.ReferenceLeadMappingPage;
	            ReferenceLeadMappingController settings = new ReferenceLeadMappingController();
	            for(string str : settings.referenceLeadHeaderMap.keySet()){
	            	settings.referenceLeadHeaderMap.get(str).Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            settings.editNominationSettings();
	            for(Data_Mapping__c dm : settings.filterMappingRecords){
	            	dm.Visible__c = true;
	            }
	            for(Data_Mapping__c dm : settings.refTypeMappingRecords){
	            	dm.Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            PageReference pageRef = Page.referenceleadform;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	            pageRef.getParameters().put('option', '1');
	            ApexPages.StandardController sc = new ApexPages.StandardController(refLead);
	            ReferenceLeadFormController form = new ReferenceLeadFormController(sc);
	            
	            rfTypes.add(new Referenceability_Type__c(Name = 'Analyst Call2',Referenceability_Type__c = true, Visible__c = true, Project_type__c = true, Request_type__c = true,min_lead_time_per_request_type__c = 10,max_accounts_per_request_type__c = 15,Reward_points__c = 100));
	        	upsert rfTypes;
	        	system.assertEquals(rfTypes.size(),7);
	        	matrixPage = Page.ReferenceLeadMappingPage;
	            settings = new ReferenceLeadMappingController();
	            for(string str : settings.referenceLeadHeaderMap.keySet()){
	            	settings.referenceLeadHeaderMap.get(str).Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            settings.editNominationSettings();
	            for(Data_Mapping__c dm : settings.filterMappingRecords){
	            	dm.Visible__c = true;
	            }
	            for(Data_Mapping__c dm : settings.refTypeMappingRecords){
	            	dm.Visible__c = true;
	            }
	            settings.saveReferenceLeadSettings();
	            pageRef = Page.referenceleadform;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	            pageRef.getParameters().put('option', '1');
	            sc = new ApexPages.StandardController(refLead);
	            form = new ReferenceLeadFormController(sc);
	            
			test.stopTest();
    	}catch(Exception e){
    		
    	}
    }
    
}