POR/RefEdge/src/objects/Content_Collection__c.object
<CustomObject>
    <description>Content Collection (Bound 11)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collection__c</fullName>
        <label>Content Collection</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Content Collection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Content__c.object
<CustomObject>
    <description>This object holds all the Custom Content.</description>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Reference Content</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Related_Reference_Content__c.object
<CustomObject>
    <description>Content Collection (Bound 11)</description>
    <fields>
        <fullName>Content_Collection__c</fullName>
        <label>Content Collection</label>
        <referenceTo>Content_Collection__c</referenceTo>
        <relationshipLabel>Related Reference Contents</relationshipLabel>
        <relationshipName>Related_Reference_Contents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_Content__c</fullName>
        <label>Reference Content</label>
        <referenceTo>Reference_Content__c</referenceTo>
        <relationshipLabel>Related Reference Contents</relationshipLabel>
        <relationshipName>Related_Reference_Contents</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Related Reference Content</label>
    <nameField>
        <displayFormat>RCC-{0000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Reference Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestRelatedReferenceContentTrigger.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public with sharing class TestRelatedReferenceContentTrigger {
    //Test method for delete operation
    static testMethod void testDeleteOperation() {
        User u = TestDataFactory.createUser();
        insert u;
        //Start test method
        test.startTest();
        System.runAs(u) {
            try {
                Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
                ContentVersion cv = TestDataFactory.createContentVersion(u);
                insert cv;
                list<Reference_Content__c> referObject = TestDataFactory.createReferenceContent();
                referObject[0].Content_ID__c = cv.Id;
                insert referObject;
                Content_Collection__c conCollection = new Content_Collection__c(Active__c = true, Collection__c = 'test collection');
                insert conCollection;
                Related_Reference_Content__c relatedRefCon = new Related_Reference_Content__c(Content_Collection__c = conCollection.Id, Reference_Content__c = referObject[0].Id);
                insert relatedRefCon;
                Related_Reference_Content__c relatedRefCon1 = new Related_Reference_Content__c(Content_Collection__c = conCollection.Id, Reference_Content__c = referObject[0].Id);
                try {
                    insert relatedRefCon1;
                }
                catch(Exception e){
					system.assertEquals(e.getMessage().contains(System.Label.Junction_already_exists), false);
                }
            } catch (System.DmlException e) {
            }
        }
        //Stop test method
        test.stopTest();
    }
}