POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Create_Nomination__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When a Reference Lead results in a Reference being provided a new Nomination is created</description>
        <inlineHelpText>When a Reference Lead results in a Reference being provided a new Nomination is created</inlineHelpText>
        <label>Create Nomination?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ref_Prospector_Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Activates the Build Reference Prospector List button on Reference Lead View Lists allowing for the creation of Reference Prospector Leads</inlineHelpText>
        <label>Enable Reference Prospector</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ref_Prospector_Hdr_Txt__c</fullName>
        <defaultValue>&quot;Potential Reference Leads&quot;</defaultValue>
        <label>Reference Prospector Leads Header Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ref_Prospector_SubHdr_Txt__c</fullName>
        <label>Ref Prospector Leads SubHeader Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Reward_Onscreen_Notification__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Enables the onscreen messages notifying a user of points earned for the particular user activity they just completed.</inlineHelpText>
        <label>Onscreen Notification</label>
        <type>Checkbox</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Nomination__c.object
<CustomObject>
    <description>Custom Object to Store Nominations.(Bound 4)</description>
    <label>Nomination</label>
    <nameField>
        <displayFormat>NM-{00000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Generic_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generic Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</description>
        <inlineHelpText>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</inlineHelpText>
        <label>Reference Program Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Reference Owner field identifies the individual, other than the Account Owner, designated as point of contact for reference requests for the Account.</inlineHelpText>
        <label>Reference Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Lead__c.object
<CustomObject>
    <description>Custom Object to track Leads for the Reference Program(Bound 8)</description>
    <fields>
        <fullName>Follow_Up_Timeframe__c</fullName>
        <label>Follow Up Timeframe</label>
        <picklist>
            <picklistValues>
                <fullName>30 days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>180 days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nomination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the Nomination that was created when this lead was converted to a Nomination</description>
        <inlineHelpText>Indicates the Nomination that was created when this lead was converted to a Nomination</inlineHelpText>
        <label>Nomination</label>
        <referenceTo>Nomination__c</referenceTo>
        <relationshipLabel>Reference Leads</relationshipLabel>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Lead_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Lead Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reference Leads</relationshipLabel>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Lead_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is typically the Opportunity Owner but could be replaced with another name if the Opportunity Owner is no longer the correct contact</description>
        <inlineHelpText>This is typically the Opportunity Owner but could be replaced with another name if the Opportunity Owner is no longer the correct contact</inlineHelpText>
        <label>Reference Lead Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Lead_Status__c</fullName>
        <description>Indicates where this Reference Lead is in the process</description>
        <inlineHelpText>Indicates where this Reference Lead is in the process</inlineHelpText>
        <label>Reference Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initial notification sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted to Nomination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted to Program Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reminder Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Updates</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the Reference Profile that was created when this lead was converted to a Reference Program Member</description>
        <inlineHelpText>Indicates the Reference Profile that was created when this lead was converted to a Reference Program Member</inlineHelpText>
        <label>Reference Profile</label>
        <referenceTo>Reference_Basic_Information__c</referenceTo>
        <relationshipLabel>Reference Leads</relationshipLabel>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/RefProspectorResponseController.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 * 
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 * 
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"),
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR,
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING,
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS
 * WRITTEN CONSENT FROM COMPANY.
 */
/**
 * VF Page: RefProspectorResponsePage.page
 * Description: controller for prviding response to the reference prospector campaign
 * Author: Gaurav Saini (2 Nov, 2017)
 */
public with sharing class RefProspectorResponseController extends RefEdgeEditionFeatures {
    
    /**
     * method to get custom settings fields
     * author: Gaurav Saini (13 Oct, 2017)
     */
    @RemoteAction
    public static String getCustomSettings() {
    	Custom_Settings__c customSetting = UtilityController.getCustomSettings();
    	Map<String, String> resultMap = new Map<String, String>();
    	resultMap.put('createNomination', customSetting.Create_Nomination__c + '');
    	resultMap.put('isRefProspectEnabled', customSetting.Ref_Prospector_Enable__c + '');
    	resultMap.put('pageHeader', customSetting.Ref_Prospector_Hdr_Txt__c != null ? customSetting.Ref_Prospector_Hdr_Txt__c + '' : 'Potential Reference Leads');
    	resultMap.put('pageSubHeader', customSetting.Ref_Prospector_SubHdr_Txt__c != null ? customSetting.Ref_Prospector_SubHdr_Txt__c + '' : '');
    	//	REF-2008
		resultMap.put('onScreenNotification', customSetting.User_Reward_Onscreen_Notification__c+'');
		return JSON.serialize(resultMap);
    }
    
    /**
     * method to get reference lead records
     * author: Gaurav Saini (13 Oct, 2017)
     */
    @RemoteAction
    public static String getRefLeads() {
    	List<RefLeadWrapper> refLeadWrapperList = new List<RefLeadWrapper>();
    	List<Reference_Lead__c> refLeadsList = WithoutSharingHelperController.getRefLeadsForUser();
    	Set<String> accIds = new Set<String>();
    	
    	for (Reference_Lead__c rl : refLeadsList) {
    		accIds.add(rl.Reference_Lead_Account__c);
    	}
    	Map<String, Account> accRBIMap
    			= new Map<String, Account>((List<Account>)WithoutSharingHelperController.getAccountAndRBI(accIds));
    	
    	for (Reference_Lead__c rl : refLeadsList) {
    		
    		if (accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r != null
					&& accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r.size() > 0
					&& !accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r[0].Generic_Account__c) {
	    		refLeadWrapperList.add(new RefLeadWrapper(rl, accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r[0].Is_Referenceable__c));
    		} else {
    			refLeadWrapperList.add(new RefLeadWrapper(rl, false));
    		}
    	}
    	return JSON.serialize(refLeadWrapperList);
    }
    
    /**
     * method to get the list of reference lead records for specified page number
     * author: Gaurav Saini (13 Nov, 2017)
     */
    @RemoteAction
    public static String getRefLeadsForPageNo(Integer pageNo) {
    	List<RefLeadWrapper> refLeadWrapperList = new List<RefLeadWrapper>();
    	List<Reference_Lead__c> refLeadsList = WithoutSharingHelperController.getRefLeadsForPageNo(((pageNo + 1) * 10));
    	Set<String> accIds = new Set<String>();
    	
    	for (Reference_Lead__c rl : refLeadsList) {
    		accIds.add(rl.Reference_Lead_Account__c);
    	}
    	Map<String, Account> accRBIMap
    			= new Map<String, Account>((List<Account>)WithoutSharingHelperController.getAccountAndRBI(accIds));
    	
    	for (Reference_Lead__c rl : refLeadsList) {
    		
    		if (accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r != null
					&& accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r.size() > 0
					&& !accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r[0].Generic_Account__c) {
	    		refLeadWrapperList.add(new RefLeadWrapper(rl, accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r[0].Is_Referenceable__c));
    		} else {
    			refLeadWrapperList.add(new RefLeadWrapper(rl, false));
    		}
    	}
    	return JSON.serialize(refLeadWrapperList);
    }
    
    /**
     * method to get the list of reference lead records when user clicks on next link
     *			for a page which has already been opened
     * author: Gaurav Saini (13 Nov, 2017)
     */
    @RemoteAction
    public static String getAlreadyPresentRefLeads(String refLeadIdsJSON) {
    	List<RefLeadWrapper> refLeadWrapperList = new List<RefLeadWrapper>();
    	List<String> refLeadIds = (List<String>)JSON.deserialize(refLeadIdsJSON, List<String>.class);
    	List<Reference_Lead__c> refLeadsList = WithoutSharingHelperController.getRefLeadsPresent(refLeadIds);
    	Set<String> accIds = new Set<String>();
    	
    	for (Reference_Lead__c rl : refLeadsList) {
    		accIds.add(rl.Reference_Lead_Account__c);
    	}
    	Map<String, Account> accRBIMap
    			= new Map<String, Account>((List<Account>)WithoutSharingHelperController.getAccountAndRBI(accIds));
    	
    	for (Reference_Lead__c rl : refLeadsList) {
    		
    		if (accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r != null
					&& accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r.size() > 0
					&& !accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r[0].Generic_Account__c) {
	    		refLeadWrapperList.add(new RefLeadWrapper(rl, accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r[0].Is_Referenceable__c));
    		} else {
    			refLeadWrapperList.add(new RefLeadWrapper(rl, false));
    		}
    	}
    	return JSON.serialize(refLeadWrapperList);
    }
    
    /**
     * method to get the list of reference lead records when user clicks on next link
     *			for a new page
     * author: Gaurav Saini (13 Nov, 2017)
     */
    @RemoteAction
    public static String getAlreadyNotPresentRefLeads(String alreadyPresentRefLeadIdsJSON) {
    	List<RefLeadWrapper> refLeadWrapperList = new List<RefLeadWrapper>();
    	List<String> alreadyPresentRefLeadIds = (List<String>)JSON.deserialize(alreadyPresentRefLeadIdsJSON, List<String>.class);
    	List<Reference_Lead__c> refLeadsList = WithoutSharingHelperController.getRefLeadsNotPresent(alreadyPresentRefLeadIds);
    	Set<String> accIds = new Set<String>();
    	
    	for (Reference_Lead__c rl : refLeadsList) {
    		accIds.add(rl.Reference_Lead_Account__c);
    	}
    	Map<String, Account> accRBIMap
    			= new Map<String, Account>((List<Account>)WithoutSharingHelperController.getAccountAndRBI(accIds));
    	
    	for (Reference_Lead__c rl : refLeadsList) {
    		
    		if (accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r != null
					&& accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r.size() > 0
					&& !accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r[0].Generic_Account__c) {
	    		refLeadWrapperList.add(new RefLeadWrapper(rl, accRBIMap.get(rl.Reference_Lead_Account__c).Reference_Basic_Informations__r[0].Is_Referenceable__c));
    		} else {
    			refLeadWrapperList.add(new RefLeadWrapper(rl, false));
    		}
    	}
    	return JSON.serialize(refLeadWrapperList);
    }
    
    /**
     * method to get the reference lead object
     * author: Gaurav Saini (18 April, 2017) for #5
     */
    @RemoteAction
    public static String getRefLead(String refLeadId) {
    	List<Reference_Lead__c> refLeads = WithoutSharingHelperController.getReferenceLead(refLeadId);
    	List<RefLeadWrapper> refLeadWrapperList = new List<RefLeadWrapper>();
		refLeadWrapperList.add(new RefLeadWrapper(refLeads[0]));
		return JSON.serialize(refLeadWrapperList[0]);
    }
	
    /**
     * method to get the reference lead owner for lookup field
     * author: Gaurav Saini (8 Jan, 2018) for REF-1238
     */
    @RemoteAction
    public static String getRefLeadOwnerDetails(String searchText) {
		String SOQLQuery = '';
		String communityProfileName = '\'%Community%\'';
        String siteProfileName = '\'%Guest%\'';
		String result = '';
		List<User> userList = new List<User>();
		String searchValue = searchText.replace('*', '%') + '%';
        searchValue = String.escapeSingleQuotes(searchValue);
        searchValue = '\'%' + searchValue + '\'';
		SOQLQuery = 'SELECT Name, Id FROM User '
					+ 'WHERE IsActive = true '
					+ 'AND (NOT Profile.Name LIKE ' + communityProfileName + ') '
					+ 'AND (NOT Profile.Name LIKE ' + siteProfileName + ') '
					+ 'AND (NOT Name LIKE ' + siteProfileName + ') '
					+ 'AND (Name LIKE ' + searchValue + ') ORDER BY Name LIMIT 2';
		userList = Database.query(SOQLQuery);
		
		if (userList != null && userList.size() == 1) {
			result = userList[0].Id + '@@@' + userList[0].Name;
		} else if (userList != null && userList.size() > 1) {
			result = 'multiple';
		} else if (userList != null && userList.size() == 0) {
			result = 'zero';
		}
		return result;
	}
    
    /**
     * Method to get date format according tocurrent user's locale
     * author: Gaurav Saini (14 Nov, 2017) for #1104
     */
    @RemoteAction
    public static String getDateFormat() {   
		String dateFormat = ConstantsController.localeDateFormatMap.get(UserInfo.getLocale()).split(' ').get(0);
		return (dateFormat != null ? dateFormat : 'yyyy-MM-dd');
    }
    
    /**
     * method to get follow up time frame picklist values
     * author: Gaurav Saini (15 Nov, 2017) for #1104
     */
    @RemoteAction
    public static String getFollowUpDaysList() {
    	List<String> followUpDaysList = new List<String>();
    	Schema.DescribeFieldResult dfr
    			= Schema.sObjectType.Reference_Lead__c.fields.getMap().get(UtilityController.appNamespace() + 'Follow_Up_Timeframe__c').getDescribe();
        
        for (Schema.PicklistEntry ple : dfr.getPicklistValues()) {
            followUpDaysList.add(String.valueOf(ple.getValue()));
        }
        return JSON.serialize(followUpDaysList);
    }
    
    public class RefLeadWrapper {
    	public String refLeadId { get; set; }
    	public String status { get; set; }
    	public String accountId { get; set; }
    	public String accountName { get; set; }
    	public String refProfileId { get; set; }
    	public String nominationId { get; set; }
    	public Boolean isAccountMember { get; set; }
    	public String refLeadOwnerName { get; set; }
    	public String refLeadOwnerId { get; set; }
    	public String followUpTimeFrame { get; set; }
    	public Boolean isSelected { get; set; }
    	
    	public RefLeadWrapper(Reference_Lead__c refLead, Boolean isAccountMember) {
    		this.refLeadId = refLead.Id;
	    	this.accountName = refLead.Reference_Lead_Account__r.Name;
    		this.isAccountMember = isAccountMember;
    		this.isSelected = false;
    	}
    	
    	public RefLeadWrapper(Reference_Lead__c refLead) {
    		this.refLeadId = refLead.Id;
    		this.status = refLead.Reference_Lead_Status__c;
	    	this.refProfileId = refLead.Reference_Profile__c != null ? (String)refLead.Reference_Profile__c : '';
	    	this.accountId = refLead.Reference_Lead_Account__c;
	    	this.accountName = refLead.Reference_Lead_Account__r.Name;
	    	this.nominationId = refLead.Nomination__c != null ? (String)refLead.Nomination__c : '';
	    	this.refLeadOwnerName = refLead.Reference_Lead_Owner__r.Name;
	    	this.refLeadOwnerId = '';
	    	this.followUpTimeFrame = '';
    		this.isSelected = false;
    	}
    }
}