POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Auto_Assign_Sales_Rewards__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Issue User Points</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Sales_Rewards_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>User Points - as defined in Reward Settings - will be assigned to users on completion of actions.</description>
        <inlineHelpText>User Points- as defined in Reward Settings - will be assigned to users on completion of actions.</inlineHelpText>
        <label>Enable User Points</label>
        <type>Checkbox</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</description>
        <inlineHelpText>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</inlineHelpText>
        <label>Reference Program Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Reference Owner field identifies the individual, other than the Account Owner, designated as point of contact for reference requests for the Account.</inlineHelpText>
        <label>Reference Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referenceability_Status__c</fullName>
        <inlineHelpText>The Reference Status for an Account or Contact, in combination with Reference Program Membership, determines if a record may be included in Reference Search results. Only records with Active or Caution status may be included.</inlineHelpText>
        <label>Reference Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request__c.object
<CustomObject>
    <description>This object holds the information necessary for a reference request</description>
    <label>Reference Request</label>
    <nameField>
        <displayFormat>RR-{000000000}</displayFormat>
        <label>Reference Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account__c.object
<CustomObject>
    <description>Junction table associating Reference Requests with accounts</description>
    <fields>
        <fullName>Account_Request_Status__c</fullName>
        <label>Managed Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Legal Won&apos;t Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Left Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unavailable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>Reference request account</description>
        <inlineHelpText>Reference request account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Managed_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Managed Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <description>Reference request association</description>
        <inlineHelpText>Reference request association</inlineHelpText>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task_ID__c</fullName>
        <label>Account Request Task ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Account Request</label>
    <nameField>
        <displayFormat>RRA-{000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Point__c</fullName>
        <label>User Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestSelectRefUseContactsControllerSLDS.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */ 
@isTest(seeAllData = false)
public with sharing class TestSelectRefUseContactsControllerSLDS {
    /**
     * Test Method for approval succeed
     */
    static testMethod void approveTest() {
        TestDataFactory.createCustomNotifications();
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        customSetting.Enable_Sales_Rewards_Notification__c = true;
        customSetting.Auto_Assign_Sales_Rewards__c = true;
        update customSetting;
        List < Account > accounts = TestDataFactory.createAccounts();
        insert accounts;
        TestDataFactory.setUpAccountRBI(accounts);
        List < Contact > contacts = TestDataFactory.createContacts(accounts);
        contacts.add(new Contact(LeadSource = 'Partner',FirstName = 'Daniel', LastName = 'Freeman',AccountId = accounts[0].Id, Email = 'daniel@test.test'));
        contacts.add(new Contact(LeadSource = 'Partner',FirstName = 'David', LastName = 'DeRosa',AccountId = accounts[0].Id, Email = 'david@test.test'));
        insert contacts;
        TestDataFactory.setUpContactRBI(contacts);
        List < Opportunity > opps = TestDataFactory.createOpportunity(accounts);
        insert opps;
        list<Reference_Request__c> refReqs = TestDataFactory.createReferenceRequest();
        insert refReqs;
        List < Task > tasks = TestDataFactory.createTask();
        insert tasks;
        List < Referenceability_Type__c > refTypes = TestDataFactory.createReferenceabilityType();
        refTypes[0].Sales_Point__c = 100;
        insert refTypes;
        list<Reference_Basic_Information__c> rbi = [SELECT Id, Reference_Owner__c FROM Reference_Basic_Information__c WHERE Account__c =: accounts[0].Id];
        rbi[0].Reference_Owner__c = Userinfo.getUserId();
        update rbi;
        list < Reference_Request_Account__c > refReqAccs = TestDataFactory.createAccountRequests(new list<Account>{accounts[0]}, refReqs, refTypes);
        refReqAccs[0].Account_Request_Status__c = 'Completed';
        refReqAccs[0].Managed_Request__c = true;
        refReqAccs[0].Task_Id__c = tasks[0].Id;
        insert refReqAccs;
        insert new Reference_Basic_Information__c(Referenceability_Status__c = 'Inactive', Is_Referenceable__c = true, Account__c = contacts[6].AccountId, Contact__c =  contacts[6].Id );
        //Start test method
        Test.startTest();
            ApexPages.currentPage().getParameters().put('id', refReqAccs[0].Id);
            ApexPages.StandardController sc = new ApexPages.standardController(refReqAccs[0]);
            SelectRefUseContactsControllerSLDS sruccObj = new SelectRefUseContactsControllerSLDS();
            SelectRefUseContactsControllerSLDS.CustomSettingWrapper cs = SelectRefUseContactsControllerSLDS.fetchCS();
            SelectRefUseContactsControllerSLDS.InfoWrapper info = (SelectRefUseContactsControllerSLDS.InfoWrapper)JSON.deserialize(SelectRefUseContactsControllerSLDS.fetchInfo(sruccObj.refReqAccId), SelectRefUseContactsControllerSLDS.InfoWrapper.class);
            list<SelectRefUseContactsControllerSLDS.ContactWrapper> contactWps = (list<SelectRefUseContactsControllerSLDS.ContactWrapper>)JSON.deserialize(SelectRefUseContactsControllerSLDS.fetchContacts(info.rraAccountId), list<SelectRefUseContactsControllerSLDS.ContactWrapper>.class);
            SelectRefUseContactsControllerSLDS.ContactWrapper contactWp = (SelectRefUseContactsControllerSLDS.ContactWrapper)JSON.deserialize(SelectRefUseContactsControllerSLDS.activateContact(contacts[6].Id, true, true, true, ''), SelectRefUseContactsControllerSLDS.ContactWrapper.class);
            contactWp = (SelectRefUseContactsControllerSLDS.ContactWrapper)JSON.deserialize(SelectRefUseContactsControllerSLDS.activateContact(contacts[7].Id, true, true, true, ''), SelectRefUseContactsControllerSLDS.ContactWrapper.class);
            contactWps = (list<SelectRefUseContactsControllerSLDS.ContactWrapper>)JSON.deserialize(SelectRefUseContactsControllerSLDS.fetchContacts(info.rraAccountId), list<SelectRefUseContactsControllerSLDS.ContactWrapper>.class);
            string contactWpsJSON = SelectRefUseContactsControllerSLDS.fetchContacts(info.rraAccountId);
            string status = SelectRefUseContactsControllerSLDS.approve(sruccObj.refReqAccId,'','test',contactWpsJSON,cs,contacts[7].Id,true);
            system.assertEquals('success:100',status);
        //Stop test method
        Test.stopTest();
    }
    /**
     * Test Method for decline succeed
     */
    static testMethod void declineTest() {
        TestDataFactory.createCustomNotifications();
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List < Account > accounts = TestDataFactory.createAccounts();
        insert accounts;
        TestDataFactory.setUpAccountRBI(accounts);
        List < Contact > contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        TestDataFactory.setUpContactRBI(contacts);
        List < Opportunity > opps = TestDataFactory.createOpportunity(accounts);
        insert opps;
        list<Reference_Request__c> refReqs = TestDataFactory.createReferenceRequest();
        insert refReqs;
        List < Task > tasks = TestDataFactory.createTask();
        insert tasks;
        List < Referenceability_Type__c > refTypes = TestDataFactory.createReferenceabilityType();
        insert refTypes;
        list < Reference_Request_Account__c > refReqAccs = TestDataFactory.createAccountRequests(new list<Account>{accounts[0]}, refReqs, refTypes);
        refReqAccs[0].Account_Request_Status__c = 'Completed';
        refReqAccs[0].Task_Id__c = tasks[0].Id;
        insert refReqAccs;
        //Start test method
        Test.startTest();
            ApexPages.currentPage().getParameters().put('id', refReqAccs[0].Id);
            ApexPages.StandardController sc = new ApexPages.standardController(refReqAccs[0]);
            SelectRefUseContactsControllerSLDS sruccObj = new SelectRefUseContactsControllerSLDS();
            SelectRefUseContactsControllerSLDS.CustomSettingWrapper cs = SelectRefUseContactsControllerSLDS.fetchCS();
            SelectRefUseContactsControllerSLDS.InfoWrapper info = (SelectRefUseContactsControllerSLDS.InfoWrapper)JSON.deserialize(SelectRefUseContactsControllerSLDS.fetchInfo(sruccObj.refReqAccId), SelectRefUseContactsControllerSLDS.InfoWrapper.class);
            list<SelectRefUseContactsControllerSLDS.ContactWrapper> contactWps = (list<SelectRefUseContactsControllerSLDS.ContactWrapper>)JSON.deserialize(SelectRefUseContactsControllerSLDS.fetchContacts(info.rraAccountId), list<SelectRefUseContactsControllerSLDS.ContactWrapper>.class);
            string status = SelectRefUseContactsControllerSLDS.decline(sruccObj.refReqAccId,cs,'test');
            system.assertEquals('',status);
        //Stop test method
        Test.stopTest();
    }
}