POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Check_back_in_Chatter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables the confirmation Chatter sent to the Opportunity owner when they select a timeframe for checking back in on referenceability of an Account / Contact.</description>
        <inlineHelpText>Enables the confirmation Chatter sent to the Opportunity owner when they select a timeframe for checking back in on referenceability of an Account / Contact.</inlineHelpText>
        <label>Check back in Chatter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Check_back_in_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables the confirmation email sent to the Opportunity owner when they select a timeframe for checking back in on referenceability of an Account / Contact.</description>
        <inlineHelpText>Enables the confirmation email sent to the Opportunity owner when they select a timeframe for checking back in on referenceability of an Account / Contact.</inlineHelpText>
        <label>Check back in Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Check_back_in_Slack__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables the confirmation slack message sent to the Opportunity owner when they select a timeframe for checking back in on referenceability of an Account / Contact.</description>
        <inlineHelpText>Enables the confirmation slack message sent to the Opportunity owner when they select a timeframe for checking back in on referenceability of an Account / Contact.</inlineHelpText>
        <label>Check back in Slack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Slack_Integration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Slack Integration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Response_days__c</fullName>
        <description>Indicates the number of days after the &quot;Are they referenceable yet?&quot; notification is sent that the Reference Lead Status will be set to No Response. If no value is entered then the No Reponse date is left blank on the record.</description>
        <inlineHelpText>Indicates the number of days after the &quot;Are they referenceable yet?&quot; notification is sent that the Reference Lead Status will be set to No Response. If no value is entered then the No Reponse date is left blank on the record.</inlineHelpText>
        <label>No Response Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RLF_Reminder_Days__c</fullName>
        <inlineHelpText>Indicates the number of days after the &quot;Are they referenceable yet?&quot; notification is sent that a reminder is sent. If no value is entered then no reminder is sent.</inlineHelpText>
        <label>Reminder Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ref_Lead_Owner_Update_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Enables the email sent to the public group configured for the CRP Team when the Opportunity owner specifies the new person who should be contacted to determine if the Account is referenceable.</inlineHelpText>
        <label>RLF Owner Update Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Slack_Team_Ids__c</fullName>
        <label>Slack Team Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User_Reward_Onscreen_Notification__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Enables the onscreen messages notifying a user of points earned for the particular user activity they just completed.</inlineHelpText>
        <label>Onscreen Notification</label>
        <type>Checkbox</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Data_Mapping__c.object
<CustomObject>
    <description>Nominations(Bound 4)</description>
    <fields>
        <fullName>DC_Message__c</fullName>
        <label>DC Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <label>Default</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nomination</fullName>
                </value>
                <value>
                    <fullName>NominationSectionHeader</fullName>
                </value>
                <value>
                    <fullName>Filter</fullName>
                </value>
                <value>
                    <fullName>Reference Lead</fullName>
                </value>
                <value>
                    <fullName>ReferenceLeadSectionHeader</fullName>
                </value>
                <value>
                    <fullName>DMReference_Content__c</fullName>
                </value>
                <value>
                    <fullName>DMReference_Basic_Information__c</fullName>
                </value>
                <value>
                    <fullName>DMReference_Content_Type__c</fullName>
                </value>
                <value>
                    <fullName>DMAttribute__c</fullName>
                </value>
                <value>
                    <fullName>DMContentVersion</fullName>
                </value>
                <value>
                    <fullName>Notification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Name__c</fullName>
        <label>Section Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Data Mapping</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Label__c.object
<CustomObject>
    <description>An object that contains the various  Labels.</description>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nomination Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Filter</label>
    <nameField>
        <label>Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Is_Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</description>
        <inlineHelpText>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</inlineHelpText>
        <label>Reference Program Member</label>
        <type>Checkbox</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Lead__c.object
<CustomObject>
    <description>Custom Object to track Leads for the Reference Program(Bound 8)</description>
    <fields>
        <fullName>Follow_Up_Date__c</fullName>
        <label>Follow Up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Timeframe__c</fullName>
        <label>Follow Up Timeframe</label>
        <picklist>
            <picklistValues>
                <fullName>30 days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>180 days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>No_Response_Date__c</fullName>
        <description>Indicates when to set the Reference Lead status to No Response.</description>
        <inlineHelpText>Indicates when to set the Reference Lead status to No Response.</inlineHelpText>
        <label>No Response Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notification_Response__c</fullName>
        <description>Indicates the response submitted from the VF page.</description>
        <inlineHelpText>Indicates the response submitted from the VF page.</inlineHelpText>
        <label>Notification Response</label>
        <picklist>
            <picklistValues>
                <fullName>Yes, this is a very happy account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check back with me later</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I don’t know, I’m not the right person to ask</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference_Lead_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is typically the Opportunity Owner but could be replaced with another name if the Opportunity Owner is no longer the correct contact</description>
        <inlineHelpText>This is typically the Opportunity Owner but could be replaced with another name if the Opportunity Owner is no longer the correct contact</inlineHelpText>
        <label>Reference Lead Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Lead_Status__c</fullName>
        <description>Indicates where this Reference Lead is in the process</description>
        <inlineHelpText>Indicates where this Reference Lead is in the process</inlineHelpText>
        <label>Reference Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initial notification sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted to Nomination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted to Program Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reminder Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Updates</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reminder_Date__c</fullName>
        <inlineHelpText>Indicates the date that the reminder notification will be sent to the Reference Lead Owner.</inlineHelpText>
        <label>Reminder Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Response_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that a response of some kind has been submitted from the VF page</description>
        <inlineHelpText>Indicates that a response of some kind has been submitted from the VF page</inlineHelpText>
        <label>Response Received</label>
        <type>Checkbox</type>
    </fields>
    <label>Reference Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Controls the overall visibility of this Referenceability Type throughout ReferenceEdge – Referenceability, Requests, Projects, Nominations, Reference Use.</inlineHelpText>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/ReferenceByLeadControllerSLDS.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 * 
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 * 
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"),
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR,
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING,
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS
 * WRITTEN CONSENT FROM COMPANY.
 */
/**
 * VF Page: ReferenceByLeadSLDS.page
 * Description: Class to manage reference lead request
 * Author: Gaurav Saini (18 April, 2017)
 * Last modified by: Gaurav Saini (18 April, 2017)
 */
public with sharing class ReferenceByLeadControllerSLDS extends RefEdgeEditionFeatures {
    
    public String refLeadId { get; set; }
    public String followUpDaysListJSON { get; set; }
    private static Custom_Settings__c cs = UtilityController.getCustomSettings();
    private static String LINK_URL = URL.getSalesforceBaseUrl().toExternalForm() + Page.referencebylead.getURL() + '?id=';
    //  REF-2008    To check whether to show notification on screen or not
	public Boolean isScreenNotification{ get; set; }

    /**
     * constructor to use this as an extension on RefProspectorResponsePage
     * author: Gaurav Saini (16 Nov, 2017) #1104
     */
    public ReferenceByLeadControllerSLDS(RefProspectorResponseController controller) {}
    
    public ReferenceByLeadControllerSLDS(ApexPages.StandardController controller) {
    	refLeadId = '';
    	List<String> followUpDaysList = new List<String>();
    	
    	if (ApexPages.currentPage().getParameters().get('Id') != null) {
	    	refLeadId = ApexPages.currentPage().getParameters().get('Id');
    	}
    	Schema.DescribeFieldResult dfr
    			= Schema.sObjectType.Reference_Lead__c.fields.getMap().get(UtilityController.appNamespace() + 'Follow_Up_Timeframe__c').getDescribe();
        
        for (Schema.PicklistEntry ple : dfr.getPicklistValues()) {
            followUpDaysList.add(String.valueOf(ple.getValue()));
        }
        followUpDaysListJSON = JSON.serialize(followUpDaysList);
        isScreenNotification = cs.User_Reward_Onscreen_Notification__c;
    }
    
    /**
     * method to get the reference lead object
     * author: Gaurav Saini (18 April, 2017) for #5
     */
    @RemoteAction
    public static String getRefLead(String refLeadId) {
    	List<Reference_Lead__c> refLeads = WithoutSharingHelperController.getReferenceLead(refLeadId);
    	List<RefLeadWrapper> refLeadWrapperList = new List<RefLeadWrapper>();
    	
    	if (refLeads != null && refLeads.size() > 0) {
    		refLeadWrapperList.add(new RefLeadWrapper(refLeads[0]));
    		return JSON.serialize(refLeadWrapperList);
    	} else {
    		return '';
    	}
    }
    
    /**
     * method to get the account referenceable status
     * author: Gaurav Saini (18 April, 2017) for #5
     */
    @RemoteAction
    public static Boolean isAccountReferenceable(String accountId) {
    	List<Reference_Basic_Information__c> accRBIList
    				= WithoutSharingHelperController.getRBIReferenceable((Id)accountId);
		
		if (accRBIList != null && accRBIList.size() > 0) {
			return accRBIList[0].Is_Referenceable__c;
		} else {
			return false;
		}
    }
    
    /**
     * method to save the ref lead object
     * author: Gaurav Saini (24 April, 2017) for #5
     */
    @RemoteAction
    public static String saveRefLead(String refLeadJSON, Boolean isFromRefProspect) {
    	String result = '';
    	Savepoint sp = Database.setSavepoint();
    	
    	try {
    		RefLeadWrapper refLeadWrapperObj = (RefLeadWrapper)JSON.deserialize(refLeadJSON, RefLeadWrapper.class);
	    	List<Reference_Lead__c> refLeads = WithoutSharingHelperController.getReferenceLead(refLeadWrapperObj.refLeadId);
	    	List<Messaging.SingleEmailMessage> listmail = new List<Messaging.SingleEmailMessage>();
	        List<sObject> postFeedItems = new List<sObject>();
	        String previousOwnerName = refLeadWrapperObj.refLeadOwnerName;
	        // added for #959
	        String prospectPageURL = URL.getSalesforceBaseUrl().toExternalForm() + Page.RefProspectorResponsePage.getURL();
            String headerDocId = '';
            String footerDocId = '';
            Data_Mapping__c checkBackNotification = new Data_Mapping__c();
            Data_Mapping__c ownerUpdateNotification = new Data_Mapping__c();
            Set<String> notificationFieldNames = new Set<String>{UtilityController.appNamespace() + 'Check_back_in_Email__c', UtilityController.appNamespace() + 'Ref_Lead_Owner_Update_Email__c'};

            for (Data_Mapping__c dm : [SELECT Field_API_Name__c, Label__c, Section_Name__c, DC_Message__c, Default__c, Visible__c
                                        FROM Data_Mapping__c
                                        WHERE Object__c = 'Notification'
                                        AND (Field_API_Name__c IN :notificationFieldNames
                                            OR Section_Name__c = 'email header doc'
                                            OR Section_Name__c = 'email footer doc')]) {

                if (dm.Field_API_Name__c == UtilityController.appNamespace() + 'Check_back_in_Email__c') {
                    checkBackNotification = dm;
                } else if (dm.Field_API_Name__c == UtilityController.appNamespace() + 'Ref_Lead_Owner_Update_Email__c') {
                    ownerUpdateNotification = dm;
                } else if (dm.Section_Name__c == 'email header doc') {
                    headerDocId = dm.Field_API_Name__c;
                } else if (dm.Section_Name__c == 'email footer doc') {
                    footerDocId = dm.Field_API_Name__c;
                }
            }
            Map<String, Object> slackReqBody = new Map<String, Object>();
            slackReqBody.put('teamId', cs.Slack_Team_Ids__c);
            slackReqBody.put('orgId', UserInfo.getOrganizationId());
            List<Map<String, String>> messagesList = new List<Map<String, String>>();
	    	
	    	if (refLeads != null && refLeads.size() > 0) {
	    		Reference_Lead__c tempRefLead = refLeads[0];
	    		
		    	if (refLeadWrapperObj.followUpTimeFrame != '' && refLeadWrapperObj.refLeadOwnerId == '') {
		    		String mailBody = checkBackNotification.DC_Message__c;
                    mailBody = mailBody.replace('[Opportunity Account]', refLeadWrapperObj.accountName)
                                        .replace('[Specified Timeframe]', refLeadWrapperObj.followUpTimeFrame);
	                String days = refLeadWrapperObj.followUpTimeFrame.split(' ')[0];
	                tempRefLead.Response_received__c = true;
	                tempRefLead.Notification_response__c = 'Check back with me later';
	                tempRefLead.Follow_up_date__c = date.today() + Integer.valueOf(days);
	                tempRefLead.Reminder_Date__c = (cs.RLF_Reminder_Days__c != null
	                									? date.today().addDays(Integer.valueOf(days)
	                												+ Integer.Valueof(cs.RLF_Reminder_Days__c)) : null);
	                tempRefLead.Reference_Lead_Status__c = 'Follow up';
	                
	                if (cs.No_Response_days__c != null) {
	                    tempRefLead.No_Response_Date__c
	                    		= tempRefLead.Follow_up_date__c.addDays(Integer.valueOf(cs.No_Response_days__c));
	                }
	                tempRefLead = WithoutSharingHelperController.updateRefLead(tempRefLead);
			    	result = 'success';
	                
	                if (cs.Check_back_in_Chatter__c && UtilityController.isNativeChatterSetting) {
	                    postFeedItems.add(MailChatterController.preparePost(checkBackNotification.Section_Name__c.replace('[Opportunity Account]', refLeadWrapperObj.accountName),
                                                                            tempRefLead.Reference_Lead_Owner__c, mailBody, ''));
	                }
	                
	                if (cs.Check_back_in_Email__c) {
	                    listmail.add(MailChatterController.prepareEmail(checkBackNotification.Section_Name__c.replace('[Opportunity Account]', refLeadWrapperObj.accountName),
                                                                        tempRefLead.Reference_Lead_Owner__c, mailBody, true, headerDocId, footerDocId));
	                }
	                
	                if (cs.Enable_Slack_Integration__c && cs.Check_back_in_Slack__c) {
                        Map<String, String> tempReqBodyMap = new Map<String, String>();
                        tempReqBodyMap.put('userEmail', refLeadWrapperObj.refLeadOwnerEmail);
                        tempReqBodyMap.put('text', '*' + checkBackNotification.Section_Name__c.replace('[Opportunity Account]', refLeadWrapperObj.accountName) + '*\n' + mailBody);
                        messagesList.add(tempReqBodyMap);
	                }
		    	} else if (refLeadWrapperObj.followUpTimeFrame == '' && refLeadWrapperObj.refLeadOwnerId != '') {
		    		tempRefLead.Response_received__c = true;
	                tempRefLead.Notification_response__c = 'I don\'t know, I\'m not the right person to ask';
	                tempRefLead.Reference_Lead_Owner__c = refLeadWrapperObj.refLeadOwnerId;
	                tempRefLead = WithoutSharingHelperController.updateRefLead(tempRefLead);
	                result = 'success';
	                String mailBody = '';
	                
	                if (isFromRefProspect) {
	                	mailBody = refLeadWrapperObj.refLeadOwnerName + ',\n\n'
        								+ (cs.Ref_Prospector_Body__c != null
        									? cs.Ref_Prospector_Body__c
        									: 'The customer reference team is always seeking new ways to showcase client success. Accounts including the ones below have been identified as owned by you and potential candidates for the customer reference program. Do you think they would act as a reference at this time?')
    									+ '\n\n' + 'Accounts requiring your review include:\n'
    									+ refLeadWrapperObj.accountName;
	                	
	                	if (UtilityController.isNativeChatterSetting) {
	                		postFeedItems.add(MailChatterController.preparePost((cs.Ref_Prospector_Subject__c != null
																					? cs.Ref_Prospector_Subject__c
																					: 'Potential Reference Accounts'),
	                    														tempRefLead.Reference_Lead_Owner__c,
	                    														mailBody,
	                    														prospectPageURL));
	                	}
	                	listmail.add(MailChatterController.prepareEmail((cs.Ref_Prospector_Subject__c != null
																			? cs.Ref_Prospector_Subject__c
																			: 'Potential Reference Accounts'),
																		tempRefLead.Reference_Lead_Owner__c,
																		mailBody + '\n\n' + prospectPageURL,
																		true));
                        
                        if (cs.Enable_Slack_Integration__c) {
                            Map<String, String> tempReqBodyMap = new Map<String, String>();
                            tempReqBodyMap.put('userEmail', refLeadWrapperObj.refLeadOwnerEmail);
                            tempReqBodyMap.put('text', mailBody + '\n<' + prospectPageURL + '|'
                                    + (cs.Ref_Prospector_Subject__c != null ? cs.Ref_Prospector_Subject__c : 'Potential Reference Accounts') + '>');
                            messagesList.add(tempReqBodyMap);
                        }
	                } else {
		                mailBody = ownerUpdateNotification.DC_Message__c;
                        mailBody = mailBody.replace('[Opportunity Account]', refLeadWrapperObj.accountName)
                                            .replace('[Opportunity Owner]', previousOwnerName)
                                            .replace('[Opportunity Name]', refLeadWrapperObj.oppName);
		                
		                if (cs.Ref_Lead_Owner_Update_Chatter__c && UtilityController.isNativeChatterSetting) {
		                    postFeedItems.add(MailChatterController.preparePost(ownerUpdateNotification.Section_Name__c.replace('[Opportunity Account]', refLeadWrapperObj.accountName),
                                                                                tempRefLead.Reference_Lead_Owner__c, mailBody, LINK_URL + tempRefLead.Id));
		                }
		                
		                if (cs.Ref_Lead_Owner_Update_Email__c) {
		                    listmail.add(MailChatterController.prepareEmail(ownerUpdateNotification.Section_Name__c.replace('[Opportunity Account]', refLeadWrapperObj.accountName),
                                                                            tempRefLead.Reference_Lead_Owner__c, mailBody + '\n\n' + ownerUpdateNotification.Section_Name__c.replace('[Opportunity Account]', refLeadWrapperObj.accountName)
                                                                            + ': <a href="' + LINK_URL + tempRefLead.Id + '">' + LINK_URL + tempRefLead.Id + '</a>', true, headerDocId, footerDocId));
		                }

                        if (cs.Enable_Slack_Integration__c && cs.Ref_Lead_Owner_Update_Slack__c) {
                            Map<String, String> tempReqBodyMap = new Map<String, String>();
                            tempReqBodyMap.put('userEmail', refLeadWrapperObj.refLeadOwnerEmail);
                            tempReqBodyMap.put('text', mailBody + '\n<' + LINK_URL + tempRefLead.Id + '|'
                                    + ownerUpdateNotification.Section_Name__c.replace('[Opportunity Account]', refLeadWrapperObj.accountName) + '>');
                            messagesList.add(tempReqBodyMap);
                        }
	                }
	                
	                // re #119 - Added sales rewards for User  
	                if (RefEdgeEditionFeatures.isBasic == false && cs.Enable_Sales_Rewards_Notification__c == true) {
		                List<Referenceability_Type__c> refType = [SELECT Name, Id, Sales_Point__c
		                											FROM Referenceability_Type__c
		                											WHERE Visible__c = true AND Sales_Reward__c = true
		                											AND Referenceability_code__c = :ConstantsController.RLF_REFERRED
		                											ORDER BY Referenceability_code__c LIMIT 1];
		                
		                // re #633 - Check null value for Sales point 
		                if (refType.size() > 0 && refType[0].Sales_Point__c != null) {
		                    List<Reward__c> rewardsToBeInsert = new List<Reward__c>();
		                    
		                    if (tempRefLead.Response_Received__c == true ) {
		                        Reference_Lead__c refId = [SELECT OwnerId FROM Reference_Lead__c
		                        							WHERE Id = :tempRefLead.Id LIMIT 1];
		                        rewardsToBeInsert.add(new Reward__c(Amount__c = refType[0].Sales_Point__c,
		                        									Referenceability_Type__c = refType[0].Id,
		                        									Transaction__c = ConstantsController.ISSUE,
		                        									RewardDate__c = Date.Today(),
		                        									User__c = UserInfo.getUserId()));	// re #240
		                        UtilityController.isUserProfileExist(refId.OwnerId);
		                        String rewardPoints = String.valueOf(refType[0].Sales_Point__c);
		                        String actionMessage =  refType[0].Name;
		                        result += '***' + rewardPoints + '***' + actionMessage;
		                    }
		                    
		                    if (rewardsToBeInsert.size() > 0) {
		                        WithoutSharingHelperController.insertRewards(rewardsToBeInsert);
		                    }
						}
					}
		    	} else if (refLeadWrapperObj.followUpTimeFrame == '' && refLeadWrapperObj.refLeadOwnerId == '') {
		    		tempRefLead.Response_received__c = true;
		    		tempRefLead.Reference_Lead_Status__c = 'No Updates';
	                tempRefLead = WithoutSharingHelperController.updateRefLead(tempRefLead);
	                result = 'success';
		    	}
	    	}
			
	        if (listmail.size() > 0) {
	            Messaging.sendEmail(listmail);
	        }
	        
	        if (postFeedItems.size() > 0) {
	            postFeedItems = WithoutSharingHelperController.insertPostFeedItems(postFeedItems);
	        }

            if (messagesList != null && messagesList.size() > 0) {
            	slackReqBody.put('messages', messagesList);
            	UtilityController.postMsgToSlack(JSON.serialize(slackReqBody));
            }
    	} catch(Exception e) {
    		Database.rollback(sp);
    		result = CRUDAndFLSCheckController.getCleanSystemErrorMsg(e.getMessage());
    	}
    	return result;
    }
    
    /**
	 * Wrapper Class for reference lead object
	 */
    public class RefLeadWrapper {
    	public String refLeadId { get; set; }
    	public String status { get; set; }
    	public String refProfileId { get; set; }
    	public String accountId { get; set; }
    	public String accountName { get; set; }
    	public String nominationId { get; set; }
    	public String oppId { get; set; }
    	public String oppName { get; set; }
    	public String refLeadOwnerName { get; set; }
    	public String refLeadOwnerId { get; set; }
    	public String refLeadOwnerEmail { get; set; }
    	public String followUpTimeFrame { get; set; }
    	public Boolean createNomination { get; set; }
    	
    	public RefLeadWrapper(Reference_Lead__c refLead) {
    		this.refLeadId = refLead.Id;
    		this.status = refLead.Reference_Lead_Status__c;
	    	this.refProfileId = refLead.Reference_Profile__c;
	    	this.accountId = refLead.Reference_Lead_Account__c;
	    	this.accountName = refLead.Reference_Lead_Account__r.Name;
	    	this.nominationId = refLead.Nomination__c;
	    	this.oppId = refLead.Reference_Lead_Opportunity__c;
	    	this.oppName = refLead.Reference_Lead_Opportunity__r.Name;
	    	this.refLeadOwnerName = refLead.Reference_Lead_Owner__r.Name;
	    	this.refLeadOwnerEmail = refLead.Reference_Lead_Owner__r.Email;
	    	this.refLeadOwnerId = '';
	    	this.followUpTimeFrame = '';
	    	this.createNomination = cs.Create_Nomination__c;
    	}
    }
}