POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Invitation__c.object
<CustomObject>
    <description>Content Sharing (Bound 4)</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invitations</relationshipLabel>
        <relationshipName>Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invitation</label>
    <nameField>
        <label>Invitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request__c.object
<CustomObject>
    <description>This object holds the information necessary for a reference request</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity association</description>
        <inlineHelpText>Associated opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Reference Requests</relationshipLabel>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Request</label>
    <nameField>
        <displayFormat>RR-{000000000}</displayFormat>
        <label>Reference Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Requests_and_Invitations__c.object
<CustomObject>
    <description>RefEdge Object that combines the peer data of Invitations and Reference Requests (both of which are related children of Opportunity) for comprehensive Revenue Influenced reporting.</description>
    <fields>
        <fullName>Invitation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invitation</label>
        <referenceTo>Invitation__c</referenceTo>
        <relationshipLabel>Reference Requests and Invitations</relationshipLabel>
        <relationshipName>Reference_Requests_and_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Reference Requests and Invitations</relationshipLabel>
        <relationshipName>Reference_Requests_and_Invitations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipLabel>Reference Requests and Invitations</relationshipLabel>
        <relationshipName>Reference_Requests_and_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Requests and Invitations</label>
    <nameField>
        <displayFormat>RRI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests and Invitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestBatch_DataCreate_RRI.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */ 
@isTest(seeAllData = false)
public with sharing class TestBatch_DataCreate_RRI {
    //Unit Test 01 Escalation To Owner Manager when Include Weekends = false
    static testmethod void myUnitTest01() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List < Account > accounts = TestDataFactory.createAccounts();
        insert accounts;
        List < Opportunity > opps = TestDataFactory.createOpportunity(accounts);
        insert opps;
        list<Reference_Request__c> refReqs = TestDataFactory.createReferenceRequest();
        integer index = 0;
        for(Reference_Request__c rr : refReqs){
            rr.Opportunity__c = opps[index].Id;
            index++;
            if(index >= opps.size())
                index = 0;
        }
        insert refReqs;
        List < Invitation__c > invitations = TestDataFactory.createInvitation(opps);
        insert invitations;
        delete [select Id from Reference_Requests_and_Invitations__c where Opportunity__c IN : opps];
        list<Reference_Requests_and_Invitations__c> listNewRRI = new list<Reference_Requests_and_Invitations__c> ();
        listNewRRI.add(new Reference_Requests_and_Invitations__c(Opportunity__c = opps[0].Id,  Reference_Request__c = refReqs[0].Id));
        listNewRRI.add(new Reference_Requests_and_Invitations__c(Opportunity__c = opps[1].Id,  Invitation__c = invitations[0].Id));
        insert listNewRRI;
        test.startTest();
            Batch_DataCreate_RRI batchrrr = new Batch_DataCreate_RRI();
            ID batchprocessid = database.executebatch(batchrrr);
        test.stopTest();
        List <Reference_Requests_and_Invitations__c> rraiList = [select Id from Reference_Requests_and_Invitations__c];
        system.assert(rraiList.size() > 0);
    }
}