POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</description>
        <inlineHelpText>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</inlineHelpText>
        <label>Reference Program Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lifetime_Points__c</fullName>
        <label>Lifetime Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Referenceability_Status__c</fullName>
        <inlineHelpText>The Reference Status for an Account or Contact, in combination with Reference Program Membership, determines if a record may be included in Reference Search results. Only records with Active or Caution status may be included.</inlineHelpText>
        <label>Reference Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reward__c.object
<CustomObject>
    <description>Custom Object to Store Rewards.(Bound 4)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Available_Points__c</fullName>
        <label>Available Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Type</label>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RewardDate__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <picklist>
            <picklistValues>
                <fullName>Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeem</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <displayFormat>RW-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/User_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Available_Points__c</fullName>
        <label>Available Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lifetime_Points__c</fullName>
        <label>Lifetime Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RefEdge User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_User_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RefEdge User Profile</label>
    <nameField>
        <displayFormat>SUP-{0000}</displayFormat>
        <label>Sales User Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RefEdge User Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestEditRewardController.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
/**
 * Class: EditRewardController
 * Description: class to test AND cover EditRewardController
 * Modified by: Rekha Jangir @1 June 2017
 */
@isTest(seeAllData = false)
public with sharing class TestEditRewardController {
	/**
     * Method to cover save method and Constructor from Account
     * Modified By: Rekha Jangir @1 June 2017
     */
    static testMethod void testIssueEditAccount() {
    	//insert test Data
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        Account account = TestDataFactory.createAccounts()[0];
        insert account;
        insert new Reference_Basic_Information__c(Account__c = account.Id, Is_Referenceable__c = true, Referenceability_Status__c= 'Active');
        Referenceability_Type__c refType = TestDataFactory.createReferenceabilityType()[0];
        insert refType;
        Reward__c reward = new Reward__c(Account__c = account.Id, Referenceability_Type__c = refType.Id, Amount__c = 100, 
        								Available_Points__c = 100, Transaction__c = ConstantsController.ISSUE, Expiration_Date__c = system.today().addDays(5), 
        								RewardDate__c = Date.Today());
        insert reward;
        
        //Start Test method
        test.startTest();
            PageReference pageRef = Page.EditReward;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.standardController(reward);
            EditRewardController erc = new EditRewardController(sc);
            erc.reward.Expired__c = true;
            PageReference pg = erc.save();
            List<Reward__c> rewards = [SELECT Id, Expired__c FROM Reward__c WHERE Id = :reward.Id];
            system.assertEquals(true, rewards[0].Expired__c);
        //Stop Test method
        test.stopTest();
    }
    
    /**
     * Method to cover save method and Constructor from Contact
     * Modified By: Rekha Jangir @1 June 2017
     */
    static testMethod void testIssueEditAccountContact() {
    	//insert test Data
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List<Account> accounts = TestDataFactory.createAccounts();
        insert accounts;
        TestDataFactory.setUpAccountRBI(accounts);
        Referenceability_Type__c refType = TestDataFactory.createReferenceabilityType()[0];
        insert refType;
        List<Contact> contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        Reward__c reward = new Reward__c(Available_Points__c = 500, Amount__c = 500, Contact__c = contacts[0].Id, Account__c = accounts[0].Id, 
        									Transaction__c = ConstantsController.ISSUE);
        insert reward;
        //Start Test method
        test.startTest();
            PageReference pageRef = Page.EditReward;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.standardController(reward);
            EditRewardController erc = new EditRewardController(sc);
            erc.reward.Expired__c = true;
            PageReference pg = erc.save();
            List<Reward__c> rewards = [SELECT Id, Expired__c FROM Reward__c WHERE Id = :reward.Id];
            system.assertEquals(true, rewards[0].Expired__c);
            erc.reward.Expired__c = false;
            erc.reward.Amount__c = 200;
            erc.save();
            erc.cancel();
            system.assertNotEquals(erc.todayDate,'');
        //Stop Test method
        test.stopTest();
    }
    
    /**
     * Method to cover save method and Constructor from User
     * Modified By: Rekha Jangir @1 June 2017
     */
    static testMethod void testIssueEditUser() {
    	// insert test data
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        User_Profile__c userProile=new User_Profile__c(Available_Points__c = 0, Lifetime_Points__c = 0, User__c = UserInfo.getUserId());
    	insert userProile;
        Reward__c reward = new Reward__c(Available_Points__c = 250, Amount__c = 250, User__c = UserInfo.getUserId(), Transaction__c = ConstantsController.ISSUE);
        insert reward;
        //Start test method
        test.startTest();
            PageReference pageRef = Page.EditReward;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.standardController(reward);
            EditRewardController erc = new EditRewardController(sc);
            erc.reward.Expired__c = true;
            PageReference pg = erc.save();
            List<Reward__c> rewards = [SELECT Id, Expired__c FROM Reward__c WHERE Id = :reward.Id];
            system.assertEquals(true, rewards[0].Expired__c);
        //Stop test method
        test.stopTest();
    }
    
    /**
     * Method to cover cancel method
     * Modified By: Rekha Jangir @1 June 2017
     */
    static testMethod void testIssueEditWithURLs() {
    	//insert test data
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        Account account = TestDataFactory.createAccounts()[0];
        insert account;
        insert new Reference_Basic_Information__c(Account__c = account.Id, Is_Referenceable__c = true, Referenceability_Status__c= 'Active');
        Referenceability_Type__c refType = TestDataFactory.createReferenceabilityType()[0];
        insert refType;
        Reward__c reward = new Reward__c(Account__c = account.Id, Referenceability_Type__c = refType.Id, Amount__c = 100, 
        								Available_Points__c = 100, Transaction__c = ConstantsController.ISSUE, 
        								Expiration_Date__c = system.today().addDays(5), RewardDate__c = Date.Today());
        insert reward;
        //Start Test method
        test.startTest();
	        PageReference pageRef = Page.EditReward;
	        Test.setCurrentPage(pageRef);
	        
	        pageRef.getParameters().put('retURL', null);
	        ApexPages.StandardController sc = new ApexPages.standardController(reward); 
	        EditRewardController erc = new EditRewardController(sc);
	        PageReference pg;  
		    pg = erc.cancel();
		    system.assertEquals(pg.getUrl(), '/' + reward.Id);
	      
	        
	        pageRef.getParameters().put('retURL', reward.Id);
	        sc = new ApexPages.standardController(reward); 
	        erc = new EditRewardController(sc); 
	        pg = erc.cancel();
		    system.assertEquals(pg.getUrl(), '/' + reward.Id);
	        
	        pageRef.getParameters().put('retURL', System.URL.getSalesforceBaseURL().toExternalForm());
	        sc = new ApexPages.standardController(reward); 
	        erc = new EditRewardController(sc); 
		    pg = erc.cancel();
		    system.assertEquals(pg.getUrl(), System.URL.getSalesforceBaseURL().toExternalForm());
	        
	        pageRef.getParameters().put('retURL', '/' + 'www.xyz.com');
	        sc = new ApexPages.standardController(reward); 
	        erc = new EditRewardController(sc); 
		    pg = erc.cancel();
		    system.assertNotEquals(pg.getUrl(), 'www.xyz.com');
		    
		    pageRef.getParameters().put('retURL', '/' + 'www.xyz.com');
	        sc = new ApexPages.standardController(reward); 
	        erc = new EditRewardController(sc); 
		    pg = erc.cancel();
		    system.assertEquals(pg.getUrl(), '//www.xyz.com');
		    
		    pageRef.getParameters().put('retURL', null);
	        sc = new ApexPages.standardController(new Reward__c()); 
	        erc = new EditRewardController(sc); 
		    pg = erc.cancel();
		    system.assertEquals(System.URL.getSalesforceBaseURL().toExternalForm(), pg.getUrl());
		    
        //Stop Test method
        test.stopTest(); 
    }
}