POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Create_Nomination__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When a Reference Lead results in a Reference being provided a new Nomination is created</description>
        <inlineHelpText>When a Reference Lead results in a Reference being provided a new Nomination is created</inlineHelpText>
        <label>Create Nomination?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Reference_Profile__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When a Reference Lead results in a Reference being provided a Reference Profile is created</description>
        <inlineHelpText>When a Reference Lead results in a Reference being provided a Reference Profile is created</inlineHelpText>
        <label>Create Reference Profile?</label>
        <type>Checkbox</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</description>
        <inlineHelpText>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</inlineHelpText>
        <label>Reference Program Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RUL_Activities_used__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The Completed Uses is the sum of completed reference activities or uses in the specified Time Period. On a Contact record this applies to that specific Contact. On an Account it is an aggregate of all Account and related Contact uses.</inlineHelpText>
        <label>Completed Uses</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Referenceability_Status__c</fullName>
        <inlineHelpText>The Reference Status for an Account or Contact, in combination with Reference Program Membership, determines if a record may be included in Reference Search results. Only records with Active or Caution status may be included.</inlineHelpText>
        <label>Reference Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Lead__c.object
<CustomObject>
    <description>Custom Object to track Leads for the Reference Program(Bound 8)</description>
    <fields>
        <fullName>Follow_Up_Date__c</fullName>
        <label>Follow Up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_Notification_Date__c</fullName>
        <description>Indicates the date that the FIRST notification was sent to the Reference Lead Owner</description>
        <inlineHelpText>Indicates the date that the FIRST notification was sent to the Reference Lead Owner</inlineHelpText>
        <label>Initial Notification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_Notification_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the FIRST notification was sent to the Reference Lead Owner</description>
        <inlineHelpText>Indicates that the FIRST notification was sent to the Reference Lead Owner</inlineHelpText>
        <label>Initial Notification Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Lead_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Lead Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reference Leads</relationshipLabel>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Lead_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Lead Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Reference Leads</relationshipLabel>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Lead_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is typically the Opportunity Owner but could be replaced with another name if the Opportunity Owner is no longer the correct contact</description>
        <inlineHelpText>This is typically the Opportunity Owner but could be replaced with another name if the Opportunity Owner is no longer the correct contact</inlineHelpText>
        <label>Reference Lead Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Lead</label>
    <nameField>
        <displayFormat>RL-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestReferenceByLeadController.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public with sharing class TestReferenceByLeadController {
	
	//Unit Test method for Updation
    static testMethod void testRefByLeadWithProfile() {
        try{
	        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        customSetting.Create_Reference_Profile__c = true;
	        customSetting.Create_Nomination__c = false;
	        update customSetting;
	        Account account  =  new Account(Name = 'test Account');
	        insert account;
	        Opportunity opportunity = new Opportunity(CloseDate = system.today()+1,StageName = 'Closed Won', Amount = 700,Name = 'opp1', AccountId = account.Id, OwnerId = UserInfo.getUserId());
	        insert opportunity;
	        insert new Reference_Basic_Information__c(RUL_Activities_used__c = 5,Referenceability_Status__c = 'Active', Is_Referenceable__c = true, Account__c = account.Id);
	        Reference_Lead__c refLead = new Reference_Lead__c(Reference_Lead_Owner__c = UserInfo.getUserId(),Initial_notification_date__c = system.today(), Initial_notification_sent__c = true,
						Follow_up_date__c = system.today(),Reference_Lead_Account__c = account.Id, Reference_Lead_Opportunity__c = opportunity.Id);
			insert refLead;
	        Test.startTest();
	        	PageReference pageRef = Page.referencebylead;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	           	ApexPages.StandardController sc = new ApexPages.StandardController(refLead);
	            ReferenceByLeadController form = new ReferenceByLeadController(sc);
	            form.optionSelected = '1';
	            form.redirectToRefLeadForm();
	            form.optionSelected = '2';
	            form.redirectToRefLeadForm();
	            form.loadRefLeadForm();
	            form.returnHomePage();
	            system.assert(true);
	        Test.stopTest();
        }catch(Exception e){
        	
        }
    }
    
    //Unit Test method for Updation
    static testMethod void testRefByLeadWithoutProfile() {
        try{
	        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        customSetting.Create_Reference_Profile__c = true;
	        customSetting.Create_Nomination__c = false;
	        update customSetting;
	        Account account  =  new Account(Name = 'test Account');
	        insert account;
	        Opportunity opportunity = new Opportunity(CloseDate = system.today()+1,StageName = 'Closed Won', Amount = 700,Name = 'opp1', AccountId = account.Id, OwnerId = UserInfo.getUserId());
	        insert opportunity;
	        Reference_Lead__c refLead = new Reference_Lead__c(Reference_Lead_Owner__c = UserInfo.getUserId(),Initial_notification_date__c = system.today(), Initial_notification_sent__c = true,
						Follow_up_date__c = system.today(),Reference_Lead_Account__c = account.Id, Reference_Lead_Opportunity__c = opportunity.Id);
			insert refLead;
	        Test.startTest();
	        	PageReference pageRef = Page.referencebylead;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	           	ApexPages.StandardController sc = new ApexPages.StandardController(refLead);
	            ReferenceByLeadController form = new ReferenceByLeadController(sc);
	            form.optionSelected = '1';
	            form.redirectToRefLeadForm();
	            form.optionSelected = '2';
	            form.redirectToRefLeadForm();
	            form.optionSelected = '3';
	            form.redirectToRefLeadForm();
	            form.optionSelected = '4';
	            form.redirectToRefLeadForm();
	            system.assert(true);
	        Test.stopTest();
        }catch(Exception e){
        	
        }
    }
    
    //Unit Test method for Updation
    static testMethod void testRefByLeadWithProfileNomi() {
        try{
	        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        customSetting.Create_Reference_Profile__c = false;
	        customSetting.Create_Nomination__c = true;
	        update customSetting;
	        Account account  =  new Account(Name = 'test Account');
	        insert account;
	        Opportunity opportunity = new Opportunity(CloseDate = system.today()+1,StageName = 'Closed Won', Amount = 700,Name = 'opp1', AccountId = account.Id, OwnerId = UserInfo.getUserId());
	        insert opportunity;
	        insert new Reference_Basic_Information__c(RUL_Activities_used__c = 5,Referenceability_Status__c = 'Active', Is_Referenceable__c = true, Account__c = account.Id);
	        Reference_Lead__c refLead = new Reference_Lead__c(Reference_Lead_Owner__c = UserInfo.getUserId(),Initial_notification_date__c = system.today(), Initial_notification_sent__c = true,
						Follow_up_date__c = system.today(),Reference_Lead_Account__c = account.Id, Reference_Lead_Opportunity__c = opportunity.Id);
			insert refLead;
	        Test.startTest();
	        	PageReference pageRef = Page.referencebylead;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	           	ApexPages.StandardController sc = new ApexPages.StandardController(refLead);
	            ReferenceByLeadController form = new ReferenceByLeadController(sc);
	            form.optionSelected = '1';
	            form.redirectToRefLeadForm();
	            form.optionSelected = '2';
	            form.redirectToRefLeadForm();
	            form.loadRefLeadForm();
	            form.returnHomePage();
	            system.assert(true);
	        Test.stopTest();
        }catch(Exception e){
        	
        	
        }
    }
    
    //Unit Test method for Updation
    static testMethod void testRefByLeadWithoutProfileNomi() {
        try{
	        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        customSetting.Create_Reference_Profile__c = false;
	        customSetting.Create_Nomination__c = true;
	        update customSetting;
	        Account account  =  new Account(Name = 'test Account');
	        insert account;
	        Opportunity opportunity = new Opportunity(CloseDate = system.today()+1,StageName = 'Closed Won', Amount = 700,Name = 'opp1', AccountId = account.Id, OwnerId = UserInfo.getUserId());
	        insert opportunity;
	        Reference_Lead__c refLead = new Reference_Lead__c(Reference_Lead_Owner__c = UserInfo.getUserId(),Initial_notification_date__c = system.today(), Initial_notification_sent__c = true,
						Follow_up_date__c = system.today(),Reference_Lead_Account__c = account.Id, Reference_Lead_Opportunity__c = opportunity.Id);
			insert refLead;
	        Test.startTest();
	        	PageReference pageRef = Page.referencebylead;
	            Test.setCurrentPage(pageRef);
	            pageRef.getParameters().put('Id', String.valueOf(refLead.Id));
	           	ApexPages.StandardController sc = new ApexPages.StandardController(refLead);
	            ReferenceByLeadController form = new ReferenceByLeadController(sc);
	            form.optionSelected = '1';
	            form.redirectToRefLeadForm();
	            form.optionSelected = '2';
	            form.redirectToRefLeadForm();
	            form.optionSelected = '3';
	            form.redirectToRefLeadForm();
	            form.optionSelected = '4';
	            form.redirectToRefLeadForm();
	            system.assert(true);
	        Test.stopTest();
        }catch(Exception e){
        	
        }
    }
}