POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Include_Weekends__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If selected, days specified in “Off Days of Week” will not be included in date calculations (e.g., request lead times).</inlineHelpText>
        <label>Exclude Weekends</label>
        <type>Checkbox</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request__c.object
<CustomObject>
    <description>This object holds the information necessary for a reference request</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity association</description>
        <inlineHelpText>Associated opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Reference Requests</relationshipLabel>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Request</label>
    <nameField>
        <displayFormat>RR-{000000000}</displayFormat>
        <label>Reference Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account__c.object
<CustomObject>
    <description>Junction table associating Reference Requests with accounts</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Escalation_to_Owner_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalated to Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_No_Response__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Response</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Reminder_to_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder Sent to Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <description>Reference request association</description>
        <inlineHelpText>Reference request association</inlineHelpText>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_ID__c</fullName>
        <label>Account Request Task ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Account Request</label>
    <nameField>
        <displayFormat>RRA-{000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestBatch_ReferenceRequestAccount.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public class TestBatch_ReferenceRequestAccount {
    //Unit Test 01 No response when Include Weekends = false
    static testmethod void myUnitTest01() {
        User u = TestDataFactory.CreateUser();
        insert u;
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        customSetting.Include_Weekends__c = false;
        update customSetting;
        List<Account> accounts = TestDataFactory.createAccounts();
        
        system.runAs(u) {
            insert accounts;
        }
        List<Opportunity> opps = TestDataFactory.createOpportunity(accounts);
        insert opps;
        List<Referenceability_Type__c> refTypes = TestDataFactory.createReferenceabilityType();
        insert refTypes;
        list<Reference_Request__c> refReqs = TestDataFactory.createMoreReferenceRequest();
        integer index = 0;
        
        for (Reference_Request__c rr : refReqs) {
            rr.Opportunity__c = opps[index].Id;
            index++;
            
            if (index >= opps.size()) {
                index = 0;
                }                 
        }
        insert refReqs;
        
        list<Task> tasks = TestDataFactory.createTask();
        insert tasks;        
        List<Reference_Request_Account__c> refReqAccs = TestDataFactory.createAccountRequests(accounts, refReqs, refTypes);
        
        for (Reference_Request_Account__c rra : refReqAccs) {
            rra.Task_ID__c = tasks[0].Id;
            rra.Deadline__c = Date.today();
            rra.Is_Reminder_to_Owner__c = false;
            rra.Reference_Owner__c = u.Id;
            rra.Project_Owner__c = u.Id;
            rra.Is_Escalation_to_Owner_Manager__c = false;
            rra.Requester__c = u.Id;
        }
        insert refReqAccs;
        test.startTest();
            //update Reference_Request_Account
            refReqAccs[0].Deadline__c = (system.today()).addDays(1);
            update refReqAccs[0];
            Batch_ReferenceRequestAccount batchrrr = new Batch_ReferenceRequestAccount();
            ID batchprocessid = database.executebatch(batchrrr);
        test.stopTest();
        List<Reference_Request_Account__c> rraList = [select Id, Is_No_Response__c from Reference_Request_Account__c where Id = : refReqAccs[0].Id];
        system.assertEquals(rraList[0].Is_No_Response__c, true);
    }

    //Unit Test 02 No response when Include Weekends = true
    static testmethod void myUnitTest02() {
        User u = TestDataFactory.CreateUser();
        insert u;
        
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        update customSetting;
        List<Account> accounts = TestDataFactory.createAccounts();
        
        system.runAs(u) {
            insert accounts;
        }
        List<Opportunity> opps = TestDataFactory.createOpportunity(accounts);
        insert opps;
        List<Referenceability_Type__c> refTypes = TestDataFactory.createReferenceabilityType();
        insert refTypes;
        List<Reference_Request__c> refReqs = TestDataFactory.createMoreReferenceRequest();
        integer index = 0;
        
        for (Reference_Request__c rr : refReqs) {
            rr.Opportunity__c = opps[index].Id;
            index++;
            
            if (index >= opps.size()) {
                index = 0;
            }
        }
        insert refReqs;        
        List<Task> tasks = TestDataFactory.createTask();
        insert tasks;
        
        List<Reference_Request_Account__c> refReqAccs = TestDataFactory.createAccountRequests(accounts, refReqs, refTypes);
        
        for (Reference_Request_Account__c rra : refReqAccs) {
            rra.Task_ID__c = tasks[0].Id;
            rra.Deadline__c = Date.today();
            rra.Is_Reminder_to_Owner__c = false;
            rra.Reference_Owner__c = u.Id;
            rra.Project_Owner__c = u.Id;
            rra.Is_Escalation_to_Owner_Manager__c = false;
            rra.Requester__c = u.Id;
        }
        insert refReqAccs;
        test.startTest();
            //update Reference_Request_Account
            refReqAccs[0].Deadline__c = (system.today()).addDays(2);
            update refReqAccs[0];
           Batch_ReferenceRequestAccount batchrrr = new Batch_ReferenceRequestAccount();
            ID batchprocessid = database.executebatch(batchrrr);
        test.stopTest();
        List<Reference_Request_Account__c> rraList = [select Id, Is_No_Response__c from Reference_Request_Account__c where Id = : refReqAccs[0].Id];
        system.assert(rraList.size() > 0);
    }

    //Unit Test 03 No response when NO_RESPONSE = 0
    static testmethod void myUnitTest03() {
        User u = TestDataFactory.CreateUser();
        insert u;
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        customSetting.Include_Weekends__c = false;
        update customSetting;
        List<Account> accounts = TestDataFactory.createAccounts();
        
        system.runAs(u) {
            insert accounts;
        }
        List<Opportunity> opps = TestDataFactory.createOpportunity(accounts);
        insert opps;
        List<Referenceability_Type__c> refTypes = TestDataFactory.createReferenceabilityType();
        insert refTypes;
        List<Reference_Request__c> refReqs = TestDataFactory.createMoreReferenceRequest();
        integer index = 0;
        
        for (Reference_Request__c rr : refReqs) {
            rr.Opportunity__c = opps[index].Id;
            index++;
            
            if (index >= opps.size()) {
                index = 0;
            }
        }
        insert refReqs;
        List<Task> tasks = TestDataFactory.createTask();
        insert tasks;        
        List<Reference_Request_Account__c> refReqAccs = TestDataFactory.createAccountRequests(accounts, refReqs, refTypes);
        
        for (Reference_Request_Account__c rra : refReqAccs) {
            rra.Task_ID__c = tasks[0].Id;
            rra.Deadline__c = Date.today();
            rra.Is_Reminder_to_Owner__c = true;
            rra.Reference_Owner__c = u.Id;
            rra.Project_Owner__c = u.Id;
            rra.Is_Escalation_to_Owner_Manager__c = true;
            rra.Requester__c = u.Id;
        }
        insert refReqAccs;
        test.startTest();
            refReqAccs[0].Deadline__c = (system.today()).addDays(0);
            update refReqAccs[0];
            Batch_ReferenceRequestAccount batchrrr = new Batch_ReferenceRequestAccount();
            ID batchprocessid = database.executebatch(batchrrr);
        test.stopTest();
        List<Reference_Request_Account__c> rraList = [select Id, Is_No_Response__c from Reference_Request_Account__c where Id = : refReqAccs[0].Id];
        system.assert(rraList.size() > 0);
    }
    
    //Unit Test 04 Escalation
    static testmethod void myUnitTest04() {
        User u = TestDataFactory.CreateUser();
        insert u;
        User u2 = TestDataFactory.CreateUser();
        u2.firstname = 'testportest2';
        u2.lastname = 'testportest2';
        u2.Alias = 'portest2';
        u2.email = 'testportest@testportest2.com';
        u2.username = 'testportest@testportest2.com';
        u2.ManagerId = u.Id;
        insert u2;
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List<Account> accounts = TestDataFactory.createAccounts();
        
        system.runAs(u2) {
            insert accounts;
        }
        List<Opportunity> opps = TestDataFactory.createOpportunity(accounts);
        insert opps;
        List<Referenceability_Type__c> refTypes = TestDataFactory.createReferenceabilityType();
        insert refTypes;
        List<Reference_Request__c> refReqs = TestDataFactory.createMoreReferenceRequest();
        integer index = 0;
        
        for (Reference_Request__c rr : refReqs) {
            rr.Opportunity__c = opps[index].Id;
            index++;
            
            if (index >= opps.size()) {
                index = 0;
            }
        }
        insert refReqs;        
        List<Task> tasks = TestDataFactory.createTask();
        insert tasks;        
        List<Reference_Request_Account__c> refReqAccs = TestDataFactory.createAccountRequests(accounts, refReqs, refTypes);
        
        for (Reference_Request_Account__c rra : refReqAccs) {
            rra.Task_ID__c = tasks[0].Id;
            rra.Deadline__c = Date.today();
            rra.Is_Reminder_to_Owner__c = true;
            rra.Reference_Owner__c = u2.Id;
            rra.Project_Owner__c = u2.Id;
        }
        insert refReqAccs;
        test.startTest();
            //update Reference_Request_Account
            refReqAccs[0].Deadline__c = (system.today()).addDays(2);
            update refReqAccs[0];
            Batch_ReferenceRequestAccount batchrrr = new Batch_ReferenceRequestAccount();
            ID batchprocessid = database.executebatch(batchrrr);
        //Stop test method
        test.stopTest();
        List<Reference_Request_Account__c> rraList = [select Id, Is_Escalation_to_Owner_Manager__c from Reference_Request_Account__c where Id = : refReqAccs[0].Id];
        system.assert(rraList.size() > 0);
    }
    
    //Unit Test 05 Reminder
    static testmethod void myUnitTest05() {
        User u = TestDataFactory.CreateUser();
        insert u;
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        customSetting.Include_Weekends__c = false;
        update customSetting;
        List<Account> accounts = TestDataFactory.createAccounts();
        
        system.runAs(u) {
          insert accounts;
        }
        List<Opportunity> opps = TestDataFactory.createOpportunity(accounts);
        insert opps;
        List<Referenceability_Type__c> refTypes = TestDataFactory.createReferenceabilityType();
        insert refTypes;
        List<Reference_Request__c> refReqs = TestDataFactory.createMoreReferenceRequest();
        integer index = 0;
        
        for (Reference_Request__c rr : refReqs) {
          rr.Opportunity__c = opps[index].Id;
          index++;
          
           if (index >= opps.size()) {
             index = 0;
           }
        }
        insert refReqs;        
        List<Task> tasks = TestDataFactory.createTask();
        insert tasks;        
        List < Reference_Request_Account__c > refReqAccs = TestDataFactory.createAccountRequests(accounts, refReqs, refTypes);
        
        for (Reference_Request_Account__c rra : refReqAccs) {
          rra.Task_ID__c = tasks[0].Id;
          rra.Deadline__c = Date.today();
          rra.Reference_Owner__c = u.Id;
          rra.Project_Owner__c = u.Id;
          rra.Is_Reminder_to_Owner__c = false;
          rra.Requester__c = u.Id;
        }
        insert refReqAccs;
        //Start test method
        test.startTest();
          //update Reference_Request_Account
          refReqAccs[0].Deadline__c = (system.today()).addDays(3);
          update refReqAccs[0];
          Batch_ReferenceRequestAccount batchrrr = new Batch_ReferenceRequestAccount();
          ID batchprocessid = database.executebatch(batchrrr);
        //Stop test method
        test.stopTest();
        List<Reference_Request_Account__c> rraList = [select Id, Is_Reminder_to_Owner__c from Reference_Request_Account__c where Id = : refReqAccs[0].Id];
        system.assert(rraList.size() > 0);         
    }    
    
}