POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Infl_Event_Fetch_DateTime__c</fullName>
        <description>This field store information that when we fetch last events from Infl_Batch_Events.</description>
        <inlineHelpText>This field store information that when we fetch last events from Infl_Batch_Events. 
Don&apos;t Modify this field.</inlineHelpText>
        <label>Infl Event Fetch DateTime</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Influitive_Integration_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Influitive Integration Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Available_Balance_Points__c</fullName>
        <label>Current Available Balance Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</description>
        <inlineHelpText>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</inlineHelpText>
        <label>Reference Program Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lifetime_Points__c</fullName>
        <label>Lifetime Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Referenceability_Status__c</fullName>
        <inlineHelpText>The Reference Status for an Account or Contact, in combination with Reference Program Membership, determines if a record may be included in Reference Search results. Only records with Active or Caution status may be included.</inlineHelpText>
        <label>Reference Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Note__c</fullName>
        <inlineHelpText>Visible only on the Edit page of Referenceability Types.</inlineHelpText>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when creating a new project from the Ref Workspace.</inlineHelpText>
        <label>Project type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referenceability_code__c</fullName>
        <description>This is use to give event api code.</description>
        <inlineHelpText>This is use to give event api code.</inlineHelpText>
        <label>Referenceability_code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when making a request.</inlineHelpText>
        <label>Request type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reward_points__c</fullName>
        <description>This Field Use for Colletion of Reward Point as per Ref Type</description>
        <inlineHelpText>Points that are awarded at the completion of a reference use.</inlineHelpText>
        <label>Customer Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Controls the overall visibility of this Referenceability Type throughout ReferenceEdge – Referenceability, Requests, Projects, Nominations, Reference Use.</inlineHelpText>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>max_accounts_per_request_type__c</fullName>
        <inlineHelpText>Maximum quantity of accounts that can be requested when this is the only request type in a Request.</inlineHelpText>
        <label>Max Accounts per Request</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>min_lead_time_per_request_type__c</fullName>
        <inlineHelpText>Time required by the reference team to fulfill a Managed Request.</inlineHelpText>
        <label>Lead Time</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reward__c.object
<CustomObject>
    <description>Custom Object to Store Rewards.(Bound 4)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Available_Points__c</fullName>
        <label>Available Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expired_Points__c</fullName>
        <label>Expired Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Influitive_ID2__c</fullName>
        <externalId>true</externalId>
        <label>Influitive ID2</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Type</label>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RewardDate__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <picklist>
            <picklistValues>
                <fullName>Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeem</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <displayFormat>RW-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestInfl_Batch_Events.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public class TestInfl_Batch_Events {
	//Sync reward 
    static testmethod void syncRewardTest(){
        User u = TestDataFactory.CreateUser();
        //Start test method
        test.startTest();
        system.runAs(u) {
            Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
            customSetting.Is_Influitive_Integration_Enabled__c = true;
            customSetting.Infl_Event_Fetch_DateTime__c = '2015-12-22T10:56:49Z';
            update customSetting;
            
            //issueing rewards
            List < Account > accounts = TestDataFactory.createAccounts();
            insert accounts;
            
            TestDataFactory.setUpAccountRBI(accounts);
            List < Contact > contacts = TestDataFactory.createContacts(accounts);
            insert contacts;
            //if contact is exist with below email id
            contacts.get(0).email = 'metacube.narendra@gmail.com';
            update contacts;
            System.debug('contacts:::::'+contacts);
            Reference_Basic_Information__c newrbi = new Reference_Basic_Information__c(Contact__c = contacts[0].Id, Account__c = contacts[0].AccountId, Is_Referenceable__c = true, Referenceability_Status__c = ConstantsController.ACTIVE);
            insert newrbi;
            System.debug(newrbi+'11newrbi rewards'+newrbi.Current_Available_Balance_Points__c);
            Integer points = 1000;
            Date createdAt = Date.today();
            String defaultRefType = createReferenceabilityType();
            List<Reward__c> issueRewards = new List<Reward__c>();
            Reward__c issueReward = new Reward__c(Account__c = contacts[0].AccountId,Contact__c = contacts[0].id,
                                                             Transaction__c ='Issue',Amount__c = points, 
                                                             Available_Points__c = points,Referenceability_Type__c = defaultRefType,Influitive_ID2__c = '' ,RewardDate__c = createdAt); 
            Reward__c issueReward2 = new Reward__c(Account__c = contacts[0].AccountId,Contact__c = contacts[0].id,
                                                             Transaction__c ='Issue',Amount__c = points, 
                                                             Available_Points__c = 0,Expired_Points__c= points,Referenceability_Type__c = defaultRefType,Influitive_ID2__c = '' ,RewardDate__c = createdAt,Expired__c = true); 
            Reward__c issueReward3 = new Reward__c(Account__c = contacts[0].AccountId,Contact__c = contacts[0].id,
                                                             Transaction__c ='Issue',Amount__c = points, 
                                                             Available_Points__c =0,Expired_Points__c= points,Referenceability_Type__c = defaultRefType,Influitive_ID2__c = '' ,RewardDate__c = createdAt,Expired__c = true); 
            issueRewards.add(issueReward);
            issueRewards.add(issueReward2);
            issueRewards.add(issueReward3);
            insert issueRewards;
            System.debug('issued  rewards'+issueRewards);
            points = 50;
            newrbi = [select Current_Available_Balance_Points__c,Lifetime_Points__c from Reference_Basic_Information__c where Id =: newrbi.id limit 1];
            System.debug('newrbi rewards'+newrbi.Lifetime_Points__c);
            List<Reward__c> rewards = new List<Reward__c>();
            rewards.add(new Reward__c(Account__c = contacts[0].AccountId, Contact__c = contacts[0].id,transaction__c = 'Redeem',Amount__c = points,Available_Points__c = points,Influitive_ID2__c = '',RewardDate__c= createdAt));
            insert rewards;
            
            //Execute Batch
            DataBase.executeBatch(new INfl_Batch_Events());
            System.assert(true);
        }
         //Stop test method
        test.stopTest();
    }

    private static String createReferenceabilityType(){
        Referenceability_Type__c refTye = new Referenceability_Type__c(Name = 'refedge_form',Referenceability_code__c = 'refedge_form',Referenceability_Type__c = true, Visible__c = true, Project_type__c = true, Request_type__c = true,min_lead_time_per_request_type__c = 10,max_accounts_per_request_type__c = 15,Reward_points__c = 100,Note__c = 'test notes');
        insert refTye;
        return refTye.Id;
    } 
}