POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Project_Account_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Contact_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Notes_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notes Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Opportunity_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opportunity Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Subject_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subject Required</label>
        <type>Checkbox</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Nomination__c.object
<CustomObject>
    <description>Custom Object to Store Nominations.(Bound 4)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Nominations</relationshipLabel>
        <relationshipName>Nominations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>notEqual</operation>
                <value>null</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Nominations</relationshipLabel>
        <relationshipName>Nominations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nomination</label>
    <nameField>
        <displayFormat>NM-{00000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nominations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Referenceable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</description>
        <inlineHelpText>The Reference Program Member checkbox indicates whether or not a Contact and/or Account is a customer reference, which is one factor that determines if a record may be included in Reference Search results. Reference Status must be Active or Caution.</inlineHelpText>
        <label>Reference Program Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Program_Candidate__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This Account or Contact is being considered for membership in the Customer Reference Program.</inlineHelpText>
        <label>Reference Program Candidate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referenceability_Status__c</fullName>
        <inlineHelpText>The Reference Status for an Account or Contact, in combination with Reference Program Membership, determines if a record may be included in Reference Search results. Only records with Active or Caution status may be included.</inlineHelpText>
        <label>Reference Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account__c.object
<CustomObject>
    <description>Junction table associating Reference Requests with accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Reference request account</description>
        <inlineHelpText>Reference request account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference_Type_Needed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Type Needed</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Referenceability_Type__c.Project_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Referenceability_Type__c.Request_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Account Requests</relationshipLabel>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Notes__c</fullName>
        <inlineHelpText>Provide details that will help the recipient process your request.</inlineHelpText>
        <label>Request Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Request</label>
    <nameField>
        <displayFormat>RRA-{000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Unspecified_Request__c.object
<CustomObject>
    <description>Unspecified Request associating with Reference Requests without accounts(Bound 3)</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference_Type_Needed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Type Needed</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Referenceability_Type__c.Project_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Referenceability_Type__c.Request_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Unspecified Requests</relationshipLabel>
        <relationshipName>Unspecified_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Notes__c</fullName>
        <label>Request Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Unspecified Request</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unspecified Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestNewProjectController.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */
/**
 * Class: NewProjectController
 * Description: class to test AND cover NewProjectController 
 * Modified by: Rekha Jangir @3 July 2017
 */
@isTest(seeAllData = false)
private class TestNewProjectController {
    public static User u;
    public static Profile p;
    public static List<Referenceability_Type__c> rfTypes = setUpRFTypes();
    
    /*
     * Method to cover Constructor AND add Account Request and contact request creation method
     * Modified By: Rekha Jangir @3 July 2017
     */
    static testMethod void testCreateAccountRequestMember() {
        createUser();
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        Account account = new Account(Name = 'Metacube');
        insert account;
        Nomination__c nomi = new Nomination__c(Account__c = account.Id);
        insert nomi;
        Contact contact = new Contact(FirstName = 'con1', LastName = 'test', AccountID = account.Id);
        insert contact;
        List<Reference_Basic_Information__c> RBIAccList = new list<Reference_Basic_Information__c>();
        RBIAccList.add(new Reference_Basic_Information__c(Referenceability_Status__c = 'Active', Is_Referenceable__c = true, Account__c = account.Id));
        RBIAccList.add(new Reference_Basic_Information__c(Referenceability_Status__c = 'Active', Is_Referenceable__c = true, Account__c = contact.AccountId, Contact__c =  contact.Id ));
        insert RBIAccList;
        insert rfTypes;
        //Start test method
        test.startTest();
            system.runAs(u) {
                
                NewProjectController controller = new NewProjectController();
                //Account Request
                controller.accName = 'New Metacube';
                controller.setAccountID();
                controller.accName = 'Meta';
                controller.setAccountID();
                controller.accName = 'Metacube';
                controller.setAccountID();
                controller.tempRef = nomi;
                controller.setAccountID();
                controller.refReqAccountObject.Request_Notes__c = 'test';
                controller.refReqAccountObject.Reference_Type_Needed__c = rfTypes.get(0).Id;
                controller.refReqAccountObject.Deadline__c = date.today();
                //Contact Request
                controller.refReqAccContactObject.Contact__c = contact.Id;
                controller.getReferenceStatus();
                controller.selectedContact = contact.Id;
                controller.getReferenceStatus();
                controller.saveContent();
            }
        //Stop test method
        test.stopTest();
        List<Reference_Request_Account__c> listRRA = [SELECT Id FROM Reference_Request_Account__c WHERE Account__c = :account.Id];
        system.assertEquals(1, listRRA.size());
    }
    
    /*
     * Method to cover Constructor AND add Candidate type Account Request and contact request creation method
     * Modified By: Rekha Jangir @3 July 2017
     */
    static testMethod void testCreateAccountRequestCandidate() {
        createUser();
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        Account account = new Account(Name = 'Metacube');
        insert account;
        Account account1 = new Account(Name = 'Metacube');
        insert account1;
        Nomination__c nomi = new Nomination__c(Account__c = account.Id);
        insert nomi;
        Contact contact = new Contact(FirstName = 'con1', LastName = 'test', AccountID = account.Id);
        insert contact;
        List<Reference_Basic_Information__c> RBIAccList = new list<Reference_Basic_Information__c>();
        RBIAccList.add(new Reference_Basic_Information__c(Reference_Program_Candidate__c = true, Account__c = account.Id));
        RBIAccList.add(new Reference_Basic_Information__c(Reference_Program_Candidate__c = true, Account__c = account1.Id));
        RBIAccList.add(new Reference_Basic_Information__c(Referenceability_Status__c = 'Active', Is_Referenceable__c = true, Account__c = contact.AccountId, Contact__c =  contact.Id ));
        insert RBIAccList;
        insert rfTypes;
        //Start test method
        test.startTest();
            system.runAs(u) {
                NewProjectController controller = new NewProjectController();
                controller.projectType = 'Candidate';
                controller.accName = 'Metacube';
                controller.setAccountID();
                controller.accName = 'Meta';
                controller.setAccountID();
                delete account1;
                controller.accName = 'Meta';
                controller.setAccountID();
                controller.accName = 'Metacube';
                controller.setAccountID();
                controller.refReqAccountObject.Request_Notes__c = 'test';
                controller.refReqAccountObject.Reference_Type_Needed__c = rfTypes.get(0).Id;
                controller.refReqAccountObject.Deadline__c = date.today();
                //Contact Request
                controller.refReqAccContactObject.Contact__c = contact.Id;
                controller.getReferenceStatus();
                controller.selectedContact = contact.Id;
                controller.getReferenceStatus();
                controller.saveContent();
                controller.refReqAccContactObject.Contact__c = null;
                controller.saveContent();
            }
        //Stop test method
        test.stopTest();
        List<Reference_Request_Account__c> listRRA = [SELECT Id FROM Reference_Request_Account__c WHERE Account__c = :account.Id];
        system.assertEquals(1, listRRA.size());
    }
    
	/*
     * Method to cover Constructor AND add unspecified request creation method
     * Modified By: Rekha Jangir @3 July 2017
     */
    static testMethod void testCreateUnspecifiedRequestCandidate() {
        createUser();
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        
        insert rfTypes;
        //Start test method
        test.startTest();
            system.runAs(u) {
                NewProjectController controller = new NewProjectController();
                controller.projectType = 'Candidate';
                controller.refReqAccountObject.Request_Notes__c = 'test';
                controller.refReqAccountObject.Reference_Type_Needed__c = rfTypes.get(0).Id;
                controller.refReqAccountObject.Deadline__c = date.today();
                controller.saveContent();
                controller.setBlankAccountContact();
                controller.cancel();
            }
        //Stop test method
        test.stopTest();
        List<Unspecified_Request__c> listUR = [SELECT Id FROM Unspecified_Request__c WHERE Reference_Type_Needed__c = :rfTypes.get(0).Id];
        system.assertEquals(1, listUR.size());
    }
    
    /*
     * Method to cover exceptions
     * Modified By: Rekha Jangir @3 July 2017
     */
    static testMethod void testExceptions() {
        createUser();
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        customSetting.Project_Account_Required__c = true;
        customSetting.Project_Contact_Required__c = true;
        customSetting.Project_Opportunity_Required__c = true;
        customSetting.Project_Notes_Required__c = true;
        customSetting.Project_Subject_Required__c = true;
        update customSetting;
        insert rfTypes;
        //Start test method
        test.startTest();
            system.runAs(u) {
                NewProjectController controller = new NewProjectController();
                controller.saveContent();
            }
        //Stop test method
        test.stopTest();
        List<Unspecified_Request__c> listUR = [SELECT Id FROM Unspecified_Request__c WHERE Reference_Type_Needed__c = :rfTypes.get(0).Id];
        system.assertEquals(0, listUR.size());
    }
    //Creation of User record
    private static void CreateUser() {
        p = [SELECT id FROM profile WHERE name LIKE '%System Admin%'];
        u = new User(alias = 'jpusr', email = 'japnalocal@newtest.com',
            emailencodingkey = 'UTF-8', lastname = 'Testing', languagelocalekey = 'en_US',
            localesidkey = 'en_US', profileid = p.Id,
            timezonesidkey = 'America/Los_Angeles', username = 'japnalocal@newtest.com');
    }
    
    //Creation of Referenceability_Type records
    private static List<Referenceability_Type__c> setUpRFTypes() {
        List<Referenceability_Type__c> rftypesLst = new List<Referenceability_Type__c>();
        rftypesLst.add(new Referenceability_Type__c(Name = 'RFType1'));
        rftypesLst.add(new Referenceability_Type__c(Name = 'RFType2'));
        rftypesLst.add(new Referenceability_Type__c(Name = 'RFType3'));
        return rftypesLst;
    }
}