POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request__c.object
<CustomObject>
    <description>This object holds the information necessary for a reference request</description>
    <fields>
        <fullName>Reference_Use__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows for segmenting Reference Use records from other RR records in reporting/dashboard; checked when a Reference Use is recorded from the Reference Use form.</description>
        <label>Reference Use</label>
        <type>Checkbox</type>
    </fields>
    <label>Reference Request</label>
    <nameField>
        <displayFormat>RR-{000000000}</displayFormat>
        <label>Reference Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account__c.object
<CustomObject>
    <description>Junction table associating Reference Requests with accounts</description>
    <fields>
        <fullName>Account_Request_Status__c</fullName>
        <label>Managed Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Legal Won&apos;t Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Left Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unavailable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <description>Activity Date on Reference Use form; date the Activity occurred.</description>
        <label>Activity date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Managed_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Managed Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <description>Reference request association</description>
        <inlineHelpText>Reference request association</inlineHelpText>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_Use__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows for segmenting Reference Use records from other RRAC records in reporting/dashboard; checked when a Reference Use is recorded from the Reference Use form.</description>
        <label>Reference Use</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Request</label>
    <nameField>
        <displayFormat>RRA-{000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account_Contact__c.object
<CustomObject>
    <description>This object holds all the reference request for contacts</description>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <description>Activity Date on Reference Use form; date the Activity occurred.</description>
        <label>Activity date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact_Request_Status__c</fullName>
        <label>Contact Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Legal Won&apos;t Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Left Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Request_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Requests</label>
        <referenceTo>Reference_Request_Account__c</referenceTo>
        <relationshipLabel>Contact Requests</relationshipLabel>
        <relationshipName>Reference_Request_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Use__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows for segmenting Reference Use records from other RR records in reporting/dashboard; checked when a Reference Use is recorded from the Reference Use form.</description>
        <label>Reference Use</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenceability Type</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Referenceability_Type__c.Project_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Referenceability_Type__c.Request_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Contact Requests</relationshipLabel>
        <relationshipName>Contact_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Request</label>
    <nameField>
        <displayFormat>RRAC-{000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestBatch_ResetContactRUL.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public class TestBatch_ResetContactRUL {
	//Unit test method
    static testmethod void myUnitTest01() {  
    	try{
	        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        List < Referenceability_Type__c > refTypes = TestDataFactory.createReferenceabilityType();
	        insert refTypes;
	        List < Account > accounts = TestDataFactory.createAccounts();
	        insert accounts;
	        TestDataFactory.setUpAccountRBI(accounts);
	        List < Contact > contacts = TestDataFactory.createContacts(accounts);
	        insert contacts;
	        TestDataFactory.setUpContactRBI(contacts);
	        List < Opportunity > opps = TestDataFactory.createOpportunity(accounts);
	        insert opps;
	        list<Reference_Request__c> refReqs = TestDataFactory.createReferenceRequest();
	        insert refReqs;
	        refReqs = TestDataFactory.createMoreReferenceRequest();
	        insert refReqs;
	        list < Reference_Request_Account__c > refReqAccs = TestDataFactory.createAccountRequests(accounts, refReqs, refTypes);
	        for(Reference_Request_Account__c rra : refReqAccs){
	        	rra.Activity_Date__c = system.today();
	        	rra.Reference_Use__c = true;
	        	rra.Managed_Request__c=true;
	        	rra.Account_Request_Status__c = 'Completed';
	        }
	        insert refReqAccs;
	        list<Reference_Request_Account_Contact__c> refReqAccContact = TestDataFactory.createContactRequests(contacts, refReqAccs, refTypes);
	        for(Reference_Request_Account_Contact__c rrac : refReqAccContact){
	        	rrac.Activity_Date__c = system.today();
	        	rrac.Reference_Use__c = true;
	        	rrac.Contact_Request_Status__c = 'Completed';
	        }
	        insert refReqAccContact;
	        //Start test method
	        test.startTest(); 
		        Batch_ResetContactRULWithAccountRBI batchContactRUL = new Batch_ResetContactRULWithAccountRBI();
		        ID batchprocessid = database.executebatch(batchContactRUL);
	        //Stop test method
	        test.stopTest();
	      	list<Reference_Basic_Information__c> rbiList = [select Id from Reference_Basic_Information__c where Contact__c =:contacts[0].Id];
	        system.assertEquals(rbiList.size(),1);
    	}catch(Exception e){
    		
    	}
    }
}