POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Active_Version__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This checkbox denotes that this version of the settings is the active one</description>
        <inlineHelpText>This checkbox denotes that this version of Custom Settings is currently active.</inlineHelpText>
        <label>Active Version</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chatter_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Chatter enabled app-wide?</description>
        <inlineHelpText>Used to enable/disable Chatter notifications.</inlineHelpText>
        <label>Chatter Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Referenceability_check_days__c</fullName>
        <label>Referenceability Check Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Version__c</fullName>
        <description>The version of the software&apos;s settings that this object represents</description>
        <externalId>true</externalId>
        <inlineHelpText>The version of the software&apos;s settings that this object represents</inlineHelpText>
        <label>Current Version</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Days_of_Week__c</fullName>
        <description>off Days</description>
        <label>Off Days of Week</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is email enabled app-wide?</description>
        <inlineHelpText>Used to enable/disable email notifications. Not necessary if Chatter is enabled.</inlineHelpText>
        <label>Email Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Escalation_to_Owner_Manager__c</fullName>
        <description>The number of days before a Request deadline that an escalation notification will be sent to the Account/Reference Owner&apos;s manager.</description>
        <inlineHelpText>The number of days before a Request deadline that an escalation notification will be sent to the Account/Reference Owner&apos;s manager.</inlineHelpText>
        <label>Escalation to Owner’s Manager</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Feedback_Message_Delay__c</fullName>
        <description>number of days after a reference use deadline for the automatic reference use feedback message to be sent (see R57)</description>
        <inlineHelpText>The number of days after the deadline for a reference activity (e.g., Reference Call)  when a message will be sent to the Requester asking for feedback concerning the activity.</inlineHelpText>
        <label>Request Feedback</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Include_Weekends__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If selected, days specified in “Off Days of Week” will not be included in date calculations (e.g., request lead times).</inlineHelpText>
        <label>Exclude Weekends</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Minimum_Deadline__c</fullName>
        <description>Minimum deadline for requests</description>
        <inlineHelpText>The minimum lead time required to fulfill any type of reference Account request. No managed request type may have a lower value.</inlineHelpText>
        <label>Minimum Lead Time</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Opportunity_Size__c</fullName>
        <label>Minimum Opportunity Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Sales_Stage__c</fullName>
        <description>Sales requests can only be made for Opportunities that are AT or PAST this sales stage.</description>
        <inlineHelpText>Sales requests can only be made for Opportunities that are AT or PAST this sales stage.</inlineHelpText>
        <label>Minimum Sales Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Needs Analysis</fullName>
                </value>
                <value>
                    <fullName>Value Proposition</fullName>
                </value>
                <value>
                    <fullName>Id. Decision Makers</fullName>
                </value>
                <value>
                    <fullName>Perception Analysis</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Negotiation/Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Response__c</fullName>
        <description>Days before deadline of no response</description>
        <inlineHelpText>The number of days before a Request deadline that a notification will be sent to the requester explaining that the Account/Reference Owner has been unresponsive.</inlineHelpText>
        <label>No Response</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Response_days__c</fullName>
        <description>Indicates the number of days after the &quot;Are they referenceable yet?&quot; notification is sent that the Reference Lead Status will be set to No Response. If no value is entered then the No Reponse date is left blank on the record.</description>
        <inlineHelpText>Indicates the number of days after the &quot;Are they referenceable yet?&quot; notification is sent that the Reference Lead Status will be set to No Response. If no value is entered then the No Reponse date is left blank on the record.</inlineHelpText>
        <label>No Response Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Closed_Won_Stage__c</fullName>
        <label>Opportunity Closed Won Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Needs Analysis</fullName>
                </value>
                <value>
                    <fullName>Value Proposition</fullName>
                </value>
                <value>
                    <fullName>Id. Decision Makers</fullName>
                </value>
                <value>
                    <fullName>Perception Analysis</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Negotiation/Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RUL_Activities__c</fullName>
        <description>The number of activities an account is willing to participate in over a specified amount of time</description>
        <inlineHelpText>The number of activities for which an Account is available for during the defined time period.</inlineHelpText>
        <label>Number of Activities in Period</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUL_Period__c</fullName>
        <description>The specified period of time for a set number of reference activities (e.g., 3 activities every 90 days).</description>
        <inlineHelpText>The specified period of time for a set number of reference activities (e.g., 3 activities every 90 days).</inlineHelpText>
        <label>Period Length</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reminder_to_Owner__c</fullName>
        <description>Number of days before deadline that a reminder will be sent to the owner</description>
        <inlineHelpText>The number of days before a Request deadline that a reminder will be sent to the Account/Reference Owner.</inlineHelpText>
        <label>Reminder to Owner</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestSf1_FindReferenceAccountExt.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public with sharing class TestSf1_FindReferenceAccountExt {
	//Unit Test method for Updation
    static testMethod void unitTest01() {
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        Account acc = new Account(Name = 'Acc1');
        insert acc;
        
        Opportunity opp = new Opportunity(CloseDate = system.today()+1,StageName = 'Closed Won', Amount = 700,Name = 'opp1', AccountId = acc.Id, OwnerId = UserInfo.getUserId());
        insert opp;
        
        Test.startTest();
            ApexPages.StandardController sc = new ApexPages.standardController(opp);
        	sf1_FindReferenceAccountExt sruccObj = new sf1_FindReferenceAccountExt(sc);
        	system.assert(true);
        Test.stopTest();
    }
	/*//Creation of Custom_Settings record
    private static Custom_Settings__c setUpCustomSetting1() {
        Custom_Settings__c testSettings = new Custom_Settings__c(
            Name = 'Test', Current_Version__c = '3.3.3', Include_Weekends__c = false,
            Escalation_to_Owner_Manager__c = 2, Feedback_Message_Delay__c = 2,
            Minimum_Deadline__c = 4, No_Response__c = 0, Reminder_to_Owner__c = 3,
            Email_Enabled__c = true, Chatter_Enabled__c = true, Active_Version__c = true,
            Days_of_Week__c = 'Sunday;Monday',  
              Minimum_Sales_Stage__c = 'Value Proposition',
            RUL_Activities__c = 3, RUL_Period__c = 99,Opportunity_Closed_Won_Stage__c = 'Closed Won',
            Minimum_Opportunity_Size__c = 500,Client_Referenceability_check_days__c = 1,No_Response_days__c = 2
        );
        return testSettings;
    }*/
}