POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Auto_create_delete_Reference_Content__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When content is added to Salesforce CRM Content a Reference Content record will be automatically created. When content is deleted from Salesforce CRM Content the Reference Content record will be deleted.</inlineHelpText>
        <label>Auto Create/Delete Reference Content</label>
        <type>Checkbox</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Content__c.object
<CustomObject>
    <description>This object holds all the Custom Content.</description>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Status__c</fullName>
        <label>Content Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>Chinese (Simplified)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese (Traditional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dutch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finnish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese (Brazilian)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Swedish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thai</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Search_Terms_keywords__c</fullName>
        <label>Search Terms (keywords)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reference Content</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Note__c.object
<CustomObject>
    <description>Custom Object to Store Custom Notes.</description>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reference_Content__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Reference Content</label>
        <referenceTo>Reference_Content__c</referenceTo>
        <relationshipLabel>Reference Notes</relationshipLabel>
        <relationshipName>Reference_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Note</label>
    <nameField>
        <displayFormat>RN-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/ContentDocumentTriggerHandler.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */
public with sharing class ContentDocumentTriggerHandler {
	
	/**
     * Method called on after update of Content Document
     */
    public static void onAfterUpdate(Map<Id, ContentDocument> oldMap, Map<Id, ContentDocument> newMap) {
    	Set<String> archivedDocIds = new Set<String>();
    	Set<String> unarchivedDocIds = new Set<String>();
    	List<Reference_Note__c> refNotesToInsert = new List<Reference_Note__c>();
    	List<Reference_Content__c> refContentToUpdate = new List<Reference_Content__c>();
    	
    	for (Id docId : oldMap.keySet()) {
    		
	    	if (!oldMap.get(docId).IsArchived && newMap.get(docId).IsArchived) {
		        archivedDocIds.add(oldMap.get(docId).LatestPublishedVersionId);
	    	}
	    	
	    	if (oldMap.get(docId).IsArchived && !newMap.get(docId).IsArchived) {
		        unarchivedDocIds.add(oldMap.get(docId).LatestPublishedVersionId);
	    	}
    	}
    	
    	for (Reference_Content__c refContent : [SELECT Id, Content_Status__c, Content_Id__c FROM Reference_Content__c
        										WHERE (Content_Id__c IN :archivedDocIds
        											OR Content_Id__c IN :unarchivedDocIds)
        										AND Content_Id__c != null]) {
            
            if (archivedDocIds.contains(refContent.Content_Id__c)) {
	            refContent.Content_Status__c = 'Inactive';
	            refContentToUpdate.add(refContent);
	            Reference_Note__c tempNote = new Reference_Note__c();
	            tempNote.Note__c = System.Label.Content_Archive_Note;
	            tempNote.Reference_Content__c = refContent.Id;
	            refNotesToInsert.add(tempNote);
            } else if (unarchivedDocIds.contains(refContent.Content_Id__c)) {
            	refContent.Content_Status__c = 'Active';
	            refContentToUpdate.add(refContent);
	            Reference_Note__c tempNote = new Reference_Note__c();
	            tempNote.Note__c = System.Label.Content_Restore_From_Archive_Note;
	            tempNote.Reference_Content__c = refContent.Id;
	            refNotesToInsert.add(tempNote);
            }
        }
        
        if (refContentToUpdate.size() > 0) {
        	update refContentToUpdate;
        }
        
        if (refNotesToInsert.size() > 0) {
        	insert refNotesToInsert;
        }
    }
	
    /**
     * Method called on after delete of Content Document
     */
    public static void onAfterDelete(List<ContentDocument> oldContentDocuments) {
        deleteContentDocument(oldContentDocuments);
    }
	
    /**
     * Method to delete Reference Content on delete ContentVersion
     */
    static void deleteContentDocument(List<ContentDocument> oldContentDocuments) {
        List<Reference_Content__c> refrenceContents = new List<Reference_Content__c>();
        Set<String> contentIds = new Set<String>();
        
        //Get Content Ids
        for (ContentDocument cd : oldContentDocuments) {
            contentIds.add(cd.LatestPublishedVersionId);
        }
        
        //Get Contents to be deleted
        //changes regarding ticket #156
        for (Reference_Content__c refContent : [SELECT Title__c, Language__c, Content_ID__c, Search_Terms_keywords__c, Content_Status__c
        										FROM Reference_Content__c
        										WHERE Content_Id__c IN :contentIds AND Content_Id__c != null]) {
            refContent.Content_Status__c = 'Inactive';
            refContent.Content_ID__c = '';                                
            refrenceContents.add(refContent);
        }
        
        //If Reference Contents size greater than 'ZERO'
        if (refrenceContents.size() > 0) {
            Custom_Settings__c cs = UtilityController.getCustomSettings();
        
            if (cs != null && cs.Auto_create_delete_Reference_Content__c) {
                delete refrenceContents;
            } else {
                update refrenceContents;
            }
        }
    }
}