POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Launch_Frequency__c</fullName>
        <description>Determines the frequency with which requests for Profile Updates are sent using the Automatic Launch.</description>
        <inlineHelpText>Determines the frequency with which requests for Profile Updates are sent using the Automatic Launch.</inlineHelpText>
        <label>Launch Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Manual_Automatic_Launch__c</fullName>
        <description>Manual Launch lets you decide the exact date to request the Profile Updates; with Automatic Launch Profile Updates are sent based on the Launch Frequency.</description>
        <inlineHelpText>Manual Launch lets you decide the exact date to request the Profile Updates; with Automatic Launch Profile Updates are sent based on the Launch Frequency.</inlineHelpText>
        <label>Manual/Automatic Launch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Automatic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Refresh_launch_Date__c</fullName>
        <description>Indicates when the next requests for Profiles Updates will be sent automatically.</description>
        <inlineHelpText>Indicates when the next requests for Profiles Updates will be sent automatically.</inlineHelpText>
        <label>Next Update Launch Date</label>
        <type>Date</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestReferenceRefreshSettings.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */ 
@isTest(seeAllData = false) 
public with sharing class TestReferenceRefreshSettings {
    static testMethod void testMethod1(){
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        PageReference pageRef = Page.ReferenceRefreshSettingsPage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('customSettingId',customSetting.Id);
        ApexPages.StandardController controller = new ApexPages.StandardController(customSetting);
        ReferenceRefreshSettings temp = new ReferenceRefreshSettings(controller);
        temp.editTheSettings();
        temp.customSetting.Manual_Automatic_Launch__c = 'Automatic';
        try{
            temp.customSetting.Launch_Frequency__c = null;
            temp.saveTheSettings();
        }
        catch(exception e){}
        temp.customSetting.Launch_Frequency__c = 'Quarterly';
        temp.customSetting.Next_Refresh_launch_Date__c = system.today().addDays(+30);
        temp.saveTheSettings();
        temp.customSetting.Launch_Frequency__c = 'Monthly';
        temp.saveTheSettings();
        temp.customSetting.Launch_Frequency__c = 'Semi-Annually';
        temp.saveTheSettings();
        temp.customSetting.Launch_Frequency__c = 'Annually';
        temp.saveTheSettings();
        temp.customSetting.Manual_Automatic_Launch__c = 'Manual';
        temp.customSetting.Next_Refresh_launch_Date__c = system.today().addDays(+30);
        temp.saveTheSettings();
        temp.cancel();
        PageReference pg = temp.returnCustomSettings();
        System.assertEquals(pg.getURL(),'/'+customSetting.Id);
        temp.launchReferenceRefresh();
    }
    
}