POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Caution_deadline_window__c</fullName>
        <inlineHelpText>Used to define the time frame of the Caution category for Reference Workspace projects.</inlineHelpText>
        <label>Caution Deadline Window</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Critical_Deadline_window__c</fullName>
        <inlineHelpText>Used to define the time frame of the Critical category for Reference Workspace projects.</inlineHelpText>
        <label>Critical Deadline Window</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account__c.object
<CustomObject>
    <description>Junction table associating Reference Requests with accounts</description>
    <fields>
        <fullName>Account_Request_Status__c</fullName>
        <label>Managed Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Legal Won&apos;t Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Left Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unavailable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>Reference request account</description>
        <inlineHelpText>Reference request account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_f__c</fullName>
        <description>Field have Name of Account</description>
        <formula>Account__r.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approve_Deny_Notes__c</fullName>
        <label>Approve Deny Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Influitive_Challenge_Id__c</fullName>
        <label>Influitive Challenge Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Influitive_Challenge_Status__c</fullName>
        <label>Influitive Challenge Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unpublish</fullName>
                </value>
                <value>
                    <fullName>Publish</fullName>
                </value>
                <value>
                    <fullName>UnArchive</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Managed_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Managed Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <picklist>
            <picklistValues>
                <fullName>Peer2Peer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Managed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request_Additional_Info__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Request Additional Info</label>
        <referenceTo>Reference_Request_Additional_Info__c</referenceTo>
        <relationshipLabel>Account Requests</relationshipLabel>
        <relationshipName>Account_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Type_Needed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Type Needed</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Referenceability_Type__c.Project_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Referenceability_Type__c.Request_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Account Requests</relationshipLabel>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Type_Needed_f__c</fullName>
        <formula>Reference_Type_Needed__r.Name</formula>
        <label>Reference Type Needed</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Notes__c</fullName>
        <inlineHelpText>Provide details that will help the recipient process your request.</inlineHelpText>
        <label>Request Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Request</label>
    <nameField>
        <displayFormat>RRA-{000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Additional_Info__c.object
<CustomObject>
    <description>Custom Object Additional Referenceability type Information from Reference Use Request Page (Bound 3)</description>
    <label>Reference Request Additional Info</label>
    <nameField>
        <displayFormat>RRAI-{000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Request Additional Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/AccRequestWrapper.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */
public class AccRequestWrapper {
        public String accRequestId { get; set; }
        public String accRequestName { get; set; }
        public String accountId { get; set; }
        public String accountName { get; set; }
        public String requestStatus { get; set; }
        public String deadline { get; set; }
        public String refTypeId { get; set; }
        public String refTypeName { get; set; }
        public String process { get; set; }
        public String reqNotes { get; set; }
        public String emailNotes { get; set; }
        public String ownerId { get; set; }
        public String ownerName { get; set; }
        public String refOwnerId { get; set; }
        public String addInfoId { get; set; }
        public Boolean isManaged { get; set; }
        public String conRequestId { get; set; }
        public String contactId { get; set; }
        public String contactName { get; set; }
        public String phone { get; set; }
        public String email { get; set; }
        public String deadlineColor { get; set; }
        //REF-1964
        public String challengeId { get; set; }
        public String challengeStatus { get; set; }

        public AccRequestWrapper(Reference_Request_Account__c ar, Custom_Settings__c cs) {
            this.accRequestId = ar.Id;
            this.accRequestName = ar.Name;
            this.accountId = ar.Account__c != null ? String.valueOf(ar.Account__c) : '';
            this.accountName = ar.Account_f__c != null ? String.valueOf(ar.Account_f__c) : '';
            this.requestStatus = ar.Account_Request_Status__c;
            this.deadline = ar.Deadline__c != null ? ar.Deadline__c.format() : '';
            this.refTypeId = ar.Reference_Type_Needed__c != null ? String.valueOf(ar.Reference_Type_Needed__c) : '';
            this.refTypeName = ar.Reference_Type_Needed_f__c != null ? String.valueOf(ar.Reference_Type_Needed_f__c) : '';
            this.process = ar.Process__c;
            this.reqNotes = ar.Request_Notes__c != null ? ar.Request_Notes__c : '';
            this.emailNotes = ar.Approve_Deny_Notes__c != null ? ar.Approve_Deny_Notes__c : '';
            this.refOwnerId = ar.Reference_Owner__c != null ? String.valueOf(ar.Reference_Owner__c) : '';
            this.ownerId = ar.Project_Owner__c != null ? String.valueOf(ar.Project_Owner__c) : '';
            this.ownerName = ar.Project_Owner__c != null ? ar.Project_Owner__r.Name : '';
            this.addInfoId = ar.Reference_Request_Additional_Info__c != null ? String.valueOf(ar.Reference_Request_Additional_Info__c) : '';
            this.isManaged = ar.Managed_Request__c;
            this.conRequestId = '';
            this.contactId = '';
            this.contactName = '';
            this.phone = '';
            this.email = '';
            Date criticalDate = Date.today().addDays(Integer.valueOf(cs.Critical_Deadline_window__c));
            Date cautionDate = Date.today().addDays(Integer.valueOf(cs.Caution_Deadline_window__c));

            if (ar.Deadline__c <= criticalDate) {
                this.deadlineColor = '#DD0000';
            } else if (ar.Deadline__c > criticalDate && ar.Deadline__c <= cautionDate) {
                this.deadlineColor = '#FFCC00';
            } else if (ar.Deadline__c > cautionDate) {
                this.deadlineColor = '#00CC00';
            }
            //REF-1964
       	 	this.challengeId = ar.Influitive_Challenge_Id__c != null ? String.valueOf(ar.Influitive_Challenge_Id__c) : '';
        	this.challengeStatus = ar.Influitive_Challenge_Status__c != null ? String.valueOf(ar.Influitive_Challenge_Status__c) : '';
        }
    }