POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Inherit_Attributes_from_All_Accounts__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Contacts will inherit ALL attributes from ALL associated Accounts.</inlineHelpText>
        <label>Inherit Attributes from All Accounts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Roll_up_Attributes_to_Primary_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Attributes for Shared Contacts will ONLY roll up to the Primary Account. By default, the primary account will have the oldest created date.</inlineHelpText>
        <label>Roll up Attributes to Primary Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Roll_up_Referenceability_to_Primary_Acc__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Referenceability for Shared Contacts will ONLY roll up to the Primary Account. By default, the primary account will have the oldest created date.</inlineHelpText>
        <label>Roll up Ref to Primary Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shared_Account_Field__c</fullName>
        <inlineHelpText>Select the field in the chosen related list that contains the Account name.</inlineHelpText>
        <label>Shared Account Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Contact_Field__c</fullName>
        <inlineHelpText>Select the field in the chosen related list that contains the Contact name.</inlineHelpText>
        <label>Shared Contact Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Contact_Object__c</fullName>
        <inlineHelpText>Select the “Shared Contacts” related object from the list of objects.</inlineHelpText>
        <label>Shared Contact Object</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Contacts__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If selected, Shared Contacts will be enabled.</inlineHelpText>
        <label>Shared Contacts</label>
        <type>Checkbox</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Hit_List__c.object
<CustomObject>
    <description>Hit List(Bound 4)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hit Lists</relationshipLabel>
        <relationshipName>Hit_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hit Lists</relationshipLabel>
        <relationshipName>Hit_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenceability Type</label>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Hit Lists</relationshipLabel>
        <relationshipName>Hit_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hit List</label>
    <nameField>
        <displayFormat>HL-{0000}</displayFormat>
        <label>Hit List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hit Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reward__c.object
<CustomObject>
    <description>Custom Object to Store Rewards.(Bound 4)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Type</label>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <displayFormat>RW-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestIssueRewardControllerSLDS.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */
/**
 * Class: IssueRewardControllerSLDS
 * Description: class to test AND cover IssueRewardControllerSLDS 
 * Created By: Rekha Jangir @11 May 2017
 */
@isTest(seeAllData = false)
public with sharing class TestIssueRewardControllerSLDS {
    
    /**
     * Method to cover save method with valid amount for Contact
     * Created By: Rekha Jangir @12 May 2017
     */
    static testMethod void testIssueRewardsFromContact() {
    	//insert test Data
        //insert test Data
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        Schema.SObjectType objectType = CRUDAndFLSCheckController.sObjectsMap.get(UtilityController.appNamespace() + 'Hit_List__c');
		sObject obj = objectType.newSObject();
		Schema.DescribeSObjectResult describeResult = objectType.getDescribe();
		customSetting.Shared_Contacts__c = true;
		customSetting.Shared_Contact_Object__c = describeResult.getName();
		customSetting.Shared_Account_Field__c = describeResult.fields.getMap().get(UtilityController.appNamespace() + 'Account__c').getDescribe().getName();
		customSetting.Shared_Contact_Field__c = describeResult.fields.getMap().get(UtilityController.appNamespace() + 'Contact__c').getDescribe().getName();
		customSetting.Roll_up_Attributes_to_Primary_Account__c = true;
        customSetting.Roll_up_Referenceability_to_Primary_Acc__c = true;
        customSetting.Inherit_Attributes_from_All_Accounts__c = true;
		update customSetting;
		
		
        Account accountA = new Account( Name = 'test account');
        insert accountA;
        Account accountB = new Account( Name = 'test account new');
        insert accountB;
        Contact contactA = new Contact (lastName = 'test Contact', AccountId = accountA.Id);
        insert contactA;
        Contact contactB = new Contact (lastName = 'test Contact', AccountId = accountB.Id);
        insert contactB;
        obj.put(UtilityController.appNamespace() + 'Account__c', accountA.Id);
		obj.put(UtilityController.appNamespace() + 'Contact__c', contactB.Id);
		insert obj;
        List<Referenceability_Type__c> refTypes = TestDataFactory.createReferenceabilityType();
        insert refTypes;
        
        //Start Test method
        test.startTest();
            PageReference pageRef = Page.IssueRewardSLDS;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('AccountId', accountB.Id);
            pageRef.getParameters().put('ContactId', contactB.Id);
            IssueRewardControllerSLDS irc = new IssueRewardControllerSLDS();
            //fetch all required information
            IssueRewardControllerSLDS.InfoWrapper info = IssueRewardControllerSLDS.fetchInfo(irc.accountId, irc.contactId, irc.userId);
            
            // set all data 
            info.amount = 50;
            info.comments = 'test reward';
            info.selectedRef = info.referenceabilities[1].id;
            // save reward
            String result = IssueRewardControllerSLDS.submit(JSON.serialize(info));
            
            List<Reward__c> reward = [SELECT Id, Amount__c FROM Reward__c WHERE Contact__c = :contactB.Id];
            system.assertEquals(50, reward[0].Amount__c);
            
            info = IssueRewardControllerSLDS.fetchInfo(irc.accountId, irc.contactId, irc.userId);
        //Stop Test method
        test.stopTest();
    }
    
    /**
     * Method to cover save method with valid amount for Account
     * Created By: Rekha Jangir @12 May 2017
     */
    static testMethod void testIssueRewardFromAccount() {
    	//insert test Data
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        Account accountA = new Account( Name = 'test account');
        insert accountA;
        Contact contactA = new Contact (lastName = 'test Contact', AccountId = accountA.Id);
        insert contactA;
        Contact contactB = new Contact (lastName = 'test ContactB', AccountId = accountA.Id);
        insert contactB;
        List<Referenceability_Type__c> refTypes = TestDataFactory.createReferenceabilityType();
        insert refTypes;
        //Start Test method
        test.startTest();
            PageReference pageRef = Page.IssueRewardSLDS;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('AccountId', accountA.Id);
            IssueRewardControllerSLDS irc = new IssueRewardControllerSLDS();
            //fetch all required information
            IssueRewardControllerSLDS.InfoWrapper info = IssueRewardControllerSLDS.fetchInfo(irc.accountId, irc.contactId, irc.userId);
            
            // set all data 
            info.amount = 100;
            info.comments = 'test reward';
            info.selectedRef = info.referenceabilities[1].id;
            info.selectedContact = info.contacts[2];
            // save reward
            String result = IssueRewardControllerSLDS.submit(JSON.serialize(info));
            result = IssueRewardControllerSLDS.getPermissionsMessage(irc.userId);
            
            List<Reward__c> reward = [SELECT Id, Amount__c FROM Reward__c WHERE Contact__c = :contactB.Id];
            system.assertEquals(100, reward[0].Amount__c);
            
            info = IssueRewardControllerSLDS.fetchInfo(irc.accountId, irc.contactId, irc.userId);
        //Stop Test method
        test.stopTest();
    }
    
    /**
     * Method to cover save method with valid amount for User
     * Created By: Rekha Jangir @12 May 2017
     */
    static testMethod void testIssueRewardFromUser() {
    	//insert test Data
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        User user = TestDataFactory.createUser();
        insert user;
        
        List<Referenceability_Type__c> refTypes = TestDataFactory.createUserRewardReferenceabilityType();
        insert refTypes;
        //Start Test method
        test.startTest();
            PageReference pageRef = Page.IssueRewardSLDS;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('userId', user.Id);
            pageRef.getParameters().put('retUrl', user.Id);
            IssueRewardControllerSLDS irc = new IssueRewardControllerSLDS();
            //fetch all required information
            IssueRewardControllerSLDS.InfoWrapper info = IssueRewardControllerSLDS.fetchInfo(irc.accountId, irc.contactId, irc.userId);
            
            // set all data 
            info.amount = 100;
            info.comments = 'test reward';
            info.selectedRef = info.referenceabilities[1].id;
            // save reward
            String result = IssueRewardControllerSLDS.submit(JSON.serialize(info));
            
            List<Reward__c> reward = [SELECT Id, Amount__c FROM Reward__c WHERE User__c = :user.Id];
            system.assertEquals(100, reward[0].Amount__c);
            
        //Stop Test method
        test.stopTest();
    }
    
    /**
     * Method to cover save method and error block with invalid amount
     * Created By: Rekha Jangir @12 May 2017
     */
    static testMethod void testAllException() {
    	//insert test Data
        Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List<Account> accounts = TestDataFactory.createAccounts();
        insert accounts;
        List<Contact> contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        List<Referenceability_Type__c> refTypes = TestDataFactory.createReferenceabilityType();
        insert refTypes;
        //Start Test method
        test.startTest();
            PageReference pageRef = Page.IssueRewardSLDS;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('AccountId', accounts[0].Id);
            IssueRewardControllerSLDS irc = new IssueRewardControllerSLDS();
            //fetch all required information
            IssueRewardControllerSLDS.InfoWrapper info = IssueRewardControllerSLDS.fetchInfo(irc.accountId, ':' + irc.contactId, irc.userId);
            
            // set all data 
            info.amount = 100;
            info.comments = 'test reward';
            info.selectedRef = info.referenceabilities[1].id;
            // save reward
            String result = IssueRewardControllerSLDS.submit(JSON.serialize(info) + 'test');
            
            List<Reward__c> reward = [SELECT Id, Amount__c FROM Reward__c];
            system.assertEquals(0, reward.size());
        //Stop Test method
        test.stopTest();
    }
}