POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Adv_Request_Routing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This setting enables us to determine which approach to take when routing any new requests.</description>
        <inlineHelpText>Enables Advanced Request Routing.</inlineHelpText>
        <label>Advanced Request Routing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Adv_Routing_Default__c</fullName>
        <description>The default behaviour if Advanced Routing does not find a match.</description>
        <inlineHelpText>The default behaviour if Advanced Routing does not find a match.</inlineHelpText>
        <label>Advanced Routing Default</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Send to CRP Team</fullName>
                    <default>true</default>
                    <label>Send to CRP Team</label>
                </value>
                <value>
                    <fullName>Send to Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Adv_Routing_Group_Lbl__c</fullName>
        <description>This field allows each client to specify the label that will be displayed on our VF pages for this field.</description>
        <inlineHelpText>Specify the label that will be displayed next to the Advanced Routing Group choices on the Request page.</inlineHelpText>
        <label>Advanced Routing Group Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adv_Routing_Group_Mandatory__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that a selection must be made from the Advanced Routing Group before a request can be submitted.</description>
        <inlineHelpText>Indicates that a selection must be made from the Advanced Routing Group before a request can be submitted.</inlineHelpText>
        <label>Advanced Routing Group Mandatory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Adv_Rt_Acct_Team_Contact__c</fullName>
        <label>Contact Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adv_Rt_Acct_Team_Object__c</fullName>
        <description>Indicates which related object on the Account is to be used for Team Member identification.</description>
        <inlineHelpText>Indicates which related object on the Account is to be used for Team Member identification.</inlineHelpText>
        <label>Account Team Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adv_Rt_Acct_Team_Role_Picklist__c</fullName>
        <inlineHelpText>Indicates which picklist field on the Account Team Object contains the list of values identifying the roles of the Account Team members. Blank indicates that Roles should not be considered as part of the routing criteria.</inlineHelpText>
        <label>Role Picklist</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adv_Rt_Acct_Team_Roles_to_Include__c</fullName>
        <inlineHelpText>Indicates which roles should be included in the routing decisions. Only team members with matching roles will be considered in the routing decisions.</inlineHelpText>
        <label>Roles to Include</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Adv_Rt_Acct_Team_Routeby__c</fullName>
        <description>Indicates which picklist field on the Account Team Object contains the list of values for routing the request.</description>
        <inlineHelpText>Indicates which picklist field on the Account Team Object contains the list of values for routing the request.</inlineHelpText>
        <label>Routing Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adv_Rt_Acct_Team_User__c</fullName>
        <description>Indicates which picklist field on the Account Team Object contains the Team Member that the request will be routed to.</description>
        <inlineHelpText>Indicates which picklist field on the Account Team Object contains the Team Member that the request will be routed to.</inlineHelpText>
        <label>User Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing_Groups_to_Exclude__c</fullName>
        <label>Routing Groups to Exclude</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/AdvRoutingExtensionsSLDS.cls
/**
 * ReferenceEdge
 *
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"),
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR,
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING,
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS
 * WRITTEN CONSENT FROM COMPANY.
 */
/**
 * VF Page: AdvRoutingSettingsSLDS
 * Description: Class used to handle Advance Routing fields.  
 * Created by: Rekha Jangir @25 August 2017
 */
public with sharing class AdvRoutingExtensionsSLDS extends RefEdgeEditionFeatures {
    
    /**
     * Constructor
     */
    public AdvRoutingExtensionsSLDS(ApexPages.StandardController controller) {}
    
    /**
     * Method to check Permissions
     */
    private static Boolean checkPermissions() {
    	Map<String, Set<String>> fieldMap = new Map<String, Set<String>>();
    	
    	fieldMap.put(UtilityController.appNamespace() + 'Custom_Settings__c',
    										new Set<String>{
                                                UtilityController.appNamespace() + 'Adv_Rt_Acct_Team_Roles_to_Include__c',
                                                UtilityController.appNamespace() + 'Adv_Rt_Acct_Team_Role_Picklist__c',
    											UtilityController.appNamespace() + 'Adv_Request_Routing__c',
    											UtilityController.appNamespace() + 'Adv_Routing_Default__c',
    											UtilityController.appNamespace() + 'Adv_Routing_Group_Lbl__c',
    											UtilityController.appNamespace() + 'Adv_Routing_Group_Mandatory__c',
	        									UtilityController.appNamespace() + 'Adv_Rt_Acct_Team_Object__c',
	        									UtilityController.appNamespace() + 'Adv_Rt_Acct_Team_Routeby__c',
                                                UtilityController.appNamespace() + 'Adv_Rt_Acct_Team_Contact__c',
                                                UtilityController.appNamespace() + 'Routing_Groups_to_Exclude__c',
	        									UtilityController.appNamespace() + 'Adv_Rt_Acct_Team_User__c'});
        return CRUDAndFLSCheckController.isUpsertable(fieldMap, false, true);
    }
    
    /**
     * Remote Action Method to get Objects names
     */
    @RemoteAction
    public static List<OptionWrapper> getObjects() {
        List<OptionWrapper> options = new List<OptionWrapper>();
        Schema.DescribeSObjectResult R = Account.SObjectType.getDescribe();
 
		List<Schema.ChildRelationship> C = R.getChildRelationships();
        
        for (Schema.ChildRelationship cr : C) { 
            options.add(new OptionWrapper(cr.getChildSobject().getDescribe().getName(), cr.getChildSobject().getDescribe().getLabel()));
        }
        return options;
    }
    /**
     * Remote Action Method to get fields for an object
     */
    @RemoteAction
    public static List<String> getFieldValues() {
    	List<String> options = new List<String>();
        Schema.DescribeFieldResult dfr = Schema.sObjectType.Custom_Settings__c.fields.getMap().get(UtilityController.appNamespace() 
                                                                                                               + 'Adv_Routing_Default__c').getDescribe();
        List<Schema.PicklistEntry> ple = dfr.getPicklistValues();
        
        for (Schema.PicklistEntry f : ple) {
            options.add(String.valueOf(f.value));
        }
        return options;
    }
    /**
     * Remote Action Method to get User fields for an object
     */
    @RemoteAction
    public static String getReferenceFields(String selectedObject, String selectedContactField) {
    	List<OptionWrapper> returnFields = new List<OptionWrapper>();
    	
        if (selectedContactField != null && selectedContactField != '') { 
            selectedObject = 'Contact';
        }
        if (selectedObject != null && selectedObject != '') {
            
            Schema.SObjectType objectType = CRUDAndFLSCheckController.sObjectsMap.get(selectedObject);
            Map<String, Schema.SObjectField> fieldMap = objectType.getDescribe().fields.getMap();
            
            for (String field : fieldMap.keySet()) {
                Schema.DescribeFieldResult dfr = fieldMap.get(field).getDescribe();
                
                if (string.valueOf(dfr.getType()) =='REFERENCE' && string.valueOf(dfr.getReferenceTo()) == '(User)') {
					returnFields.add(new OptionWrapper(dfr.getName(), dfr.getLabel()));
				} 
            }
        }
        return JSON.serialize(returnFields);
    }

    /**
     * Remote Action Method to get Contact fields for an object
     */
    @RemoteAction
    public static String getReferenceFieldsContacts(String selectedObject) {
    	List<OptionWrapper> returnFields = new List<OptionWrapper>();
    	
        if (selectedObject != null && selectedObject != '') {
            Schema.SObjectType objectType = CRUDAndFLSCheckController.sObjectsMap.get(selectedObject);
            Map<String, Schema.SObjectField> fieldMap = objectType.getDescribe().fields.getMap();
            
            for (String field : fieldMap.keySet()) {
                Schema.DescribeFieldResult dfr = fieldMap.get(field).getDescribe();
                
                if (string.valueOf(dfr.getType()) =='REFERENCE' && string.valueOf(dfr.getReferenceTo()) == '(Contact)') {
					returnFields.add(new OptionWrapper(dfr.getName(), dfr.getLabel()));
				} 
            }
        }
        return JSON.serialize(returnFields);
    }

    /**
     * Remote Action Method to get Role Picklist fields for an object
     */
    @RemoteAction
    public static String getPicklistFieldsRole(String selectedObject) {
    	List<OptionWrapper> returnFields = new List<OptionWrapper>();
    	
        if (selectedObject != null && selectedObject != '') {
            Schema.SObjectType objectType = CRUDAndFLSCheckController.sObjectsMap.get(selectedObject);
            Map<String, Schema.SObjectField> fieldMap = objectType.getDescribe().fields.getMap();
            
            for (String field : fieldMap.keySet()) {
                Schema.DescribeFieldResult dfr = fieldMap.get(field).getDescribe();
                
                if (string.valueOf(dfr.getType()) =='PICKLIST' || string.valueOf(dfr.getType()) =='MULTIPICKLIST') {
					returnFields.add(new OptionWrapper(dfr.getName(), dfr.getLabel()));
				} 
            }
        }
        return JSON.serialize(returnFields);
    }

    /**
     * Remote Action Method to get Role Picklist fields for an object
     */
    @RemoteAction
    public static String getRoleEntries(String selectedRole, String selectedObject, String selectedValues) {
    	List<OptionWrapper> returnFields = new List<OptionWrapper>();
    
        if (selectedObject != null && selectedObject != '' && selectedRole != null && selectedRole != '') {
            Schema.SObjectType objectType = CRUDAndFLSCheckController.sObjectsMap.get(selectedObject);
            Map<String, Schema.SObjectField> fieldMap = objectType.getDescribe().fields.getMap();
            Schema.DescribeFieldResult dfr = fieldMap.get(selectedRole).getDescribe();
            List<Schema.PicklistEntry> entries = dfr.getPicklistValues();
            Set<String> rolesSelectedSaved = new Set<String>(selectedValues.split(','));
            
            for( Schema.PicklistEntry pickListVal : entries) {
                OptionWrapper entry = new OptionWrapper(pickListVal.getValue(), pickListVal.getLabel());
                
                if (rolesSelectedSaved.contains(pickListVal.getValue())) {
                    entry.isSelected = true;
                } 
                returnFields.add(entry);
            } 
        }
        return JSON.serialize(returnFields);
    }
    
    /**
     * Remote Action Method to get fields for an object
     */
    @RemoteAction
    public static String getPicklistFields(String selectedObject, String selectedContactField) {
    	List<OptionWrapper> returnFields = new List<OptionWrapper>();
    	
        if (selectedContactField != null && selectedContactField != '') { 
            selectedObject = 'Contact';
        }
        
        if (selectedObject != null && selectedObject != '') {
            Schema.SObjectType objectType = CRUDAndFLSCheckController.sObjectsMap.get(selectedObject);
            Map<String, Schema.SObjectField> fieldMap = objectType.getDescribe().fields.getMap();
            
            for (String field : fieldMap.keySet()) {
                Schema.DescribeFieldResult dfr = fieldMap.get(field).getDescribe();
                
                if (string.valueOf(dfr.getType()) =='PICKLIST' || string.valueOf(dfr.getType()) =='MULTIPICKLIST') {
					returnFields.add(new OptionWrapper(dfr.getName(), dfr.getLabel()));
				} 
            }
        }
        return JSON.serialize(returnFields);
    }
    
    @RemoteAction
    public static String saveCSRUL(String cswJSON) { 
    	
    	try {
    		
    		if (checkPermissions()) {
	    		CustomSettingWrapper csw = (CustomSettingWrapper)JSON.deserialize(cswJSON, CustomSettingWrapper.class);
		    	Custom_Settings__c cs = UtilityController.getCustomSettings();
		    	cs.Adv_Request_Routing__c = csw.adReqRouting;
		    	cs.Adv_Routing_Default__c = csw.adRoutingDefault;
		    	cs.Adv_Routing_Group_Lbl__c = csw.adRoutingGroup;
		    	cs.Adv_Routing_Group_Mandatory__c = csw.adRoutingGroupMandatory;
		    	cs.Adv_Rt_Acct_Team_Object__c = csw.teamObject;
		    	cs.Adv_Rt_Acct_Team_Routeby__c = csw.teamRouteBy;
		    	cs.Adv_Rt_Acct_Team_User__c = csw.teamUser;
                cs.Adv_Rt_Acct_Team_Contact__c = csw.teamContact;
                cs.Adv_Rt_Acct_Team_Role_Picklist__c = csw.teamRole; 
                cs.Adv_Rt_Acct_Team_Roles_to_Include__c = csw.teamRolesToInclude;
                cs.Routing_Groups_to_Exclude__c = csw.groupsToExclude;
		    	update cs;
    		} else {
        		return CRUDAndFLSCheckController.getErrorMsg();
        	}
    	} catch(Exception e) {
    		return CRUDAndFLSCheckController.getCleanSystemErrorMsg(e.getMessage());
    	}
        return '';
    }
    
    /**
     * Method to get Custom Setting
     * Created By: Rekha Jangir @25 August 2017
     */
    @RemoteAction
    public static String getCustomSetting() { 
        CustomSettingWrapper csw = new CustomSettingWrapper();
    	Custom_Settings__c cs = UtilityController.getCustomSettings();
    	csw.adReqRouting = cs.Adv_Request_Routing__c;
    	csw.adRoutingDefault = cs.Adv_Routing_Default__c;
    	csw.adRoutingGroup = cs.Adv_Routing_Group_Lbl__c;
    	csw.adRoutingGroupMandatory = cs.Adv_Routing_Group_Mandatory__c;
    	csw.teamObject = cs.Adv_Rt_Acct_Team_Object__c;
    	csw.teamRouteBy = cs.Adv_Rt_Acct_Team_Routeby__c;
    	csw.teamUser = cs.Adv_Rt_Acct_Team_User__c;
        csw.teamContact = cs.Adv_Rt_Acct_Team_Contact__c == null ? '' : cs.Adv_Rt_Acct_Team_Contact__c;
        csw.teamRole = cs.Adv_Rt_Acct_Team_Role_Picklist__c == null ? '' : cs.Adv_Rt_Acct_Team_Role_Picklist__c;
        csw.teamRolesToInclude = cs.Adv_Rt_Acct_Team_Roles_to_Include__c == null ? '' : cs.Adv_Rt_Acct_Team_Roles_to_Include__c;
        csw.groupsToExclude = cs.Routing_Groups_to_Exclude__c == null ? '' : cs.Routing_Groups_to_Exclude__c;
        return JSON.serialize(csw);
    }
    
    /**
     * Wrapper class for Custom Setting
     * Created By: Rekha Jangir @25 August 2017
     */
    public class CustomSettingWrapper {
    	public Boolean adReqRouting { get; set; }
    	public String adRoutingDefault { get; set; }
    	public String adRoutingGroup { get; set; }
    	public Boolean adRoutingGroupMandatory { get; set; }
        public String teamObject { get; set; }
        public String teamRouteBy { get; set; }
        public String teamUser { get; set; }
        public String teamContact { get; set; }
        public String teamRole { get; set; }
        public String teamRolesToInclude { get; set; }
        public String groupsToExclude { get; set; }
    }
    
    /**
     * Wrapper class
     */
 	public class OptionWrapper {
 		public String name { get; set; }
 		public String id { get; set; }
        public Boolean isSelected { get; set; }
 		
 	    public OptionWrapper(String id, String name) {
            this.name = name;
            this.id = id;
            this.isSelected = false;
	    }
 	}
}