POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>Enable_Sales_Rewards_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>User Points - as defined in Reward Settings - will be assigned to users on completion of actions.</description>
        <inlineHelpText>User Points- as defined in Reward Settings - will be assigned to users on completion of actions.</inlineHelpText>
        <label>Enable User Points</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inherit_Attributes_from_All_Accounts__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Contacts will inherit ALL attributes from ALL associated Accounts.</inlineHelpText>
        <label>Inherit Attributes from All Accounts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Roll_up_Attributes_to_Primary_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Attributes for Shared Contacts will ONLY roll up to the Primary Account. By default, the primary account will have the oldest created date.</inlineHelpText>
        <label>Roll up Attributes to Primary Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Roll_up_Referenceability_to_Primary_Acc__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Referenceability for Shared Contacts will ONLY roll up to the Primary Account. By default, the primary account will have the oldest created date.</inlineHelpText>
        <label>Roll up Ref to Primary Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shared_Account_Field__c</fullName>
        <inlineHelpText>Select the field in the chosen related list that contains the Account name.</inlineHelpText>
        <label>Shared Account Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Contact_Field__c</fullName>
        <inlineHelpText>Select the field in the chosen related list that contains the Contact name.</inlineHelpText>
        <label>Shared Contact Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Contact_Object__c</fullName>
        <inlineHelpText>Select the “Shared Contacts” related object from the list of objects.</inlineHelpText>
        <label>Shared Contact Object</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shared_Contacts__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If selected, Shared Contacts will be enabled.</inlineHelpText>
        <label>Shared Contacts</label>
        <type>Checkbox</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Hit_List__c.object
<CustomObject>
    <description>Hit List(Bound 4)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hit Lists</relationshipLabel>
        <relationshipName>Hit_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hit Lists</relationshipLabel>
        <relationshipName>Hit_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenceability Type</label>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Hit Lists</relationshipLabel>
        <relationshipName>Hit_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hit List</label>
    <nameField>
        <displayFormat>HL-{0000}</displayFormat>
        <label>Hit List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hit Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referenceability_code__c</fullName>
        <description>This is use to give event api code.</description>
        <inlineHelpText>This is use to give event api code.</inlineHelpText>
        <label>Referenceability_code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Point__c</fullName>
        <label>User Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Reward__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User Reward</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Controls the overall visibility of this Referenceability Type throughout ReferenceEdge – Referenceability, Requests, Projects, Nominations, Reference Use.</inlineHelpText>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestRecordAReferenceUseExtensionSLDS.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */

/**
 * Class: RecordAReferenceUseExtensionSLDS
 * Description : class to test and cover RecordAReferenceUseExtensionSLDS
 * Created by: Rekha Jangir @5 September 2017
 */
@isTest(seeAllData = false)
public with sharing class TestRecordAReferenceUseExtensionSLDS {
    
	/*
     * Method to cover all method and constructor for account
     * Created By: Rekha Jangir @5 September 2017
     */
    static testmethod void testRecordReferenceOnAccount() {
    	//create test data
    	Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
    	customSetting.Enable_Sales_Rewards_Notification__c = true;
        update customSetting;
        List<Referenceability_Type__c> refTypes = TestDataFactory.createReferenceabilityType();
        refTypes.add(new Referenceability_Type__c(Name = 'REFERANCE USE', Referenceability_Type__c = true, Visible__c = true, 
        						Sales_Point__c = 50, Referenceability_code__c = ConstantsController.REFERANCE_USE, Sales_Reward__c = true));
        insert refTypes;
        List<Account> accounts = TestDataFactory.createAccounts();
        insert accounts;
        TestDataFactory.setUpAccountRBI(accounts);
        List<Contact> contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        TestDataFactory.setUpContactRBI(contacts);
        
    	//Start test method
        test.startTest();
            Apexpages.currentPage().getParameters().put('Id', accounts[0].Id);
            RecordAReferenceUseExtensionSLDS obj = new RecordAReferenceUseExtensionSLDS();
            RecordAReferenceUseExtensionSLDS.InfoWrapper info = RecordAReferenceUseExtensionSLDS.fetchInfo('');
            info = RecordAReferenceUseExtensionSLDS.fetchInfo(obj.recordId);
            info.selectedRefType = info.refTypes[0].id;
            info.activityDate = date.today();
            info.notes = 'test account request';
            String result = RecordAReferenceUseExtensionSLDS.submit(JSON.serialize(info));
            system.assertEquals('success:50:REFERANCE USE', result);
            system.assertNotEquals(RecordAReferenceUseExtensionSLDS.getDateFormat(), '');
    	//Stop test method
        test.stopTest();
    }
    
    /*
     * Method to cover all method and constructor for contact
     * Created By: Rekha Jangir @5 September 2017
     */
    static testmethod void testRecordReferenceOnContact() {
    	//create test data
    	Schema.SObjectType objectType = CRUDAndFLSCheckController.sObjectsMap.get(UtilityController.appNamespace() + 'Hit_List__c');
		Schema.DescribeSObjectResult describeResult = objectType.getDescribe();
    	Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
    	customSetting.Shared_Contacts__c = true;
        customSetting.Shared_Contact_Object__c = describeResult.getName();
		customSetting.Shared_Account_Field__c = describeResult.fields.getMap().get(UtilityController.appNamespace() + 'Account__c').getDescribe().getName();
		customSetting.Shared_Contact_Field__c = describeResult.fields.getMap().get(UtilityController.appNamespace() + 'Contact__c').getDescribe().getName();
		customSetting.Roll_up_Attributes_to_Primary_Account__c = true;
        customSetting.Roll_up_Referenceability_to_Primary_Acc__c = true;
        customSetting.Inherit_Attributes_from_All_Accounts__c = true;
		update customSetting;
        List<Referenceability_Type__c> refTypes = TestDataFactory.createReferenceabilityType();
        insert refTypes;
        Account account = new Account( Name = 'test account');
        insert account;
        Contact contact = new Contact (lastName = 'test Contact', AccountId = account.Id);
        insert contact;
        Account acc = new Account(Name = 'new shared');
        insert acc;
        Hit_List__c sharedc = new Hit_List__c(Account__c = acc.Id, Contact__c = contact.Id);
        insert sharedc;
        
    	//Start test method
        test.startTest();
            Apexpages.currentPage().getParameters().put('Id', contact.Id);
            RecordAReferenceUseExtensionSLDS obj = new RecordAReferenceUseExtensionSLDS();
            RecordAReferenceUseExtensionSLDS.InfoWrapper info = RecordAReferenceUseExtensionSLDS.fetchInfo(obj.recordId);
            info.selectedRefType = info.refTypes[0].id;
            info.activityDate = date.today();
            info.notes = 'test contac request';
            info.useFeedback = info.feedbackOptions[0].id;
            info.feedbackReason = 'good';
            String result = RecordAReferenceUseExtensionSLDS.submit(JSON.serialize(info));
            system.assertEquals('', result);
    	//Stop test method
        test.stopTest();
    }
    
    
    /*
     * Method to cover all method and constructor for opportunity
     * Created By: Rekha Jangir @5 September 2017
     */
    static testmethod void testRecordReferenceOnOpportunity() {
    	//create test data
    	Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
        List<Referenceability_Type__c> refTypes = TestDataFactory.createReferenceabilityType();
        insert refTypes;
        List<Account> accounts = TestDataFactory.createAccounts();
        insert accounts;
        Opportunity opp = new Opportunity(Name = accounts[0].Name + ' Opportunity', AccountId = accounts[0].Id, 
        												CloseDate = system.today(), StageName = 'Closed Won');
        insert opp;
        TestDataFactory.setUpAccountRBI(accounts);
        List<Contact> contacts = TestDataFactory.createContacts(accounts);
        insert contacts;
        TestDataFactory.setUpContactRBI(contacts);
        
    	//Start test method
        test.startTest();
            Apexpages.currentPage().getParameters().put('Id', opp.Id);
            RecordAReferenceUseExtensionSLDS obj = new RecordAReferenceUseExtensionSLDS();
            RecordAReferenceUseExtensionSLDS.InfoWrapper info = RecordAReferenceUseExtensionSLDS.fetchInfo(obj.recordId);
            info.selectedRefType = info.refTypes[0].id;
            info.activityDate = date.today() + 3;
            info.notes = 'test opp request';
            String result = RecordAReferenceUseExtensionSLDS.submit(JSON.serialize(info));
            system.assertNotEquals('', result);
            info.activityDate = date.today();
            result = RecordAReferenceUseExtensionSLDS.submit(JSON.serialize(info));
            system.assertEquals('', result);
            
            String permission = RecordAReferenceUseExtensionSLDS.getPermissionsMessage(true);
    	//Stop test method
        test.stopTest();
    }
}