POR/RefEdge/src/objects/Custom_Settings__c.object
<CustomObject>
    <description>This object holds the custom settings for the app</description>
    <fields>
        <fullName>RUL_Activities_Contact__c</fullName>
        <description>The number of activities an contact is willing to participate in over a specified amount of time</description>
        <inlineHelpText>The number of activities for which an Contact is available for during the defined time period.</inlineHelpText>
        <label>Number of Activities in Period</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUL_Activities__c</fullName>
        <description>The number of activities an account is willing to participate in over a specified amount of time</description>
        <inlineHelpText>The number of activities for which an Account is available for during the defined time period.</inlineHelpText>
        <label>Number of Activities in Period</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUL_Period_Contact__c</fullName>
        <description>The specified period of time for a set number of reference activities (e.g., 3 activities every 90 days).</description>
        <inlineHelpText>The specified period of time for a set number of reference activities (e.g., 3 activities every 90 days).</inlineHelpText>
        <label>Period Length</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUL_Period__c</fullName>
        <description>The specified period of time for a set number of reference activities (e.g., 3 activities every 90 days).</description>
        <inlineHelpText>The specified period of time for a set number of reference activities (e.g., 3 activities every 90 days).</inlineHelpText>
        <label>Period Length</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RefEdge Custom Settings</label>
    <nameField>
        <label>Custom Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RefEdge Custom Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RUL_Period__c</fullName>
        <inlineHelpText>The Time Period is the range of time during which a reference use limit has been set (e.g., 3 uses in 90 days where 90 days is the Time Period).</inlineHelpText>
        <label>Time Period</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request__c.object
<CustomObject>
    <description>This object holds the information necessary for a reference request</description>
    <label>Reference Request</label>
    <nameField>
        <displayFormat>RR-{000000000}</displayFormat>
        <label>Reference Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account__c.object
<CustomObject>
    <description>Junction table associating Reference Requests with accounts</description>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <description>Reference request association</description>
        <inlineHelpText>Reference request association</inlineHelpText>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Account Request</label>
    <nameField>
        <displayFormat>RRA-{000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account_Contact__c.object
<CustomObject>
    <description>This object holds all the reference request for contacts</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Reference_Request_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Requests</label>
        <referenceTo>Reference_Request_Account__c</referenceTo>
        <relationshipLabel>Contact Requests</relationshipLabel>
        <relationshipName>Reference_Request_Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenceability Type</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Referenceability_Type__c.Project_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Referenceability_Type__c.Request_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Contact Requests</relationshipLabel>
        <relationshipName>Contact_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Request</label>
    <nameField>
        <displayFormat>RRAC-{000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestBatch_AccConUpdateOnCustomSetting.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */ 
@isTest(seeAllData = false)
public with sharing class TestBatch_AccConUpdateOnCustomSetting {
    //Unit Test Method
  	static testmethod void myUnitTest01() {
  		try{
		    Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        List < Account > accounts = TestDataFactory.createAccounts();
	        insert accounts;
	        TestDataFactory.setUpAccountRBI(accounts);
	        List < Contact > contacts = TestDataFactory.createContacts(accounts);
	        insert contacts;
	        TestDataFactory.setUpContactRBI(contacts);
	        List < Referenceability_Type__c > refTypes = TestDataFactory.createReferenceabilityType();
	        insert refTypes;
	        list<Reference_Request__c> refReqs = TestDataFactory.createReferenceRequest();
	        insert refReqs;
	        list < Reference_Request_Account__c > refReqAccs = TestDataFactory.createAccountRequests(accounts, refReqs, refTypes);
	        insert refReqAccs;
	        List < Reference_Request_Account_Contact__c > refReqCons = TestDataFactory.createContactRequests(contacts, refReqAccs, refTypes);
	        insert refReqCons;
	        //Start test method
	        test.startTest();
		        Batch_AccConUpdateOnCustomSetting batchConAcc = new Batch_AccConUpdateOnCustomSetting(customSetting.RUL_Period__c,10, customSetting.RUL_Period_Contact__c,10, true, true,customSetting.RUL_Activities__c,customSetting.RUL_Activities_Contact__c);
		        ID batchprocessid = database.executebatch(batchConAcc);
	        //Stop test method
	        test.stopTest();
	        list<Reference_Basic_Information__c> rbiList = [select Id from Reference_Basic_Information__c where Contact__c =:contacts[0].Id];
	    	system.assertEquals(rbiList.size(),1);
  		}catch(Exception e){
  			
  		}		
  	}
  	//Unit Test Method
  	static testmethod void myUnitTest02() {
  		try{
		    Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        List < Account > accounts = TestDataFactory.createAccounts();
	        insert accounts;
	        TestDataFactory.setUpAccountRBI(accounts);
	        List < Contact > contacts = TestDataFactory.createContacts(accounts);
	        insert contacts;
	        TestDataFactory.setUpContactRBI(contacts);
	        List < Referenceability_Type__c > refTypes = TestDataFactory.createReferenceabilityType();
	        insert refTypes;
	        list<Reference_Request__c> refReqs = TestDataFactory.createReferenceRequest();
	        insert refReqs;
	        list < Reference_Request_Account__c > refReqAccs = TestDataFactory.createAccountRequests(new List < Account > {accounts[0]}, refReqs, refTypes);
	        insert refReqAccs;
	        List < Reference_Request_Account_Contact__c > refReqCons = TestDataFactory.createContactRequests(contacts, refReqAccs, refTypes);
	        insert refReqCons;
	        //Start test method
	        test.startTest();
		        Batch_AccConUpdateOnCustomSetting batchConAcc = new Batch_AccConUpdateOnCustomSetting(customSetting.RUL_Period__c,20, customSetting.RUL_Period_Contact__c,10, true, false,customSetting.RUL_Activities__c,customSetting.RUL_Activities_Contact__c);
		        ID batchprocessid = database.executebatch(batchConAcc);
	        //Stop test method
	        test.stopTest();
	        list<Reference_Basic_Information__c> rbiList = [select Id from Reference_Basic_Information__c where Contact__c =:contacts[0].Id];
	    	system.assertEquals(rbiList.size(),1);
  		}catch(Exception e){
  			
  		}
  	}
  	//Unit Test Method
  	static testmethod void myUnitTest03() { 
  		try{
		    Custom_Settings__c customSetting = TestDataFactory.createCustomSetting();
	        List < Account > accounts = TestDataFactory.createAccounts();
	        insert accounts;
	        TestDataFactory.setUpAccountRBI(accounts);
	        List < Contact > contacts = TestDataFactory.createContacts(accounts);
	        insert contacts;
	        TestDataFactory.setUpContactRBI(contacts);
	        List < Referenceability_Type__c > refTypes = TestDataFactory.createReferenceabilityType();
	        insert refTypes;
	        list<Reference_Request__c> refReqs = TestDataFactory.createReferenceRequest();
	        insert refReqs;
	        list < Reference_Request_Account__c > refReqAccs = TestDataFactory.createAccountRequests(new List < Account > {accounts[0]}, refReqs, refTypes);
	        insert refReqAccs;
	        List < Reference_Request_Account_Contact__c > refReqCons = TestDataFactory.createContactRequests(contacts,new list < Reference_Request_Account__c > { refReqAccs[0]}, refTypes);
	        insert refReqCons;
	        //Start test method
	        test.startTest();
		        Batch_AccConUpdateOnCustomSetting batchConAcc = new Batch_AccConUpdateOnCustomSetting(customSetting.RUL_Period__c,10, customSetting.RUL_Period_Contact__c,30, false, true,customSetting.RUL_Activities__c,customSetting.RUL_Activities_Contact__c);
		        ID batchprocessid = database.executebatch(batchConAcc);
	        //Stop test method
	        test.stopTest();
	        list<Reference_Basic_Information__c> rbiList = [select Id from Reference_Basic_Information__c where Contact__c =:contacts[0].Id];
	    	system.assertEquals(rbiList.size(),1);
  		}catch(Exception e){
  			
  		}
  		
  	}
}