POR/RefEdge/src/objects/Hit_List__c.object
<CustomObject>
    <description>Hit List(Bound 4)</description>
    <fields>
        <fullName>Account_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Request</label>
        <referenceTo>Reference_Request_Account__c</referenceTo>
        <relationshipLabel>Hit Lists</relationshipLabel>
        <relationshipName>Hit_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hit Lists</relationshipLabel>
        <relationshipName>Hit_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Hit Lists</relationshipLabel>
        <relationshipName>Hit_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipLabel>Hit Lists</relationshipLabel>
        <relationshipName>Hit_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unspecified_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unspecified Request</label>
        <referenceTo>Unspecified_Request__c</referenceTo>
        <relationshipLabel>Hit Lists</relationshipLabel>
        <relationshipName>Hit_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hit List</label>
    <nameField>
        <displayFormat>HL-{0000}</displayFormat>
        <label>Hit List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hit Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request__c.object
<CustomObject>
    <description>This object holds the information necessary for a reference request</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity association</description>
        <inlineHelpText>Associated opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Reference Requests</relationshipLabel>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request_Status__c</fullName>
        <label>Reference Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Legal Won&apos;t Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Left Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Request</label>
    <nameField>
        <displayFormat>RR-{000000000}</displayFormat>
        <label>Reference Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account__c.object
<CustomObject>
    <description>Junction table associating Reference Requests with accounts</description>
    <fields>
        <fullName>Account_Request_Status__c</fullName>
        <label>Managed Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Legal Won&apos;t Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Left Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unavailable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <description>Reference request association</description>
        <inlineHelpText>Reference request association</inlineHelpText>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Request</label>
    <nameField>
        <displayFormat>RRA-{000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Requests_and_Invitations__c.object
<CustomObject>
    <description>RefEdge Object that combines the peer data of Invitations and Reference Requests (both of which are related children of Opportunity) for comprehensive Revenue Influenced reporting.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Reference Requests and Invitations</relationshipLabel>
        <relationshipName>Reference_Requests_and_Invitations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipLabel>Reference Requests and Invitations</relationshipLabel>
        <relationshipName>Reference_Requests_and_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Requests and Invitations</label>
    <nameField>
        <displayFormat>RRI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests and Invitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reward__c.object
<CustomObject>
    <description>Custom Object to Store Rewards.(Bound 4)</description>
    <fields>
        <fullName>Account_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Request</label>
        <referenceTo>Reference_Request_Account__c</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <displayFormat>RW-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Unspecified_Request__c.object
<CustomObject>
    <description>Unspecified Request associating with Reference Requests without accounts(Bound 3)</description>
    <fields>
        <fullName>Project_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PO_Unspecified_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipLabel>Unspecified Requests</relationshipLabel>
        <relationshipName>Unspecified_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Unspecified_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specified_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Specified Account</label>
        <referenceTo>Reference_Request_Account__c</referenceTo>
        <relationshipLabel>Unspecified Requests</relationshipLabel>
        <relationshipName>Unspecified_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unspecified_Request_Status__c</fullName>
        <label>Unspecified Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Reference Match</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Unspecified Request</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unspecified Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/ReferenceRequestTriggerHandler.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */
public with sharing class ReferenceRequestTriggerHandler {
    /**
     * Properties and variables
     */
    public static list < Reference_Request__c > newReferenceRequests;
    public static list < Reference_Request__c > oldReferenceRequests;
    public static map < Id, Reference_Request__c > newReferenceRequestMap;
    public static map < Id, Reference_Request__c > oldReferenceRequestMap;
    /**
     * Method called on before insert of Reference Request
     */
    public static void onBeforeInsert() {
        
        for (Reference_Request__c refReq : newReferenceRequests) {
            
            if (refReq.Requester__c == null) {
                refReq.Requester__c = Userinfo.getUserId();
            }
        }
    }
    
    /**
     * Method called on before delete of Reference Request
     */
    public static void onBeforeDelete() {
        
        for (Reference_Request_Account__c rra : WithoutSharingHelperController.getAccountRequests2(oldReferenceRequestMap)) {
            
            for (Reward__c reward : rra.Rewards__r) {
                ConstantsController.RewardIds.add(reward.Id);
            }
            
            for (Hit_List__c hitId : rra.Hit_Lists__r) {
                ConstantsController.HitIdSet.add(hitId);
            }
        }
    }

    /**
     * Method called on after insert of Reference Request
     */
    public static void onAfterInsert() {
        list < Reference_Requests_and_Invitations__c > listNewRRI = new list < Reference_Requests_and_Invitations__c > ();
        
        for (Reference_Request__c rr : newReferenceRequests) {
            
            if (rr.Opportunity__c != null) {
                listNewRRI.add(new Reference_Requests_and_Invitations__c(Opportunity__c = rr.Opportunity__c,
                																Reference_Request__c = rr.Id));
            }
        }
        
        //Insert New RRI
        if (listNewRRI.size() > 0) {
            WithoutSharingHelperController.insertRefRequestInvi(listNewRRI);
        }
    }
    
    /**
     * Method called on after update of Reference Request
     */
    public static void onAfterUpdate() {
        list < Reference_Request_Account__c > updatedAccountRequest = new list < Reference_Request_Account__c > ();
        list < Unspecified_Request__c > updatedUnspecifiedRequest = new list < Unspecified_Request__c > ();
        
        if (ConstantsController.shouldArAndUrUpdate) {
            
            for (Reference_Request__c rrObj : WithoutSharingHelperController.getReferenceRequests1(newReferenceRequests)) {
                
                if (oldReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c != newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c) {
                    
                    if (newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c == ConstantsController.IN_PROGRESS) {
                        
                        for (Reference_Request_Account__c rraObj: rrObj.Reference_Request_Accounts__r) {
                            
                            if (rraObj.Account_Request_Status__c == null
                            			|| rraObj.Account_Request_Status__c == ConstantsController.NOT_STARTED
                            			|| rraObj.Account_Request_Status__c == ConstantsController.ONHOLD) {
                                
                                rraObj.Account_Request_Status__c = ConstantsController.IN_PROGRESS;
                                updatedAccountRequest.add(rraObj);
                            }
                        }
                        
                        for (Unspecified_Request__c urObj : rrObj.Unspecified_Requests__r) {
                            
                            if (urObj.Unspecified_Request_Status__c == null
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.NOT_STARTED
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.ONHOLD) {
                                
                                urObj.Unspecified_Request_Status__c = ConstantsController.IN_PROGRESS;
                                updatedUnspecifiedRequest.add(urObj);
                            }
                        }
                    } else if (newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c == ConstantsController.ONHOLD) {
                        
                        for (Reference_Request_Account__c rraObj : rrObj.Reference_Request_Accounts__r) {
                            
                            if (rraObj.Account_Request_Status__c == null
                            			|| rraObj.Account_Request_Status__c == ConstantsController.NOT_STARTED
                            			|| rraObj.Account_Request_Status__c == ConstantsController.IN_PROGRESS) {
                                
                                rraObj.Account_Request_Status__c = ConstantsController.ONHOLD;
                                updatedAccountRequest.add(rraObj);
                            }
                        }
                        
                        for (Unspecified_Request__c urObj : rrObj.Unspecified_Requests__r) {
                            
                            if (urObj.Unspecified_Request_Status__c == null
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.NOT_STARTED
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.IN_PROGRESS) {
                                
                                urObj.Unspecified_Request_Status__c = ConstantsController.ONHOLD;
                                updatedUnspecifiedRequest.add(urObj);
                            }
                        }
                    } else if (newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c == 'Give Up - Legal Won\'t Approve'
                    			|| newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c == 'Give Up - Service Issues'
                    			|| newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c == 'Give Up - Contact Left Company'
                    			|| newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c == 'Give Up - Contact Unresponsive') {
                        
                        for (Reference_Request_Account__c rraObj : rrObj.Reference_Request_Accounts__r) {
                            
                            if (rraObj.Account_Request_Status__c == ConstantsController.COMPLETED) {
                                newReferenceRequestMap.get(rrObj.Id).addError(System.Label.CANNOT_SET_COMPLETED_REQUEST_TO_GIVEUP);
                            } else if (rraObj.Account_Request_Status__c == null
                            			|| rraObj.Account_Request_Status__c == ConstantsController.NOT_STARTED
                            			|| rraObj.Account_Request_Status__c == ConstantsController.IN_PROGRESS
                            			|| rraObj.Account_Request_Status__c == ConstantsController.ONHOLD) {
                                
                                rraObj.Account_Request_Status__c = newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c;
                                rraObj.Project_Owner__c = UserInfo.getUserId();
                                updatedAccountRequest.add(rraObj);
                            }
                        }
                        
                        for (Unspecified_Request__c urObj : rrObj.Unspecified_Requests__r) {
                            
                            if (urObj.Unspecified_Request_Status__c == null
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.NOT_STARTED
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.IN_PROGRESS
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.ONHOLD) {
                                
                                urObj.Unspecified_Request_Status__c = ConstantsController.NO_LONGER_NEEDED;
                                urObj.Project_Owner__c = UserInfo.getUserId();
                                updatedUnspecifiedRequest.add(urObj);
                            }
                        }
                    } else if (newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c == ConstantsController.COMPLETED) {
                        
                        for (Reference_Request_Account__c rraObj : rrObj.Reference_Request_Accounts__r) {
                            
                            if (rraObj.Account_Request_Status__c == null
                            			|| rraObj.Account_Request_Status__c == ConstantsController.NOT_STARTED
                            			|| rraObj.Account_Request_Status__c == ConstantsController.IN_PROGRESS
                            			|| rraObj.Account_Request_Status__c == ConstantsController.ONHOLD) {
                                
                                rraObj.Account_Request_Status__c = ConstantsController.COMPLETED;
                                rraObj.Project_Owner__c = UserInfo.getUserId();
                                updatedAccountRequest.add(rraObj);
                            }
                        }
                        
                        for (Unspecified_Request__c urObj : rrObj.Unspecified_Requests__r) {
                            
                            if (urObj.Unspecified_Request_Status__c == null
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.NOT_STARTED
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.IN_PROGRESS
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.ONHOLD) {
                                
                                urObj.Unspecified_Request_Status__c = ConstantsController.NO_LONGER_NEEDED;
                                urObj.Project_Owner__c = UserInfo.getUserId();
                                updatedUnspecifiedRequest.add(urObj);
                            }
                        }
                    } else if (newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c == ConstantsController.NO_LONGER_NEEDED) {
                        
                        for (Reference_Request_Account__c rraObj : rrObj.Reference_Request_Accounts__r) {
                            
                            if (rraObj.Account_Request_Status__c == null
                            			|| rraObj.Account_Request_Status__c == ConstantsController.COMPLETED
                            			|| rraObj.Account_Request_Status__c == 'Give Up - Legal Won\'t Approve'
                            			|| rraObj.Account_Request_Status__c == 'Give Up - Service Issues'
                            			|| rraObj.Account_Request_Status__c == 'Give Up - Contact Left Company'
                            			|| rraObj.Account_Request_Status__c == 'Give Up - Contact Unresponsive') {
                                
                                newReferenceRequestMap.get(rrObj.Id).addError(System.Label.CANNOT_SET_COMPLETED_REQUEST_TO_NO_LONGER_NEEDED);
                            } else if (rraObj.Account_Request_Status__c == ConstantsController.NOT_STARTED
                            			|| rraObj.Account_Request_Status__c == ConstantsController.IN_PROGRESS
                            			|| rraObj.Account_Request_Status__c == ConstantsController.ONHOLD) {
                				
                                rraObj.Account_Request_Status__c = newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c;
                                rraObj.Project_Owner__c = UserInfo.getUserId();
                                updatedAccountRequest.add(rraObj);
                            }
                        }
                        
                        for (Unspecified_Request__c urObj : rrObj.Unspecified_Requests__r) {
                            
                            if (urObj.Unspecified_Request_Status__c == null
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.NOT_STARTED
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.IN_PROGRESS
                            			|| urObj.Unspecified_Request_Status__c == ConstantsController.ONHOLD) {
                                
                                urObj.Unspecified_Request_Status__c = newReferenceRequestMap.get(rrObj.Id).Reference_Request_Status__c;
                                urObj.Project_Owner__c = UserInfo.getUserId();
                                updatedUnspecifiedRequest.add(urObj);
                            }
                        }
                    }
                }
            }
            
            if (updatedAccountRequest.size() > 0) {
                WithoutSharingHelperController.updateRRA(updatedAccountRequest);
            }
            
            if (updatedUnspecifiedRequest.size() > 0) {
                WithoutSharingHelperController.updateUnspecified(updatedUnspecifiedRequest);
            }
        }

        /** New RR & Invitaion Combined Object : 09 June**/
        list<Reference_Requests_and_Invitations__c> listNewRRI = new list<Reference_Requests_and_Invitations__c>();
        set<Id> oldInvitationIds = new set<Id>();
        
        for (Reference_Request__c rr : newReferenceRequests) {
            
            if (newReferenceRequestMap.get(rr.Id).Opportunity__c != oldReferenceRequestMap.get(rr.Id).Opportunity__c) {
                
                if (newReferenceRequestMap.get(rr.Id).Opportunity__c != null) {
                    listNewRRI.add(new Reference_Requests_and_Invitations__c(Opportunity__c = rr.Opportunity__c,
                    																Reference_Request__c = rr.Id));
                }
                
                if (oldReferenceRequestMap.get(rr.Id).Opportunity__c != null) {
                    oldInvitationIds.add(rr.Id);
                }
            }
        }
        
        //Delete old RRI    
        list<Reference_Requests_and_Invitations__c> listOldRRI = WithoutSharingHelperController.getRefRequestInvitations(oldInvitationIds);
        
        if (listOldRRI.size() > 0) {
            WithoutSharingHelperController.deleteRefRequestInvitations(listOldRRI);
        }

        //Insert New RRI
        if (listNewRRI.size() > 0) {
            WithoutSharingHelperController.insertRefRequestInvi(listNewRRI);
        }
    }
    
    /**
     * Method called on after delete of Reference Request
     */
    public static void onAfterDelete() {
        
        if (ConstantsController.RewardIds != null && ConstantsController.RewardIds.size() > 0) {
            list < Reward__c > deleteRewardList = WithoutSharingHelperController.getRewardList(ConstantsController.RewardIds);
            
            if (deleteRewardList != null && deleteRewardList.size() > 0) {
                WithoutSharingHelperController.deleteRewards(deleteRewardList); 
            }
        }
        
        if (ConstantsController.HitIdSet != null && ConstantsController.HitIdSet.size() > 0) {
            list<Hit_List__c> deleteHitList = WithoutSharingHelperController.getHitLists(ConstantsController.HitIdSet);
            
            if (deleteHitList != null && deleteHitList.size() > 0) {
                WithoutSharingHelperController.deleteHitListsForUpdateRBI(deleteHitList);
            }
        }
        
        //Delete old RRI
        List<Reference_Requests_and_Invitations__c> listOldRRI = WithoutSharingHelperController.getRRIList();
        
        if (listOldRRI.size() > 0) {
            WithoutSharingHelperController.deleteRefRequestInvitations(listOldRRI);
        }
    }
    
    /**
     * Method called on after undelete of Reference Request
     */
    public static void onAfterUndelete() {
        list < Reference_Requests_and_Invitations__c > listNewRRI = new list < Reference_Requests_and_Invitations__c > ();
        list < Reference_Requests_and_Invitations__c > deleteRRI = new list < Reference_Requests_and_Invitations__c > ();
        set < Id > rrIds = new set < Id > ();
        for (Reference_Request__c rr: newReferenceRequests) {
            if (rr.Opportunity__c != null) {
                rrIds.add(rr.Id);
            }
        }

        for (Reference_Request__c rr: [SELECT Id, Opportunity__c, (Select Id, Opportunity__c From Reference_Requests_and_Invitations__r order by CreatedDate DESC) FROM Reference_Request__c WHERE Id IN: rrIds]) {
            Integer countRRI = 0;
            for (Reference_Requests_and_Invitations__c rri: rr.Reference_Requests_and_Invitations__r) {
                countRRI++;
                if (countRRI != 1) {
                    deleteRRI.add(rri);
                }
            }
            if (countRRI == 0)
                listNewRRI.add(new Reference_Requests_and_Invitations__c(Opportunity__c = rr.Opportunity__c, Reference_Request__c = rr.Id));
        }

        //Insert New RRI
        if (listNewRRI.size() > 0)
            insert listNewRRI;

        //Delete RRI
        if (deleteRRI.size() > 0)
            delete deleteRRI;
    }
}