POR/RefEdge/src/objects/Interview_Question__c.object
<CustomObject>
    <description>Custom Object to add Interview Question(Bound 6)</description>
    <fields>
        <fullName>Question__c</fullName>
        <description>Questions to be stores for reference interviews</description>
        <inlineHelpText>Questions to be stores for reference interviews</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Interview Question</label>
    <nameField>
        <displayFormat>IQ-{0000}</displayFormat>
        <label>Interview Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interview Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Interview_Topic__c.object
<CustomObject>
    <description>Custom Object to add Interview Topics for reference Interview Content types(Bound 6).</description>
    <fields>
        <fullName>Interview_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interview Question</label>
        <referenceTo>Interview_Question__c</referenceTo>
        <relationshipLabel>Interview Topics</relationshipLabel>
        <relationshipName>Interview_Topics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Interview__c</fullName>
        <label>Reference Interview</label>
        <referenceTo>Reference_Interview__c</referenceTo>
        <relationshipLabel>Interview Topics</relationshipLabel>
        <relationshipName>Interview_Topics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Video_URL__c</fullName>
        <description>This is the YouTube or BrightCove hyperlink to the media file for this interview topic.</description>
        <inlineHelpText>This is the YouTube or BrightCove hyperlink to the media file for this interview topic.</inlineHelpText>
        <label>Media URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Interview Topic</label>
    <nameField>
        <displayFormat>IT-{0000}</displayFormat>
        <label>Interview Topic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interview Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Content__c.object
<CustomObject>
    <description>This object holds all the Custom Content.</description>
    <fields>
        <fullName>Reference_Content_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Content Type</label>
        <referenceTo>Reference_Content_Type__c</referenceTo>
        <relationshipLabel>Reference Content</relationshipLabel>
        <relationshipName>Reference_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Content</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Content_Type__c.object
<CustomObject>
    <description>Reference Content Type - Replace to native CRM Content (Bound 6)</description>
    <label>Reference Content Type</label>
    <nameField>
        <displayFormat>RCT-{0000}</displayFormat>
        <label>Reference Content Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Content Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Interview__c.object
<CustomObject>
    <description>Custom Object to use Reference Interview Content type(Bound 6)</description>
    <fields>
        <fullName>Reference_Content__c</fullName>
        <label>Reference Content</label>
        <referenceTo>Reference_Content__c</referenceTo>
        <relationshipLabel>Reference Interviews</relationshipLabel>
        <relationshipName>Reference_Interviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reference Interview</label>
    <nameField>
        <displayFormat>RI-{0000}</displayFormat>
        <label>Reference Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestInterviewTopicExtension.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */  
@isTest(seeAllData = false)
public with sharing class TestInterviewTopicExtension {
    
    public static list < Reference_Interview__c > rrAIntList;
    public static list < Reference_Content__c > rrACntList;
    public static list < Interview_Topic__c > intrTopicList;
    public static list < Interview_Question__c > intrQueList;
    
    //Unit Test Method 1
    static testMethod void myUnitTest01() {
        User u = TestDataFactory.CreateUser();
        insert u;
        //Start test method
        test.startTest();
        System.runAs(u) {
            Reference_Content_Type__c customRefContent = TestDataFactory.createContentType();
            insert customRefContent;
            list<Reference_Content__c> referObject = TestDataFactory.createReferenceContent();
            referObject[0].Reference_Content_Type__c = customRefContent.Id;
            insert referObject;
            intrQueList = TestDataFactory.createInterviewQuestions();
            rrAIntList = TestDataFactory.createReferenceInterview(referObject);
            insert rrAIntList;
            
            setUpInterviewTopic();
            ApexPages.currentPage().getParameters().put('retUrl', referObject[0].Id);
            ApexPages.StandardController sc = new ApexPages.standardController(intrTopicList[0]);
            InterviewTopicExtension testObj = new InterviewTopicExtension(sc);
            testObj.ContentType = 'audio/mp3';
            testObj.contentFileName = 'audio/mp3';
            testObj.contentFile = TestDataFactory.createFile();
            
            testObj.save();
            testObj.cancel();
            
            system.assertEquals(testObj.returl, referObject[0].Id);
            testObj.ContentType = 'audio123';
            testObj.save();
        }
        //Stop test method
        test.stopTest();
    }
    //Interview_Topic Setup
    private static void setUpInterviewTopic() {
        intrTopicList = new List < Interview_Topic__c >();
        intrTopicList.add( new Interview_Topic__c(Interview_Question__c = intrQueList[0].Id,Question__c = 'Test Interview1',Reference_Interview__c = rrAIntList[0].Id,Video_URL__c='https://www.youtube.com/watch?v=0GWWcwpGosw'));
        insert intrTopicList;
    }
}