POR/RefEdge/src/objects/Invitation__c.object
<CustomObject>
    <description>Content Sharing (Bound 4)</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invitations</relationshipLabel>
        <relationshipName>Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invitation</label>
    <nameField>
        <label>Invitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request__c.object
<CustomObject>
    <description>This object holds the information necessary for a reference request</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity association</description>
        <inlineHelpText>Associated opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Reference Requests</relationshipLabel>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Request</label>
    <nameField>
        <displayFormat>RR-{000000000}</displayFormat>
        <label>Reference Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Requests_and_Invitations__c.object
<CustomObject>
    <description>RefEdge Object that combines the peer data of Invitations and Reference Requests (both of which are related children of Opportunity) for comprehensive Revenue Influenced reporting.</description>
    <fields>
        <fullName>Invitation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invitation</label>
        <referenceTo>Invitation__c</referenceTo>
        <relationshipLabel>Reference Requests and Invitations</relationshipLabel>
        <relationshipName>Reference_Requests_and_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Reference Requests and Invitations</relationshipLabel>
        <relationshipName>Reference_Requests_and_Invitations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipLabel>Reference Requests and Invitations</relationshipLabel>
        <relationshipName>Reference_Requests_and_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Requests and Invitations</label>
    <nameField>
        <displayFormat>RRI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests and Invitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/Batch_DataCreate_RRI.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */
/**
 * Class: RefedgeSetupHomeController
 * Description : This Batch called FROM RefedgeSetupHomeController to create Reference_Requests_and_Invitations__c records for opportunity
 * Modified by: Rekha Jangir @Nov/16/2016
 */
global with sharing class Batch_DataCreate_RRI implements Database.Batchable<sObject> {
    /**
     * Properties and variables
     */
    private String soqlQuery = '';

    /**
     * Constructor
     */
    global Batch_DataCreate_RRI() {
        soqlQuery = 'SELECT Id, (SELECT Reference_Request__c, Invitation__c FROM Reference_Requests_and_Invitations__r), ' 
        				+ '(SELECT Id, Opportunity__c FROM Reference_Requests__r WHERE Opportunity__c != null), ' 
        				+ '(SELECT Id, Opportunity__c FROM Invitations__r  WHERE Opportunity__c != null) FROM Opportunity ';
    }

    /**
     * Method to get the data to be proceesed   
     */
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(soqlQuery);
    }

    /**
     * Method to execute the batch
     */
    global void execute(Database.BatchableContext BC, List<Opportunity> scope) {
        List<Reference_Requests_and_Invitations__c> listNewRRI = new List<Reference_Requests_and_Invitations__c>();
        Set<String> setRRandInvIds = new Set<String>();
        
        //Iterate Opportunity list 
        for (Opportunity opp : scope) {
        	
            for (Reference_Requests_and_Invitations__c rri : opp.Reference_Requests_and_Invitations__r) {
            	
                if (rri.Reference_Request__c != null) {
                    setRRandInvIds.add(rri.Reference_Request__c);
                }
                    
                if (rri.Invitation__c != null) {
                    setRRandInvIds.add(rri.Invitation__c);
                }
            }
            
            for (Reference_Request__c rr : opp.Reference_Requests__r) {
            	
                if (rr.Opportunity__c != null && !setRRandInvIds.contains(rr.Id)) {
                    listNewRRI.add(new Reference_Requests_and_Invitations__c(Opportunity__c = opp.Id, Reference_Request__c = rr.Id));
                }
            }
            
            for (Invitation__c inv : opp.Invitations__r) {
            	
                if (inv.Opportunity__c != null && !setRRandInvIds.contains(inv.Id)) {
                    listNewRRI.add(new Reference_Requests_and_Invitations__c(Opportunity__c = opp.Id, Invitation__c = inv.Id));
                }
            }
        }
        
        //Insert New RRI
        if (listNewRRI.size() > 0) {
            insert listNewRRI;
        }
    }

    /**
     * Method to be called after the excute
     */
    global void finish(Database.BatchableContext BC) {}
}