POR/RefEdge/src/objects/Reference_Basic_Information__c.object
<CustomObject>
    <description>Basic Information for Account &amp; Contact(Bound 5)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Reference Owner field identifies the individual, other than the Account Owner, designated as point of contact for reference requests for the Account.</inlineHelpText>
        <label>Reference Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Basic_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Profile</label>
    <nameField>
        <displayFormat>RBI-{00000}</displayFormat>
        <label>Reference Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request__c.object
<CustomObject>
    <description>This object holds the information necessary for a reference request</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Reference Requests</relationshipLabel>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Request</label>
    <nameField>
        <displayFormat>RR-{000000000}</displayFormat>
        <label>Reference Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Account__c.object
<CustomObject>
    <description>Junction table associating Reference Requests with accounts</description>
    <fields>
        <fullName>Account_Request_Status__c</fullName>
        <label>Managed Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Legal Won&apos;t Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Left Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Up - Contact Unresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unavailable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>Reference request account</description>
        <inlineHelpText>Reference request account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Managed_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Managed Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <picklist>
            <picklistValues>
                <fullName>Peer2Peer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Managed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request_Additional_Info__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Request Additional Info</label>
        <referenceTo>Reference_Request_Additional_Info__c</referenceTo>
        <relationshipLabel>Account Requests</relationshipLabel>
        <relationshipName>Account_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <description>Reference request association</description>
        <inlineHelpText>Reference request association</inlineHelpText>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_Type_Needed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Type Needed</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Referenceability_Type__c.Project_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Referenceability_Type__c.Request_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Account Requests</relationshipLabel>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Notes__c</fullName>
        <inlineHelpText>Provide details that will help the recipient process your request.</inlineHelpText>
        <label>Request Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Request_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Request</label>
    <nameField>
        <displayFormat>RRA-{000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Request_Additional_Info__c.object
<CustomObject>
    <description>Custom Object Additional Referenceability type Information from Reference Use Request Page (Bound 3)</description>
    <label>Reference Request Additional Info</label>
    <nameField>
        <displayFormat>RRAI-{000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Request Additional Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Unspecified_Request__c.object
<CustomObject>
    <description>Unspecified Request associating with Reference Requests without accounts(Bound 3)</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PO_Unspecified_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request_Additional_Info__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Request Additional Info</label>
        <referenceTo>Reference_Request_Additional_Info__c</referenceTo>
        <relationshipLabel>Unspecified Requests</relationshipLabel>
        <relationshipName>Unspecified_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipLabel>Unspecified Requests</relationshipLabel>
        <relationshipName>Unspecified_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference_Type_Needed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Type Needed</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Referenceability_Type__c.Project_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Referenceability_Type__c.Request_type__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Unspecified Requests</relationshipLabel>
        <relationshipName>Unspecified_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Notes__c</fullName>
        <label>Request Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Unspecified_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specified_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Specified Account</label>
        <referenceTo>Reference_Request_Account__c</referenceTo>
        <relationshipLabel>Unspecified Requests</relationshipLabel>
        <relationshipName>Unspecified_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unspecified_Request_Status__c</fullName>
        <label>Unspecified Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Reference Match</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Unspecified Request</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unspecified Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/AllCasesARandURController.cls
/**
 * ReferenceEdge
 *
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"),
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR,
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING,
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS
 * WRITTEN CONSENT FROM COMPANY.
 */
/**
 * VF Page: AllCasesARandUR
 * Description: controller for inline page on case detail page to show all the
 *				reference requests related to the case record
 * LastModified by: Gaurav Saini (13 June, 2017) for #732
 */
public with sharing class AllCasesARandURController extends RefEdgeEditionFeatures {
    
    /**
     * Properties and variables
     */
    public Map<String, List<Reference_Request_Account__c>> accountRequestMap { get; set; }
    public Map<String, List<Unspecified_Request__c>> unspecifiedRequestMap { get; set; }
    public List<RequestWrapper> requestList { get; set; }
    public boolean isSalesUser { get; set; }
    public boolean isSLDS { get; set; }
    
    /**
     * Constructor
     */
    public AllCasesARandURController(ApexPages.StandardController controller) {
        Case caseObj = (Case)controller.getRecord();
        
        if (UserInfo.getUiTheme() == 'Theme4d' || UserInfo.getUiTheme() == 'Theme4t') {
            system.debug('*********SF1');
            isSLDS = true;
        } else {
            system.debug('********normal');
            isSLDS = false;
        }
        
        if (!isSLDS) {
	        String caseId = caseObj.Id;
	        requestList = new List<RequestWrapper>();
	        accountRequestMap = new Map<String, List<Reference_Request_Account__c>>();
	        unspecifiedRequestMap = new Map<String, List<Unspecified_Request__c>>();
	        
	        isSalesUser = false;
	        List<Profile> proList = [SELECT Id, Name FROM Profile WHERE Id = :UserInfo.getProfileId() LIMIT: limits.getLimitQueryRows()];
	        
	        if (proList.size() > 0) {
	        	isSalesUser = (proList[0].Name.contains('Sales') ? true : false);
	        }
	        List<String> accountsIds = new List<String>();
	        List<Reference_Request__c> refRequets = [SELECT Id, Name, 
	    										(SELECT Name, Deadline__c, Reference_Type_Needed__c, Requester__c,
	    											Reference_Request_Additional_Info__c, Request_Notes__c,
	    											Specified_Account__c, Unspecified_Request_Status__c,
	    											Project_Owner__c, Project_Owner__r.Name, Specified_Account__r.Name,
	    											Reference_Type_Needed__r.Name
	    											FROM Unspecified_Requests__r
	    											ORDER BY CreatedDate DESC),
												(SELECT Name, Account__c, Deadline__c, Requester__c, Managed_Request__c, Process__c,
													Reference_Type_Needed__c, Approval_Status__c, Account_Request_Status__c,
													Reference_Owner__c, Reference_Owner__r.Name, Account__r.Name, Reference_Type_Needed__r.Name
													FROM Reference_Request_Accounts__r
													ORDER BY CreatedDate DESC)
												FROM Reference_Request__c r
												WHERE Case__c = :caseId
												ORDER BY CreatedDate DESC];
	        
	        for (Reference_Request__c req : refRequets) {
	        	 
	            for (Reference_Request_Account__c rra : req.Reference_Request_Accounts__r) {
	        		accountsIds.add(rra.Account__c);
	            }
	        }
	        Map<Id,Reference_Basic_Information__c> rbiMap = new Map<Id,Reference_Basic_Information__c>();
	        
	        for (Reference_Basic_Information__c rbi : WithoutSharingHelperController.getAccountsRBI(accountsIds)) {
	        	rbiMap.put(rbi.Account__c, rbi);
	        }
	        List<Group> groups = [SELECT Id FROM Group WHERE Name = 'Customer Reference Team'];
	        
	        for (Reference_Request__c req : refRequets) {
	            requestList.add(new RequestWrapper(req, req.Reference_Request_Accounts__r, req.Unspecified_Requests__r, rbiMap, groups[0].Id));
	        }
        }
    }
    
    /**
     * Wrapper class
     */
    public class RequestWrapper {
        public Reference_Request__c request { get; set; }
        public List<AccountRequestWrapper> accReqs { get; set; }
        public List<UnspecifiedWrapper> unspReqs { get; set; }
        
        public RequestWrapper(Reference_Request__c request, List<Reference_Request_Account__c> accReqs1, 
        			List<Unspecified_Request__c> unspReqs1, Map<Id,Reference_Basic_Information__c> rbiMap, String gId) {
            this.request = request;
            this.accReqs = new List<AccountRequestWrapper>();
            
            for (Reference_Request_Account__c rra : accReqs1) {
            	accReqs.add(new AccountRequestWrapper(rra, rbiMap, gId));
            }
            this.unspReqs = new List<UnspecifiedWrapper>();
            
            for (Unspecified_Request__c rra : unspReqs1) {
            	unspReqs.add(new UnspecifiedWrapper(rra, gId));
            }
        }
    }
    
    /**
     * Wrapper class
     */
    public class AccountRequestWrapper {
    	public Reference_Request_Account__c rra { get; set; }
    	public String Owner { get; set; }
        public String OwnerName { get; set; }
        
        public AccountRequestWrapper(Reference_Request_Account__c rra, Map<Id, Reference_Basic_Information__c> rbiMap, String gId) {
        	this.rra = rra;
        	
        	if (rra.Process__c == 'Peer2Peer') {
        		this.Owner = (rra.Reference_Owner__c != null ? rra.Reference_Owner__c : gId);
        		this.OwnerName = (rra.Reference_Owner__c != null ? rra.Reference_Owner__r.Name : 'Reference Team');
        	} else {
        		this.Owner = (rra.Reference_Owner__c != null ? rra.Reference_Owner__c : gId);
        		this.OwnerName = (rra.Reference_Owner__c != null ? rra.Reference_Owner__r.Name : 'Reference Team');
        	}
        }
    }
    
    /**
     * Wrapper class
     */
    public class UnspecifiedWrapper {
    	public Unspecified_Request__c unspReq { get; set; }
    	public String Owner { get; set; }
        public String OwnerName { get; set; }
        
        public UnspecifiedWrapper(Unspecified_Request__c unspReq, String gId) {
        	this.unspReq = unspReq;
    		this.Owner = (unspReq.Project_Owner__c != null ? unspReq.Project_Owner__c : gId);
    		this.OwnerName = (unspReq.Project_Owner__c != null ? unspReq.Project_Owner__r.Name : 'Reference Team');
        }
    }
}