POR/RefEdge/src/objects/Referenceability_Type__c.object
<CustomObject>
    <description>An object that contains the various Referenceability Types.</description>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This type will appear in the list of available types when adding referenceability to an Account or Contact, and will show in RefSearch.</inlineHelpText>
        <label>Referenceability Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referenceability_code__c</fullName>
        <description>This is use to give event api code.</description>
        <inlineHelpText>This is use to give event api code.</inlineHelpText>
        <label>Referenceability_code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Referenceability Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referenceability Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reward__c.object
<CustomObject>
    <description>Custom Object to Store Rewards.(Bound 4)</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expired_Points__c</fullName>
        <label>Expired Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expired_Points_in_influitive__c</fullName>
        <description>Expired Points in influitive</description>
        <inlineHelpText>Expired Points in influitive</inlineHelpText>
        <label>Expired Points in Influitive</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Influitive_ID2__c</fullName>
        <externalId>true</externalId>
        <label>Influitive ID2</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Influitive_Id__c</fullName>
        <label>Influitive Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referenceability_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Type</label>
        <referenceTo>Referenceability_Type__c</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <picklist>
            <picklistValues>
                <fullName>Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeem</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <displayFormat>RW-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/Infl_Event.cls
/**
 * ReferenceEdge
 *
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"),
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR,
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING,
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS
 * WRITTEN CONSENT FROM COMPANY.
 */ 
/** 
 * Author :  Narender Singh Tanwar
 * Description:  Classe used to update rewards in respect of influitive.  
 * Last Modified By: Rajesh @Feb 6 2017
 */
public with sharing class Infl_Event {
	/**
     * Creating Handler instance
     */ 
    private static InflAPIHandler handler = new InflAPIHandler();
    public static List<Reward__c> rewardList;
    
    @future(callout=true)
    public static void influitiveEventsCallout(String jsonMapContactString, String jsonMapReferenceabilityTypeString, String jsonNewMapString, String jsonOldMapString, String jsonNewListString) {
        // List of Reward to be updated
        rewardList = new List<Reward__c>();
        //deserialize the JSON to their respective type.
        Map<Id, Contact> mapContact = (Map<Id, Contact>)Json.deserialize(jsonMapContactString, Map<Id, Contact>.class);
        Map<Id, Referenceability_Type__c> mapReferenceabilityType = (Map<Id, Referenceability_Type__c>)Json.deserialize(jsonMapReferenceabilityTypeString, Map<Id, Referenceability_Type__c>.class);
        Map<Id, Reward__c> newMap = (Map<Id, Reward__c>)Json.deserialize(jsonNewMapString, Map<Id, Reward__c>.class);
        Map<Id, Reward__c> oldMap = (Map<Id, Reward__c>)Json.deserialize(jsonOldMapString, Map<Id, Reward__c>.class);        
		List<Reward__c> newList = (List<Reward__c>)Json.deserialize(jsonNewListString, List<Reward__c>.class);
        
        for (Reward__c reward : newList) { 
             
            if (reward.Contact__c != null && mapContact != null && mapContact.size() > 0 && mapContact.containsKey(reward.Contact__c)) {
				// If Stands for After insert and Else Stands for after Update.
                if (mapContact.get(reward.Contact__c).email != null && reward.Amount__c != null && reward.Influitive_Id__c == null 
                                                                            && reward.Influitive_ID2__c == null && oldMap.Size() == 0) {
                	String defaultRefType = 'Non-Reference Activity';
                	                       
                    if (reward.Referenceability_Type__c != null) {

                        //REF-2389
                        if (mapReferenceabilityType.containsKey(reward.Referenceability_Type__c)) {
                            defaultRefType = String.valueOf(mapReferenceabilityType.get(reward.Referenceability_Type__c).Referenceability_code__c);
                        }
                    }
					
                    if(!Test.isRunningTest()) {
                    	handleRBIReward(defaultrefType, mapContact.get(reward.Contact__c).email, 
                    									(reward.Transaction__c == ConstantsController.ISSUE ? String.valueOf(reward.Amount__c) : '-' 
                    									+ String.valueOf(reward.Amount__c)), reward.Contact__c, reward, false);
                    }
                    //REF-2389
                } else if (mapContact.get(reward.Contact__c).email != null && reward.Referenceability_Type__c != null && reward.Amount__c != null && reward.Influitive_Id__c == null
								&& oldMap.Size() > 0 && reward.Influitive_ID2__c == null && mapReferenceabilityType.containskey(reward.Referenceability_Type__c)) {  
                     
                    handleRBIReward(String.valueOf(mapReferenceabilityType.get(reward.Referenceability_Type__c).Referenceability_code__c), 
                    											mapContact.get(reward.Contact__c).email, (reward.Transaction__c == ConstantsController.ISSUE 
                    											? String.valueOf(reward.Amount__c) : '-' + String.valueOf(reward.Amount__c)), reward.Contact__c, 
                    											reward, false);
                } else if (mapContact.get(reward.Contact__c).email != null && reward.Transaction__c == ConstantsController.ISSUE && oldMap.Size() > 0 
                											&& oldMap.get(reward.Id).Expired__c != newMap.get(reward.Id).Expired__c && reward.Expired__c
                                                            && reward.Influitive_Id__c != ConstantsController.ADJUSTMENT_INFL_ID) {
                    handleRBIReward('', mapContact.get(reward.Contact__c).email, '-' + String.valueOf(reward.Expired_Points__c), 
                    									reward.Contact__c, reward, true);
                } else if (mapContact.get(reward.Contact__c).email != null && reward.Transaction__c == ConstantsController.ISSUE && oldMap.Size() > 0 && 
                											oldMap.get(reward.Id).Expired__c != newMap.get(reward.Id).Expired__c && !reward.Expired__c 
                											&& reward.Expired_Points_in_influitive__c != null && reward.Expired_Points_in_influitive__c> 0
                                                            && reward.Influitive_Id__c != ConstantsController.ADJUSTMENT_INFL_ID) { //REF-1618
                    handleRBIReward('', mapContact.get(reward.Contact__c).email, String.valueOf(reward.Expired_Points_in_influitive__c), 
                    										reward.Contact__c, reward, true);
                }
            }
        } 
        
        if (rewardList.Size() > 0) {
        	update rewardList;
        }
    }
    
    /*
		Re #1181
		To handle future call inside loop
		Modified By: Rajneesh Jan 2,2018	
	*/
	public static void handleRBIReward(String reftype, String email, String points, String contactId, Reward__c reward, Boolean isExpired) {
		 
        if (isExpired) {
            reftype = 'expired_rewards';
        }
        
        //constructing Infl_EventJSON object 
        Infl_EventJSON request = new Infl_EventJSON(); 
        request.type = reftype; 
        Infl_EventJSON.cls_contact contact = new Infl_EventJSON.cls_contact();
        contact.crm_contact_id = contactId;//re #190-Added Contact Id
        contact.email = email;
        request.contact = contact;
        request.points = points;
        // Adding response to create events
        InflCreateEventResponse response = handler.createInflEvent(request);
        
        //REF-2300
        if (response != null && response.id == null) {
            request.type = ConstantsController.NON_REFEDGE_ACTIVITY_EVENT;
            response = new InflCreateEventResponse();
            response = handler.createInflEvent(request);            
        }
         
        if (response != null && reward != null && response.id != null && response.id != '') {
            
            if (!isExpired) {
                reward.Influitive_ID2__c = response.id;
            }
            
            if (isExpired && points.contains('-')) {
                reward.Expired_Points_in_influitive__c = reward.Expired_Points__c;
            } else {
                reward.Expired_Points_in_influitive__c = 0;
            }
            rewardList.add(reward);
        }
	}
    
    /**
     * Method to call apiHandler to create event at influitive
     * REF-1964
     */
    public static String syncRewardAtHub(Reward__c reward, String typeCode) {
        Infl_EventJSON refJSON = new Infl_EventJSON();
        refJSON.type = typeCode;//'ref';
        refJSON.points = String.valueOf(reward.Amount__c);
        Infl_EventJSON.cls_contact cls = new Infl_EventJSON.cls_contact();
        cls.email = reward.Contact__r.Email;
        refJSON.contact = cls;
        InflCreateEventResponse response = handler.createInflEvent(refJSON);
        
        //REF-2300
        if (response != null && response.id == null) {
            refJSON.type = ConstantsController.NON_REFEDGE_ACTIVITY_EVENT;
            response = new InflCreateEventResponse();
            response = handler.createInflEvent(refJSON);            
        }
        
        if (response != null && response.id != null && response.id != '') {
            return response.id;
        }
        return null;
    }
}