POR/RefEdge/src/objects/Reference_Content__c.object
<CustomObject>
    <description>This object holds all the Custom Content.</description>
    <fields>
        <fullName>Reference_Content_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Content Type</label>
        <referenceTo>Reference_Content_Type__c</referenceTo>
        <relationshipLabel>Reference Content</relationshipLabel>
        <relationshipName>Reference_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reference Content</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/objects/Reference_Content_Type__c.object
<CustomObject>
    <description>Reference Content Type - Replace to native CRM Content (Bound 6)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Reference Content Type</label>
    <nameField>
        <displayFormat>RCT-{0000}</displayFormat>
        <label>Reference Content Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Content Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

POR/RefEdge/src/classes/TestRefContentTypeTriggerHandler.cls
/**
 * ReferenceEdge
 * 
 * Point of Reference, Inc. - Copyright 2014 All rights reserved.
 *
 * @company : Point of Reference, Inc.
 * @website : www.point-of-reference.com
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED "AS-IS" BY POINT OF REFERENCE ("POR"), 
 * WITH NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, 
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. 
 * POR SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, 
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES. POR IS NOT LIABLE FOR, 
 * AND MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING, THE ACTIONS OR OMISSIONS OF 
 * ANY THIRD PARTIES (OR THE PRODUCTS OR SERVICES OFFERED BY ANY THIRD PARTIES) INCLUDING, 
 * WITHOUT LIMIATION, SALESFORCE.COM. COPY, USE OR DISTRIBUTION PROHIBITED WITHOUT EXPRESS 
 * WRITTEN CONSENT FROM COMPANY.
 */ 
@isTest(seeAllData = false)
public with sharing class TestRefContentTypeTriggerHandler {
	static TestMethod void testMethod01(){
		Reference_Content_Type__c rct = new Reference_Content_Type__c(name__c = 'test',active__c=true);
		insert rct;
		Reference_Content__c rc = new Reference_Content__c(title__c = 'test', Reference_Content_Type__c = rct.Id);
		insert rc;
		test.startTest();
			try{
				delete rct;
			}
			catch(System.DmlException  e){
				system.assertEquals(e.getDmlMessage(0),'You Cannot Delete this Content Type as it is Associated With Reference Contents.');
			}
		test.stopTest();
	}
}