Blackpurl/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Type</label>
        <referenceTo>Account_Type__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Account_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Account Type</label>
        <referenceTo>Account_Type__c</referenceTo>
        <relationshipLabel>Accounts (Vendor Account Type)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Account_Type__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Applies_To__c</fullName>
        <label>Applies To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customers</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Vendors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Sales_Tax_Item__c.object
<CustomObject>
    <fields>
        <fullName>Forms_Label__c</fullName>
        <label>Forms Label</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Sales Tax Item</label>
    <nameField>
        <displayFormat>STI-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Tax Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Tax_Exemption__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Type</label>
        <referenceTo>Account_Type__c</referenceTo>
        <relationshipLabel>Tax Exemptions</relationshipLabel>
        <relationshipName>Tax_Exemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tax Exemptions</relationshipLabel>
        <relationshipName>Tax_Exemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax Item</label>
        <referenceTo>Sales_Tax_Item__c</referenceTo>
        <relationshipLabel>Tax Exemptions</relationshipLabel>
        <relationshipName>Tax_Exemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tax Exemption</label>
    <nameField>
        <displayFormat>TE-{00000000}</displayFormat>
        <label>Tax Exemption Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Exemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/classes/AccountTypeSOQLUtil.cls
/**
 * Author: Rajat Jain
 * Since: October 8, 2018
 * Name: AccountTypeSOQLUtil
 * Description: SOQL Util class for Account Type
**/
public without sharing class AccountTypeSOQLUtil { 
    
    public static List<Account_Type__c> getAccountType(Map<String, String> fieldNameToFieldValueMap) { 
        String query = 'SELECT ';
        for(String fieldName : AccountTypeWrapper.getAccountTypeFields()) {
            fieldName = BPUtility.escapeSingleQuotes(fieldName);
            query += fieldName + ', ';  
        }
        // Child Query
        query += '(Select Id, Sales_Tax_Item__r.Name__c from Tax_Exemptions__r), (Select Id from Accounts__r), (Select Id from Accounts1__r)';  
        query += ' FROM Account_Type__c';
        query += getWhereClause(fieldNameToFieldValueMap);
        query += ' ORDER BY Applies_To__c ASC';
        query += ' LIMIT ' + SOQLUtil.getAvailableQueryRowsLimit();
        if(AccessControl.ifObjectFieldIsAccessible('Account_Type__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        return Database.query(query); 
    }
     
    public static List<Account_Type__c> getTaxExemptionRecForAccType(Map<String, String> fieldNameToFieldValueMap) {
        String query = 'SELECT ';
        for(String fieldName : AccountTypeWrapper.getAccountTypeFields()) {
            fieldName = BPUtility.escapeSingleQuotes(fieldName);
            query += fieldName + ', ';  
        }
        // Child Query
        query += '(Select Id, Customer__c, Sales_Tax_Item__r.Name__c, Sales_Tax_Item__r.Rate__c, Sales_Tax_Item__r.Forms_Label__c from Tax_Exemptions__r), (Select Id from Accounts__r), (Select Id from Accounts1__r)';
        query += ' FROM Account_Type__c';
        query += getWhereClause(fieldNameToFieldValueMap);
        if(AccessControl.ifObjectFieldIsAccessible('Account_Type__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        return Database.query(query);
    }
    
    public static List<Sales_Tax_Item__c> getAllSalesTaxItemWithExemptions() {
        if(AccessControl.ifObjectFieldIsAccessible('Sales_Tax_Item__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        String query;
        query = 'SELECT Name__c, Rate__c, Forms_Label__c, ';
        
        // child Query - Tax Exemptions
        query += '(SELECT Id, Customer__c from Tax_Exemptions__r)'; 
        query += ' FROM ' + Constants.NAMESPACE + 'Sales_Tax_Item__c ';
        
        List<Sales_Tax_Item__c> salesTaxItemList = Database.query(query);
        return salesTaxItemList;  
    }
    private static String getWhereClause(Map<String, String> fieldNameToFieldValueMap) {
        String whereClause = '';
        Boolean isWhereClauseAdded = false;
        for(String fieldName : fieldNameToFieldValueMap.keySet()) {
            fieldName = BPUtility.escapeSingleQuotes(fieldName);
            if(isWhereClauseAdded) {
            	if(BPUtility.escapeSingleQuotes(fieldNameToFieldValueMap.get(fieldName)) == 'true') {
            		whereClause += ' AND ' + fieldName + ' = ' + BPUtility.escapeSingleQuotes(fieldNameToFieldValueMap.get(fieldName));
            	} else {
            		whereClause += ' AND ' + fieldName + ' = \'' + BPUtility.escapeSingleQuotes(fieldNameToFieldValueMap.get(fieldName)) + '\'';
            	}
            } else {
            	if(BPUtility.escapeSingleQuotes(fieldNameToFieldValueMap.get(fieldName)) == 'true') {
            		whereClause += ' AND ' + fieldName + ' = ' + BPUtility.escapeSingleQuotes(fieldNameToFieldValueMap.get(fieldName));
            	} else {
	                whereClause += ' WHERE ' + fieldName + ' = \'' + BPUtility.escapeSingleQuotes(fieldNameToFieldValueMap.get(fieldName)) + '\'';
	                isWhereClauseAdded = true;
            	}
            }
        }
        return whereClause;
    }
    
}