Blackpurl/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Vendor</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/classes/AccountingVendorBatchSchedulerTest.cls
/**
 * Author: Nikhil Kumar Srivastava
 * Since: April 16, 2019
 * Name: AccountingVendorBatchSchedulerTest
 * Description: test Class for AccountingVendorBatchScheduler.
**/

@isTest
public with sharing  class AccountingVendorBatchSchedulerTest {

	@testSetup
    private static void setupTestData() { 
       	TestUtil.createIFWConfigForXero();
       	Account vendorObj = TestUtil.createVendor(true, 'Xero Vendor');
    	system.assertEquals(true, String.isNotBlank(vendorObj.Id));
    }
    
	static testmethod void AccountingCustomerBatchSchedulerTest() { 
		List<IFW_IntegrationConfig__c> IFWConfigObj = [Select Id from IFW_IntegrationConfig__c];
		IFW_IntegrationConfigItem__c IFWConfigItemObj = TestUtil.createIFWConfigItemForXero('Contacts' , IFWConfigObj[0].Id);
		List<Account> accList = [Select Id,Is_Vendor__c from Account where Is_Vendor__c = true Limit 1];
		system.assertEquals(1,accList.size());
		system.assertEquals(true,accList[0].Is_Vendor__c);
		test.startTest();
		XeroScriptUtil.syncVendors(25,60,25);
		test.stopTest();
	 }
}