Blackpurl/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <description>General customer notes</description>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/CO_Header__c.object
<CustomObject>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <description>General unit notes</description>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Notes__c.object
<CustomObject>
    <description>Generic Notes Object to record concerns related to the Sobject which requires large character limits</description>
    <label>Notes</label>
    <nameField>
        <displayFormat>NT-{00000000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Service_Order_Header__c.object
<CustomObject>
    <description>Object used to handle service related section on Customer order header</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Unique name field</description>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Service Order Header</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/classes/JobSchedulingCtrlTest.cls
@isTest
private class JobSchedulingCtrlTest {
	@testsetup
	private static void setup(){
		Account customerRec = TestDataFactory.createCustomer('Test001', 'Individual', 'Fname', 'Lname');
		Customer_Owned_Unit__c unitRec = TestDataFactory.createCustomerOwnedUnit(customerRec.Id, 'VIN001');
		Event eventRec = TestDataFactory.createEventForAfternoon(customerRec.Id, unitRec.Id);
		CO_Header__c coHeaderRec = TestDataFactory.createCoHeader(customerRec.Id);
	}   
	
	@isTest
	private static void testLoadJobSchedulingEvents(){
		Test.startTest();
		Event event = [SELECT Id, Title__c, Notes__c, AdditionalNotes__c, Subject, Type, WhatId, IsMultiDayEvent__c, StartDateTime, EndDateTime FROM Event LIMIT 1];
		Datetime startDateTime = Datetime.newInstance(2019, 3, 10, 05, 30, 0);
		Datetime endDateTime = Datetime.newInstance(2019, 3, 12, 05, 30, 0);
		event.StartDateTime = startDateTime;
		event.EndDateTime = endDateTime;
		update event;
		JobSchedulingWrapper jobSchedulingWrapper = new JobSchedulingWrapper(event, startDateTime, endDateTime);
		system.assertEquals(JobSchedulingCtrl.loadJobSchedulingEvents(), BPUtility.getEncodedString(''));
		Test.stopTest();
	}
	
	@isTest
	private static void testSOWrappper(){
		Test.startTest();
		CO_Header__c coHeaderRec = [SELECT Id FROM CO_Header__c LIMIT 1];
		Service_Order_Header__c soHeader = TestDataFactory.createSOheader(coHeaderRec.Id);
		JobSchedulingWrapper.SOWrapper soWrapper = new JobSchedulingWrapper.SOWrapper(soHeader);
		system.assertEquals(soWrapper.SectionName, soHeader.Name__c);
		Test.stopTest();
	}
	
	@isTest
	private static void testLoadSchedulingEvents(){
		Test.startTest();
		Event event = [SELECT Id, Title__c, Notes__c, AdditionalNotes__c, Subject, Type, WhatId, IsMultiDayEvent__c, StartDateTime, EndDateTime FROM Event LIMIT 1];
		JobSchedulingWrapper jobSchedulingWrapper = new JobSchedulingWrapper(event);
		String eventJson = json.serialize(jobSchedulingWrapper);
		eventJson = BPUtility.getEncodedString(eventJson);
		String result = BPUtility.getDecodedString(JobSchedulingCtrl.loadSchedulingEvents(eventJson));
		List<JobSchedulingWrapper> allEventList = (List<JobSchedulingWrapper>)json.deserialize(result, List<JobSchedulingWrapper>.class);
		system.assertEquals('Test Event', allEventList[0].Subject);
		Test.stopTest();
	}
	
	@isTest
	private static void testLoadSchedulingEventsForCurrentViewMonth(){
		Test.startTest();
		Event event = [SELECT Id, Title__c, Notes__c, AdditionalNotes__c, Subject, Type, WhatId, IsMultiDayEvent__c, StartDateTime, EndDateTime FROM Event LIMIT 1];
		event.Type = 'Appointment';
		event.IsMultiDayEvent__c = true;
		update event;
		JobSchedulingWrapper jobSchedulingWrapper = new JobSchedulingWrapper(event);
		jobSchedulingWrapper.CurrentView = 'Month';
		jobSchedulingWrapper.Id = null;
		jobSchedulingWrapper.ReminderFilter = true;
		jobSchedulingWrapper.AppointmentFilter = true;
		jobSchedulingWrapper.AppointmentwithserviceFilter = true;
		String eventJson = json.serialize(jobSchedulingWrapper);
		eventJson = BPUtility.getEncodedString(eventJson);
		String result = BPUtility.getDecodedString(JobSchedulingCtrl.loadSchedulingEvents(eventJson));
		List<List<JobSchedulingWrapper>> allEventList = (List<List<JobSchedulingWrapper>>)json.deserialize(result, List<List<JobSchedulingWrapper>>.class);
		system.assertEquals(2, allEventList.size());
		Test.stopTest();
	}
	
	@isTest
	private static void testLoadSchedulingEventsWithStartDateNotNull(){
		Test.startTest();
		Event event = [SELECT Id, Title__c, Notes__c, AdditionalNotes__c, Subject, Type, WhatId, IsMultiDayEvent__c, StartDateTime, EndDateTime FROM Event LIMIT 1];
		JobSchedulingWrapper jobSchedulingWrapper = new JobSchedulingWrapper(event);
		jobSchedulingWrapper.StartCalendarViewDate = '03/03/2019';
		jobSchedulingWrapper.StartCalendarViewTime = '02:00AM';
		jobSchedulingWrapper.EndCalendarViewDate = '03/03/2019';
		jobSchedulingWrapper.EndCalendarViewTime = '03:00AM';
		String eventJson = json.serialize(jobSchedulingWrapper);
		eventJson = BPUtility.getEncodedString(eventJson);
		String result = BPUtility.getDecodedString(JobSchedulingCtrl.loadSchedulingEvents(eventJson));
		List<JobSchedulingWrapper> allEventList = (List<JobSchedulingWrapper>)json.deserialize(result, List<JobSchedulingWrapper>.class);
		system.assertEquals('Test Event', allEventList[0].Subject);
		Test.stopTest();
	}
	
	@isTest
	private static void testLoadSchedulingEventsWithEventIdNull(){
		Test.startTest();
		Event event = [SELECT Id, Title__c, Notes__c, AdditionalNotes__c, Subject, Type, WhatId, IsMultiDayEvent__c, StartDateTime, EndDateTime FROM Event LIMIT 1];
		JobSchedulingWrapper jobSchedulingWrapper = new JobSchedulingWrapper(event);
		jobSchedulingWrapper.Id = null;
		jobSchedulingWrapper.ReminderFilter = true;
		jobSchedulingWrapper.AppointmentFilter = true;
		jobSchedulingWrapper.AppointmentwithserviceFilter = true;
		String eventJson = json.serialize(jobSchedulingWrapper);
		eventJson = BPUtility.getEncodedString(eventJson);
		String result = BPUtility.getDecodedString(JobSchedulingCtrl.loadSchedulingEvents(eventJson));
		List<List<JobSchedulingWrapper>> allEventList = (List<List<JobSchedulingWrapper>>)json.deserialize(result, List<List<JobSchedulingWrapper>>.class);
		system.assertEquals(2, allEventList.size());
		Test.stopTest();
	}
	
	@isTest
	private static void testSaveJobSchedulingEvent(){
		Test.startTest();
		Event event = [SELECT Id, Title__c, Notes__c, AdditionalNotes__c, Subject, Type, WhatId, IsMultiDayEvent__c, StartDateTime, EndDateTime FROM Event LIMIT 1];
		JobSchedulingWrapper jobSchedulingWrapper = new JobSchedulingWrapper(event);
		String eventJson = json.serialize(jobSchedulingWrapper);
		eventJson = BPUtility.getEncodedString(eventJson);
		String result = BPUtility.getDecodedString(JobSchedulingCtrl.saveJobSchedulingEvent(eventJson));
		List<JobSchedulingWrapper> allEventList = (List<JobSchedulingWrapper>)json.deserialize(result, List<JobSchedulingWrapper>.class);
		system.assertEquals('Meeting', allEventList[0].Subject);
		Test.stopTest();
	}
	
	@isTest
	private static void testDeleteJobSchedulingEvent(){
		Test.startTest();
		Event event = [SELECT Id, Title__c, Notes__c, AdditionalNotes__c, Subject, Type, WhatId, IsMultiDayEvent__c, StartDateTime, EndDateTime FROM Event LIMIT 1];
		JobSchedulingWrapper jobSchedulingWrapper = new JobSchedulingWrapper(event);
		String eventJson = json.serialize(jobSchedulingWrapper);
		eventJson = BPUtility.getEncodedString(eventJson);
		String result = BPUtility.getDecodedString(JobSchedulingCtrl.deleteJobSchedulingEvent(BPUtility.getEncodedString(event.Id),eventJson));
		List<JobSchedulingWrapper> allEventList = (List<JobSchedulingWrapper>)json.deserialize(result, List<JobSchedulingWrapper>.class);
		system.assertEquals(0, allEventList.size());
		
		Test.stopTest();
	}
	
	@isTest
	private static void testAddServiceJobForJobScheduling(){
		Test.startTest();
		CO_Header__c coHeaderRec = [SELECT Id FROM CO_Header__c LIMIT 1];
		Event event = [SELECT Id, Title__c, Notes__c, AdditionalNotes__c, Subject, Type, WhatId, IsMultiDayEvent__c, StartDateTime, EndDateTime FROM Event LIMIT 1];
		JobSchedulingWrapper jobSchedulingWrapper = new JobSchedulingWrapper(event);
		jobSchedulingWrapper.COHeaderId = coHeaderRec.Id;
		String eventJson = json.serialize(jobSchedulingWrapper);
		eventJson = BPUtility.getEncodedString(eventJson);
		JobSchedulingCtrl.addServiceJobForJobScheduling(eventJSON);
		Event eventRec = [SELECT WhatId FROM Event LIMIT 1];
		system.assertEquals(eventRec.WhatId, jobSchedulingWrapper.COHeaderId);
		Test.stopTest();
	}
	
	@isTest
	private static void testGetServiceJobDetailsForForJobScheduling(){
		Test.startTest();
		CO_Header__c coHeaderRec = [SELECT Id FROM CO_Header__c LIMIT 1];
		String resultJSON = BPUTility.getDecodedString(JobSchedulingCtrl.getServiceJobDetailsForForJobScheduling(BPUtility.getEncodedString(coHeaderRec.Id)));
		JobSchedulingWrapper.COHeaderWrapper result = (JobSchedulingWrapper.COHeaderWrapper)json.deserialize(resultJSON, JobSchedulingWrapper.COHeaderWrapper.class);
		system.assertEquals('Test001', result.CustomerName);
		Test.stopTest();
	}
}