Blackpurl/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/CO_Header__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CO Headers</relationshipLabel>
        <relationshipName>CO_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Formatted_Name__c</fullName>
        <formula>IF( NOT(ISBLANK(Unit_Make__c)), Unit_Make__r.Name, &apos;&apos;) &amp; 
IF( NOT(ISBLANK(Unit_Model__c)), &apos; &apos; &amp; Unit_Model__r.Name__c, &apos;&apos;) &amp; 
IF( NOT(ISBLANK(Sub_Model__r.Sub_Model_Name__c)), &apos; &apos; &amp; Sub_Model__r.Sub_Model_Name__c, &apos;&apos;) &amp; 
IF( NOT(ISNULL(Year__c)), &apos; &apos; &amp; TEXT(Year__c), &apos;&apos;) &amp; 
IF( NOT(ISBLANK(Colour__c)), &apos;, &apos; &amp; Colour__c, &apos;&apos;)</formula>
        <label>Formatted Name</label>
        <type>Text</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Service_Order_Header__c.object
<CustomObject>
    <description>Object used to handle service related section on Customer order header</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Hours__c</fullName>
        <label>Estimated Hours</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Type</label>
        <referenceTo>Transaction_Type__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Order Header</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Technician__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Technician</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Technician</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Technician Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Transaction_Type__c.object
<CustomObject>
    <description>Object used in SO related functionlaity</description>
    <fields>
        <fullName>Code_Label__c</fullName>
        <label>Code Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is what controls the behavior of a service section and who is being billed for the service work.  There are only three possible settings for this</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Third-Party</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Deal Service</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Stock Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Type</label>
    <nameField>
        <displayFormat>TTN-{00000000}</displayFormat>
        <label>Transaction Type Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/classes/JobSchedulerServiceTest.cls
@isTest
private class JobSchedulerServiceTest {
    @testsetup
    private static void setup(){
    	Account customerRec = TestDataFactory.createCustomer('Test001', 'Individual', 'Fname', 'Lname');
		Customer_Owned_Unit__c unitRec = TestDataFactory.createCustomerOwnedUnit(customerRec.Id, 'VIN001');
		Event eventRec1 = TestDataFactory.createEventForAfternoon(customerRec.Id, unitRec.Id);
		eventRec1.Type = 'Appointment';
		eventRec1.StartDateTime = HomeSearchFilterInterface.getDateFromString('12/03/1997');
		update eventRec1;
		Event eventRec2 = TestDataFactory.createEventForAfternoon(customerRec.Id, unitRec.Id);
    }
    
    @isTest
    private static void testGetTechnicianListForSpecificDay(){
    	Test.startTest();
		List<TechnicianDetailWrapper> technicianDetailWrapperList = new List<TechnicianDetailWrapper>(JobSchedulerService.getTechnicianListForSpecificDay('12/03/1997'));
		system.assertEquals(technicianDetailWrapperList.size(), 0);
    	Test.stopTest();
    }
    
    @isTest
    private static void testUpdateAppointment(){
    	Test.startTest();
    	List<Event> eventRec = new List<Event>([SELECT Id, Customer__c, Event_Concern__c, Customer_Owned_Unit__c, Estimated_Hours__c, Transaction_Type__r.Code_Label__c, Transaction_Type__c, Transaction_Type__r.Type__c, Subject, Technician__c, Customer__r.Name, Service_Order_Header__c, EndDateTime,Appointment_Concern__c, Customer_Owned_Unit__r.Formatted_Name__c, Appointment_Day_Segment__c, CO_Header__r.Name, StartDateTime FROM Event WHERE Appointment_Day_Segment__c = 'Afternoon']);
    	eventRec[0].StartDateTime = HomeSearchFilterInterface.getDateFromString('12/03/1997');
    	update eventRec;
    	AppointmentWrapper appWrapper1 = new AppointmentWrapper(eventRec[0], true);
    	AppointmentWrapper appWrapper2 = new AppointmentWrapper(eventRec[1], true);
    	List<AppointmentWrapper> appointmentWrapperList = new List<AppointmentWrapper>();
    	appointmentWrapperList.add(appWrapper1);
    	appointmentWrapperList.add(appWrapper2);
    	String appointmentObjStr = json.serialize(appointmentWrapperList);
    	JobSchedulerService.updateAppointment(appointmentObjStr);
    	List<Event> eventRecUpdated = new List<Event>([SELECT Id, Customer__c, Event_Concern__c, Customer_Owned_Unit__c, Estimated_Hours__c, Transaction_Type__r.Code_Label__c, Transaction_Type__c, Transaction_Type__r.Type__c, Subject, Technician__c, Customer__r.Name, Service_Order_Header__c, EndDateTime,Appointment_Concern__c, Customer_Owned_Unit__r.Formatted_Name__c, Appointment_Day_Segment__c, CO_Header__r.Name, StartDateTime FROM Event WHERE Appointment_Day_Segment__c = 'Afternoon']);
    	system.assertEquals(eventRecUpdated[0].Subject, 'Test Event');
    	Test.stopTest();
    }
    
    @isTest
    private static void testGetUnassignedAppointmentForSpecificDay(){
    	Test.startTest();
    	List<AppointmentWrapper> appointmentWrapperList = new List<AppointmentWrapper>(JobSchedulerService.getUnassignedAppointmentForSpecificDay('12/03/1997'));
    	system.assertEquals(appointmentWrapperList.size(), 1);
    	Test.stopTest();
    }
    
    @isTest
    private static void testCreateCOWithServiceJob(){
    	Test.startTest();
    	Account customer = [SELECT Id FROM Account LIMIT 1];
    	List<Event> eventRec = new List<Event>([SELECT Id, Customer__c, Event_Concern__c, Customer_Owned_Unit__c, Estimated_Hours__c, Transaction_Type__r.Code_Label__c, Transaction_Type__c, Transaction_Type__r.Type__c, Subject, Technician__c, Customer__r.Name, Service_Order_Header__c, EndDateTime,Appointment_Concern__c, Customer_Owned_Unit__r.Formatted_Name__c, Appointment_Day_Segment__c, CO_Header__r.Name, StartDateTime FROM Event WHERE Appointment_Day_Segment__c = 'Afternoon']);
    	eventRec[0].CO_Header__c = null;
    	update eventRec;
    	AppointmentWrapper appWrapper = new AppointmentWrapper(eventRec[0], true);
    	String appointmentObjStr = json.serialize(appWrapper);
    	Id result = (Id)JobSchedulerService.createCOWithServiceJob(appointmentObjStr);
    	system.assertEquals(true, result.getSObjectType().getDescribe().getName().contains('CO_Header__c'));
    	Test.stopTest();
    }
		
	@isTest
	private static void testGetAssignedAppointmentForSpecificDay(){
		Test.startTest();
		Technician__c technician = TestDataFactory.createTechnician();
		Map<String, List<AppointmentWrapper>> result = new Map<String, List<AppointmentWrapper>>(JobSchedulerService.getAssignedAppointmentForSpecificDay('12/03/1997', technician.Id));
		system.assertEquals(result.size(), 0);
		Test.stopTest();
	}  
}