Blackpurl/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <description>General customer notes</description>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Active__c = TRUE, &apos;Active&apos; , &apos;InActive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/CO_Header__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CO Headers</relationshipLabel>
        <relationshipName>CO_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SO_Worksheet_User_selection__c</fullName>
        <label>SO Worksheet User selection</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Order_status__c)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/CO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form_Label__c</fullName>
        <formula>IF( Part__c != null, Part__r.Applicable_Tax__r.Forms_Label__c, IF( Fee__c != null, Fee__r.Applicable_Tax__r.Forms_Label__c, &apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Form Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Stock</fullName>
                </value>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CO Line Item</label>
    <nameField>
        <displayFormat>COLI-{00000000}</displayFormat>
        <label>CO Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <description>General unit notes</description>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of unit based on unit type</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Traded</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/CustomerApproval__c.object
<CustomObject>
    <description>Object to hold approval from customer for their service Orders</description>
    <fields>
        <fullName>ApprovalDetailJson__c</fullName>
        <label>ApprovalDetailJson</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ApprovalType__c</fullName>
        <label>ApprovalType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Count__c</fullName>
        <label>Approval Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Section_Name__c</fullName>
        <label>Section Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_key__c</fullName>
        <label>Section key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Header</label>
        <referenceTo>Service_Order_Header__c</referenceTo>
        <relationshipLabel>CustomerApprovals</relationshipLabel>
        <relationshipName>CustomerApprovals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CustomerApproval</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>CustomerApproval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CustomerApprovals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Individual_Tax__c.object
<CustomObject>
    <fields>
        <fullName>CO_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Line Item</label>
        <referenceTo>CO_Line_Item__c</referenceTo>
        <relationshipLabel>Individual Taxes</relationshipLabel>
        <relationshipName>Individual_Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form_Label__c</fullName>
        <formula>If( 
	CO_Line_Item__c != null, 
	CO_Line_Item__r.Applicable_Tax__r.Forms_Label__c, 
	IF(
		Service_Order_Line_Item__c != null,
		Service_Order_Line_Item__r.Applicable_Tax__r.Forms_Label__c,
		IF(
			Option_Fee__c != null,
			Option_Fee__r.Applicable_Tax__r.Forms_Label__c,
			IF(
				Deal_Unit_Price_Cost__c != null,
				Deal_Unit_Price_Cost__r.Applicable_Tax__r.Forms_Label__c,
				IF(
					Deal_Item__c != null,
					Deal_Item__r.Applicable_Tax__r.Forms_Label__c,
                    IF(
						F_I_Product__c != null,
						F_I_Product__r.Applicable_Tax__r.Forms_Label__c,
					null
				)
			)
		)
	)
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Form Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Item_Name__c</fullName>
        <label>Sales Tax Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Header</label>
        <referenceTo>Service_Order_Header__c</referenceTo>
        <relationshipLabel>Individual Taxes</relationshipLabel>
        <relationshipName>Individual_Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Individual Tax</label>
    <nameField>
        <displayFormat>ITN-{00000000}</displayFormat>
        <label>Individual Tax Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Service_Order_Header__c.object
<CustomObject>
    <description>Object used to handle service related section on Customer order header</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Order Header</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Service_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CO_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Line Item</label>
        <referenceTo>CO_Line_Item__c</referenceTo>
        <relationshipLabel>Service Order Line Items</relationshipLabel>
        <relationshipName>Service_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form_Label__c</fullName>
        <formula>IF( Part__c != null, Part__r.Applicable_Tax__r.Forms_Label__c, IF( Fee__c != null, Fee__r.Applicable_Tax__r.Forms_Label__c, IF( Labour_Code__c != null, Labour_Code__r.Applicable_Tax__r.Forms_Label__c, &apos;&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Form Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Header</label>
        <referenceTo>Service_Order_Header__c</referenceTo>
        <relationshipLabel>Service Order Line Items</relationshipLabel>
        <relationshipName>Service_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of service job line item</description>
        <label>Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Service Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{00000000}</displayFormat>
        <label>Service Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/classes/ServiceWorkSheetCtrl.cls
/**
* Author: Nidhi Sharma
* Since: September 24, 2016
* Name: SOWorkSheetWrapper
* Description: Wrapper class to handle JSON variables for SO worksheet. Created for ticket #129
**/
global with sharing class ServiceWorkSheetCtrl {
    
    public static String Application{get;}
    public static String Assests{get;}
    public static String Application_Images{get;}
    public String coHeaderId {get; private set;}
    public String customerApprovalId {get; private set;}
    public SOWorkSheetWrapper soWorkSheetObj {get; private set;}
    public CustomerApproval customerApprovalObj {get; private set;}
    
    public ServiceWorkSheetCtrl() {
    	Application = GlobalController.GetResourceURL('Application');
    	Application_Images = GlobalController.GetResourceURL('Application_Images');
    	Assests = GlobalController.GetResourceURL('Assests');
    	getPDFDetail();
    }
    
    public void getPDFDetail() {
        coHeaderId = ApexPages.currentPage().getParameters().get('id');
        customerApprovalId = ApexPages.currentPage().getParameters().get('customerApprovalId') != null ? ApexPages.currentPage().getParameters().get('customerApprovalId') : '';
    	if(String.isNotBlank(customerApprovalId)) {
        	String worksheetData = BPUtility.getDecodedString(getCustomerApprovalRec(BPUtility.getEncodedString(customerApprovalId)));
        	customerApprovalObj = (CustomerApproval)System.JSON.deserialize(worksheetData, CustomerApproval.class);
        	soWorkSheetObj = (SOWorkSheetWrapper)System.JSON.deserialize(customerApprovalObj.ApprovalDetailJson, SOWorkSheetWrapper.class);
        } else {
        	soWorkSheetObj = getSOHeaderData(coHeaderId);	
        }
    }
    
	@RemoteAction
    global static String saveCustomerApproval(String customerApprovalObj, String soHeaderIds) {
    	customerApprovalObj = BPUtility.getDecodedString(customerApprovalObj);
    	soHeaderIds = BPUtility.getDecodedString(soHeaderIds);
        return ServiceJobService.saveCustomerApproval(customerApprovalObj, soHeaderIds); 
    } 
	
    @RemoteAction
    global static String getServiceWorkSheetData(String coHeaderId) {
    	coHeaderId = BPUtility.getDecodedString(coHeaderId);
    	SOWorkSheetWrapper soWorkSheetWrapperObj = getSOHeaderData(coHeaderId);
    	
    	return BPUtility.getEncodedString(JSON.serialize(soWorkSheetWrapperObj));
    }
    
    @RemoteAction
    global static String getCustomerApprovalRec(String customerApprovalId) {
    	customerApprovalId = BPUtility.getDecodedString(customerApprovalId);
    	getCustomerApprovalJSONById(customerApprovalId);
    	List<CustomerApproval__c> customerApprovalList = [select Approval_Count__c, ApprovalDetailJson__c, ApprovalType__c, Notes__c, Section_key__c, Name, LastModifiedDate,
                                                Section_Name__c, Service_Order_Header__c, Status__c, (Select Id from Attachments) from CustomerApproval__c where Id=: customerApprovalId];
    	if(customerApprovalList.size() > 0) {
    		return BPUtility.getEncodedString(JSON.serialize(new CustomerApproval(customerApprovalList[0])));
    	}
    	return BPUtility.getEncodedString('');
    }
    
    private static String getCustomerApprovalJSONById(String customerApprovalId) {
    	List<CustomerApproval__c> customerApprovalList = [select ApprovalDetailJson__c from CustomerApproval__c where Id=: customerApprovalId];
    	if(customerApprovalList.size() > 0) {
    		return customerApprovalList[0].ApprovalDetailJson__c;	
    	}
    	return '';
    }
    private static SOWorkSheetWrapper getSOHeaderData(String coHeaderId) {
        if(AccessControl.ifObjectFieldIsAccessible('CO_Header__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        List<CO_Header__c> coHeaderList = [select Name, Status__c, Customer__c, SO_Worksheet_User_selection__c from CO_Header__c where Id=: coHeaderId];
        if(coHeaderList.size() == 0) {
            return null;
        }
        String jsonString = coHeaderList[0].SO_Worksheet_User_selection__c; 
        
        List<SOWorkSheetWrapper.ServiceWorkSheetPrintDetail> soPrintDetailListObj = 
                    (List<SOWorkSheetWrapper.ServiceWorkSheetPrintDetail>) System.JSON.deserialize(jsonString, List<SOWorkSheetWrapper.ServiceWorkSheetPrintDetail>.class);
        
        Set<Id> soHeaderIdSet = new Set<Id>();
        Set<Id> unitIdSet = new Set<Id>();
        Boolean isPrintPreview = false; 
        for(SOWorkSheetWrapper.ServiceWorkSheetPrintDetail printDetailObj : soPrintDetailListObj) {
            if(printDetailObj.IsUnitSelected) {
                unitIdSet.add(printDetailObj.UnitId);
                for(SOWorkSheetWrapper.SOInfoWrapper soInfoObj : printDetailObj.SOInfoWrapperList) {  
                    if(soInfoObj.IsSOHeaderSelected) {
                        soHeaderIdSet.add(soInfoObj.SOHeaderId);
                    }
                }
            }
            isPrintPreview = printDetailObj.IsPrintPreview;
        }
        
        List<Account> customerList = new List<Account>();
        List<Service_Order_Header__c> soHeaderList = SOQLUtil.getSODetailsByFieldName(new Map<String, String>{'CO_Header__c' => coHeaderId});
        List<Service_Order_Header__c> soHeaderRecList = new List<Service_Order_Header__c>();
        for(Service_Order_Header__c soHeaderRec : soHeaderList) {
            if(soHeaderIdSet.contains(soHeaderRec.Id)) {
                soHeaderRecList.add(soHeaderRec);
            }
        }
        List<Customer_Owned_Unit__c> unitList = SOQLUtil.getUnitDetails(unitIdSet);
        List<Business_Profile__c> businessProfileList = SOQLUtil.getBusinessProfileData(new List<id>());
        if(soHeaderList.size() > 0 && coHeaderList[0].Customer__c != null) {
            customerList = SOQLUtil.getCustomerDetailsByFieldName(new Map<String, String>{'Id' => coHeaderList[0].Customer__c});
        } 
        
        List<Individual_Tax__c> individualItemsList = [select CO_Line_Item__c, Tax_Rate__c, Form_Label__c, Sales_Tax_Item_Name__c, 
                                                                Taxable_Amount__c, Tax_Amount__c,
                                                                Applicable_Tax__c, List_Tax_items_on_forms__c
                                                                    from Individual_Tax__c 
                                                                    where Service_Order_Line_Item__r.Service_Order_Header__c IN :soHeaderIdSet];
        
        Map<String, Decimal> salesTaxNameToTaxValue = new Map<String, Decimal>();  
        salesTaxNameToTaxValue = TaxCalculation.getTaxAmountWithFormLabel(individualItemsList); 
                
        SOWorkSheetWrapper soWorkSheetWrapperObj = new SOWorkSheetWrapper(unitList, soHeaderRecList, 
                                                                    businessProfileList, customerList, 
                                                                    coHeaderList[0], isPrintPreview,
                                                                    salesTaxNameToTaxValue);
        return soWorkSheetWrapperObj;
    }
}