Blackpurl/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Level</label>
        <referenceTo>Price_Level__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Applicable_Taxes__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Tax_Item__c</fullName>
        <label>Sales Tax Item</label>
        <referenceTo>Sales_Tax_Item__c</referenceTo>
        <relationshipLabel>Applicable Taxes</relationshipLabel>
        <relationshipName>Applicable_Taxes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Applicable Taxes</relationshipLabel>
        <relationshipName>Applicable_Taxes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Applicable Taxes</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Applicable Taxes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicable Taxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Internal Expense</fullName>
                </value>
                <value>
                    <fullName>Labour</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Part</fullName>
                </value>
                <value>
                    <fullName>Sublet</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
                <value>
                    <fullName>Trade-in</fullName>
                </value>
                <value>
                    <fullName>Stamp Duty</fullName>
                </value>
                <value>
                    <fullName>Deductible</fullName>
                </value>
                <value>
                    <fullName>Stocked Trade</fullName>
                </value>
                <value>
                    <fullName>Lien Payout</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/CO_Header__c.object
<CustomObject>
    <fields>
        <fullName>CO_Type__c</fullName>
        <description>Customer order types</description>
        <label>CO Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Cash Sale</fullName>
                </value>
                <value>
                    <fullName>Internal Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CO Headers</relationshipLabel>
        <relationshipName>CO_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Category assigned to the unit</description>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Deal__c.object
<CustomObject>
    <description>Unit Deal on Customer Order</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Order</description>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of deal</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Deal</fullName>
                </value>
                <value>
                    <fullName>Financed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Deal_Item__c.object
<CustomObject>
    <description>Junction between deal and unit</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trade In</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Deal Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Price_Level__c.object
<CustomObject>
    <fields>
        <fullName>Labour_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Labour Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price Level</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Sales_Tax_Item__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Sales Tax Items</relationshipLabel>
        <relationshipName>Sales_Tax_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Tax Item</label>
    <nameField>
        <displayFormat>STI-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Tax Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Tax_Exemption__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Tax Exemptions</relationshipLabel>
        <relationshipName>Tax_Exemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tax Exemptions</relationshipLabel>
        <relationshipName>Tax_Exemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax Item</label>
        <referenceTo>Sales_Tax_Item__c</referenceTo>
        <relationshipLabel>Tax Exemptions</relationshipLabel>
        <relationshipName>Tax_Exemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tax Exemption</label>
    <nameField>
        <displayFormat>TE-{00000000}</displayFormat>
        <label>Tax Exemption Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Exemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Unit_Model__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Unit Models</relationshipLabel>
        <relationshipName>Unit_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Model</label>
    <nameField>
        <displayFormat>UM-{0000000}</displayFormat>
        <label>Unit Model Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Unit_Price_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Base unit, Factory options, Dealer installed options</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Factory</fullName>
                </value>
                <value>
                    <fullName>Dealer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit Price &amp; Cost</label>
    <nameField>
        <displayFormat>UNP-{00000000}</displayFormat>
        <label>Unit Price &amp; Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Prices &amp; Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/classes/DealUnitPriceAndCostTriggerTest.cls
/**
 * Author: Nidhi Sharma
 * updated: Dec 20, 2016
 * Name: DealUnitPriceAndCostTriggerTest
 * Description: Test class for option and feee trigger
**/
@isTest
private class DealUnitPriceAndCostTriggerTest {

    static testMethod void dealUnitPriceAndCostTriggerTest() {
        Category__c testCategory = TestUtil.createCategory(true, 'Test Category');
        Price_Level__c defaultPriceLevel = TestUtil.createPriceLevel(false, 'Default Price Level', 'MSRP', 10 , true, true);
        defaultPriceLevel.Labour_Rate__c = 60 ;
        Insert defaultPriceLevel;
        Sales_Tax__c salestax =  TestUtil.createSalesTax(true, 'HST');
        
        Sales_Tax_Item__c salesTaxItem = TestUtil.createSalesTaxItem(true, 'Test Item', 8.0, 'Testing ', true, testCategory.Id);
        Sales_Tax_Item__c salesTaxItem1 = TestUtil.createSalesTaxItem(true, 'Test Item1', 10.0, 'Testing1 ', true, testCategory.Id);
        
        Applicable_Taxes__c applicabletax = TestUtil.createApplicableTax(true, salestax.Id, salesTaxItem.Id);
        Applicable_Taxes__c applicabletax1 = TestUtil.createApplicableTax(true, salestax.Id, salesTaxItem1.Id);
        
        Account customer =  TestUtil.createCustomer(false, 'customerName', 'abc@abc.com', 'jaipur', '1111111111', null, null, false, true,'Individual');
        customer.Is_Customer__c = true;
        insert customer;
        String statusToUpdate = 'In Progress';
        CO_Header__c co = new CO_Header__c(CO_Type__c='Customer', Selling_Group__c='Unit Deal', Customer__c=customer.Id);
        insert co;
        Tax_Exemption__c taxExemption = Testutil.createCOTaxExemption(true, co.Id, salestaxItem.Id);
        DealWrapper dealWrapperObj = (DealWrapper)Json.deserialize(BPUtility.getDecodedString(CustomerOrderCtrl.createDeal(BPUtility.getEncodedString(co.Id))),DealWrapper.class);
        Unit_Make__c unitmake = TestUtil.createUnitMake(true, 'unitMakeName', '12A', true);
        Unit_Model__c unitmodel = TestUtil.createUnitModel(true, 'unitModelName', '12A', true, unitMake.Id);
        Customer_Owned_Unit__c customerOwnedUnit = TestUtil.createCustomerOwnedUnit(false, customer.Id, UnitMake.Id, UnitModel.Id, null);
        customerOwnedUnit.Taxable__c = true;
        customerOwnedUnit.Applicable_Tax__c = salestax.Id;
        insert customerOwnedUnit;
        Unit_Price_Cost__c unitPriceAndCost1 = new Unit_Price_Cost__c(Customer_Owned_Unit__c = customerOwnedUnit.Id, Type__c = 'Factory', Cost__c = 3000);
        Unit_Price_Cost__c unitPriceAndCost2 = new Unit_Price_Cost__c(Customer_Owned_Unit__c = customerOwnedUnit.Id, Type__c = 'Dealer', Cost__c = 3555);
        insert new List<Unit_Price_Cost__c>{unitPriceAndCost1, unitPriceAndCost2};
        
        Deal_Item__c dealItemRec = new Deal_Item__c(Colour__c='Red',Year__c=2016); 
        DealItem dealItemObj = new DealItem(dealItemRec);
        dealItemObj.Model = unitmodel.Id;
        String dealItemJsonToSave = System.JSON.serialize(dealItemObj);
        Test.startTest();
        List<Deal__c> dealList = [Select id from Deal__c where CO_Header__c = :co.Id];
        String dealItemJson = BPUtility.getDecodedString(CustomerOrderCtrl.saveTemporaryUnit(BPUtility.getEncodedString(dealList[0].Id),BPUtility.getEncodedString(dealItemJsonToSave)));
        
        dealWrapperObj = (DealWrapper)Json.deserialize(dealItemJson, DealWrapper.class);
        dealWrapperObj = (DealWrapper)Json.deserialize(BPUtility.getDecodedString(CustomerOrderCtrl.addUnitToDeal(BPUtility.getEncodedString(dealWrapperObj.UnitList[0].DealItemObj.Id),BPUtility.getEncodedString(customerOwnedUnit.Id),BPUtility.getEncodedString(dealWrapperObj.DealInfo.Id))), DealWrapper.class);
        
        Test.stopTest();
        system.assertEquals(2, dealWrapperObj.UnitList.size());
        system.assertEquals(10, dealWrapperObj.UnitList[0].FactoryOptionList[0].SalesTaxPercentage);
    }
    
    static testMethod void dealDeleteTriggerTest() {
        Account customer =  TestUtil.createCustomer(false, 'customerName', 'abc@abc.com', 'jaipur', '1111111111', null, null, false, true,'Individual');
        customer.Is_Customer__c = true;
        insert customer;
        
        CO_Header__c co = new CO_Header__c(CO_Type__c='Customer', Selling_Group__c='Unit Deal', Customer__c=customer.Id);
        insert co;
        Unit_Make__c unitmake = TestUtil.createUnitMake(true, 'unitMakeName', '12A', true);
        Unit_Model__c unitmodel = TestUtil.createUnitModel(true, 'unitModelName', '12A', true, unitMake.Id);
        CustomerOrderCtrl.createDeal(BPUtility.getEncodedString(co.Id));
        system.assertEquals(co.CO_Type__c,'Customer');
        List<Deal__c> dealList = [Select id from Deal__c where CO_Header__c = :co.Id];
        Deal_Item__c dealItemRec = new Deal_Item__c(Colour__c='Red',Year__c=2016); 
        DealItem dealItemObj = new DealItem(dealItemRec);
        dealItemObj.Model = unitmodel.Id;
        String dealItemJsonToSave = System.JSON.serialize(dealItemObj);
        delete dealList[0];
    }
    
    static testMethod void dealItemDeleteTriggerTest() {
        Account customer =  TestUtil.createCustomer(false, 'customerName', 'abc@abc.com', 'jaipur', '1111111111', null, null, false, true,'Individual');
        customer.Is_Customer__c = true;
        insert customer;
        
        CO_Header__c co = new CO_Header__c(CO_Type__c='Customer', Selling_Group__c='Unit Deal', Customer__c=customer.Id);
        insert co;
        Unit_Make__c unitmake = TestUtil.createUnitMake(true, 'unitMakeName', '12A', true);
        Unit_Model__c unitmodel = TestUtil.createUnitModel(true, 'unitModelName', '12A', true, unitMake.Id);
        Category__c categoryObj = testUtil.createCategory(true,'category one');
        Sales_Tax__c salesTax1 = TestUtil.createSalesTax(true, 'Testing Sales Tax 2', true, false, true);
        Sales_Tax_Item__c salesTaxItem1 = TestUtil.createSalesTaxItem(true, 'Test Sales Tax Item 1', 20, 'Testing Form Label 1', true, categoryObj.id);
        Tax_Exemption__c taxExemptionObj = TestUtil.createCOTaxExemption(true,co.id,salesTaxItem1.id);
        
        Configurations__c taxSetting = Configurations__c.getOrgDefaults();
        taxSetting.Default_Tax_on_Fee__c = salesTax1.Id;
        taxSetting.Default_Tax_on_Labor__c = salesTax1.Id;
        taxSetting.Default_Tax_on_Part__c = salesTax1.Id;
        taxSetting.Default_Tax_on_Vendor_Product__c = salesTax1.Id; 
        taxSetting.Default_Tax_on_Unit__c = salesTax1.Id;
        taxSetting.Tax_Included_Pricing__c = true;
        insert taxSetting;
       
        Applicable_Taxes__c applicableTax1 = TestUtil.createApplicableTax(true, salesTax1.Id, salesTaxItem1.Id);
        Applicable_Taxes__c applicableTax2 = TestUtil.createApplicableTax(true, salesTax1.Id, salesTaxItem1.Id);
        
        CustomerOrderCtrl.createDeal(BPUtility.getEncodedString(co.Id));
        List<Deal__c> dealList = [Select id from Deal__c where CO_Header__c = :co.Id];
        
        Deal_Item__c dealItemRec = new Deal_Item__c(Colour__c='Red',Year__c=2016); 
    	dealItemRec.Unit_Model__c = unitmodel.Id;
    	dealItemRec.Deal__c = dealList[0].Id;
    	dealItemRec.Type__c = Constants.DEAL_ITEM_TYPE_UNIT;
    	insert dealItemRec;
    	
    	Deal_Item__c dealItemRec2 = new Deal_Item__c(Colour__c='Red',Year__c=2016); 
    	dealItemRec2.Unit_Model__c = unitmodel.Id;
    	dealItemRec2.Deal__c = dealList[0].Id;
    	dealItemRec2.Type__c = Constants.DEAL_ITEM_TYPE_UNIT;
    	insert dealItemRec2;
    	
    	Deal_Item__c dealItemRec3 = new Deal_Item__c(Colour__c='Red',Year__c=2016); 
    	dealItemRec3.Unit_Model__c = unitmodel.Id;
    	dealItemRec3.Deal__c = dealList[0].Id;
    	dealItemRec3.Type__c = Constants.DEAL_ITEM_TYPE_TRADE_IN;
    	insert dealItemRec3;
    	//system.assertEquals(1,dealList.size());
        
        delete dealItemRec;
        system.assert(true,true);
    }
}