Blackpurl/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Average_Spend_per_Order__c</fullName>
        <label>Average Spend per Order</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Open_Orders__c</fullName>
        <label>Open Orders</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Orders_Lifetime__c</fullName>
        <label>Orders Lifetime</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Blackpurl/src/objects/Applicable_Taxes__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Tax_Item__c</fullName>
        <label>Sales Tax Item</label>
        <referenceTo>Sales_Tax_Item__c</referenceTo>
        <relationshipLabel>Applicable Taxes</relationshipLabel>
        <relationshipName>Applicable_Taxes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Applicable Taxes</relationshipLabel>
        <relationshipName>Applicable_Taxes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Applicable Taxes</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Applicable Taxes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicable Taxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Business_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Business_City__c</fullName>
        <label>Business City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Business Profiles</relationshipLabel>
        <relationshipName>Business_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Email__c</fullName>
        <label>Business Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Phone__c</fullName>
        <label>Business Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Business_Postal_Code__c</fullName>
        <label>Business Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Business Profiles</relationshipLabel>
        <relationshipName>Business_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Street_Address1__c</fullName>
        <label>Business Street Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Street_Address2__c</fullName>
        <label>Business Street Address2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Business_Number__c</fullName>
        <formula>IF(Business_Phone__c != null, 
IF( Business_Country__c != null , 
IF( Business_Country__r.Name__c  == &apos;Australia&apos;, 
CASE( LEN(Business_Phone__c) , 
8 , MID(Business_Phone__c, 0, 4) + &quot; &quot; +MID(Business_Phone__c, 5, 4) , 
10 , IF(BEGINS(Business_Phone__c, &apos;04&apos;) || BEGINS(Business_Phone__c, &apos;05&apos;) , 
MID(Business_Phone__c, 0, 4) + &quot; &quot; +MID(Business_Phone__c, 5, 3)+ &quot; &quot; +MID(Business_Phone__c, 8, 3), 
MID(Business_Phone__c, 0, 2) + &quot; &quot; +MID(Business_Phone__c, 3, 4)+ &quot; &quot; +MID(Business_Phone__c, 7, 4)) 
, Business_Phone__c ), 


CASE( LEN(Business_Phone__c) , 10, &quot;(&quot; + MID(Business_Phone__c, 0, 3) + &quot;) &quot; +MID(Business_Phone__c, 4, 3) 
+ &quot;-&quot; +MID(Business_Phone__c, 7, 4) , Business_Phone__c)) 
, 
CASE( LEN(Business_Phone__c) , 8 , MID(Business_Phone__c, 0, 4) + &quot; &quot; +MID(Business_Phone__c, 4, 4) , 
10, &quot;(&quot; + MID(Business_Phone__c, 0, 3) + &quot;) &quot; +MID(Business_Phone__c, 4, 3) 
+ &quot;-&quot; +MID(Business_Phone__c, 7, 4) , Business_Phone__c)), 
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Business Number</label>
        <type>Text</type>
    </fields>
    <label>Business Profile</label>
    <nameField>
        <displayFormat>BPN-{000000}</displayFormat>
        <label>Business Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/CO_Invoice_Header__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Invoice Headers</relationshipLabel>
        <relationshipName>CO_Invoice_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CO Invoice Header</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>CO Invoice Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <label>Tax Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configurations</label>
</CustomObject>

Blackpurl/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Message_History__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text Message</fullName>
                </value>
                <value>
                    <fullName>Emailed Invoice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sent_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sent By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sent_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sent To</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Message History</label>
    <nameField>
        <displayFormat>MSG-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Sales_Tax__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Sales_Tax_Item__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Tax Item</label>
    <nameField>
        <displayFormat>STI-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Tax Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>State/Province</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Store_Credit__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Store Credits</relationshipLabel>
        <relationshipName>Store_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Store Credit</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Store Credit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Tax_Exemption__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Tax Exemptions</relationshipLabel>
        <relationshipName>Tax_Exemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax Item</label>
        <referenceTo>Sales_Tax_Item__c</referenceTo>
        <relationshipLabel>Tax Exemptions</relationshipLabel>
        <relationshipName>Tax_Exemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tax Exemption</label>
    <nameField>
        <displayFormat>TE-{00000000}</displayFormat>
        <label>Tax Exemption Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Exemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/classes/CustomerDetail.cls
/**
 * Author: Tarun Khandelwal
 * Since: June 05, 2015
 * Name: CustomerDetail
 * Description: Apex class to handle JSON related oprations of Customer Detail Page.
**/
public with sharing class CustomerDetail {
    
    public Customer CustomerInfo {get; set;}
    
    // open orders
    public Decimal OpenOrders;
    
    // Average Life Time
    public Decimal OrdersLifetime;
    
    // Average Spend per Hours
    public Decimal AverageSpendPerHour;
    
    // Last Visited Order Time
    public String LastVisit;
    
    // Related Customer
    public Integer TotalCustomerRecords;
    public List<RelatedCustomer> RelatedCustomerList;
    
    // COU list
    public Integer TotalCOURecords;
    public List<CustomerOwnedUnit> CustomerOwnedUnitList;
    
    // Contacts List
    public Integer TotalContactRecords;
    public List<CustomerContact> ContactList;
    
    // Active Orders
    public Integer TotalActiveOrderRecords;
    public List<ActiveOrder> ActiveOrderList;
    
    // Active Sales Order (Customer Header)
    public Integer TotalActiveSalesOrderRecords;
    public List<ActiveSalesOrder> ActiveSalesOrderList;
    
    // Tax Exemptions
    public Integer TotalTaxExemptionRecords;
    public List<TaxExemptions> TaxExemptionList;
    
    
    public Integer TotalStoreCreditRecords;
    public List<StoreCredit> StoreCreditList;
    
    public Company CompanyName; 
    public List<ApplicableTax> ApplicableTaxList;
    
    // All Sales Order (Customer Header) 
    public Integer TotalCustomerOrderRecords; // Added by richa 26/01/2017 for retrieving all CO's for a customer
    public List<ActiveSalesOrder> AllCustomerOrderList; // Added by richa 26/01/2017 for retrieving all CO's for a customer
    
    public Integer TotalMessageRecords;
    public List<MessageHistory> SMSMessageList;  

    // Constructor  
    public CustomerDetail(Account customerRec, List<Account> relatedCustomersList, Map<String, String> accountIdToRelationMap, List<Customer_Owned_Unit__c> couList, 
                            List<CO_Header__c> ActiveSalesOrdersList, List<Contact> customerContactList, String lastVisitedValue,
                            List<Tax_Exemption__c> taxExemptionList, List<Business_Profile__c> businessProfileList, 
                            List<Sales_Tax__c> applicableTaxList, List<CO_Header__c> AllCustomerOrdersList,
    						List<Store_Credit__c> storeCreditList, List<Message_History__c> msgList, String taxExemption) { // List<CO_Header__c> AllCustomerOrdersList Added by richa 26/01/2017 for retrieving all CO's
    	this.customerInfo = new Customer(customerRec, taxExemption); 
        this.RelatedCustomerList = new List<RelatedCustomer>();
        this.CustomerOwnedUnitList = new List<CustomerOwnedUnit>();
        this.ContactList = new List<CustomerContact>();
        this.ActiveOrderList = new List<ActiveOrder>();
        this.ActiveSalesOrderList = new List<ActiveSalesOrder>();
        this.TaxExemptionList = new List<TaxExemptions>();
        this.ApplicableTaxList = new List<ApplicableTax>();
        this.AllCustomerOrderList = new List<ActiveSalesOrder>(); // Added by richa 26/01/2017 for retrieving all CO's for a customer 
        this.StoreCreditList = new List<StoreCredit>();
        
        this.OpenOrders = customerRec.Open_Orders__c;
        this.OrdersLifetime = customerRec.Orders_Lifetime__c;
        this.AverageSpendPerHour = customerRec.Average_Spend_per_Order__c;
        this.LastVisit = lastVisitedValue; 
        
        for(Account relatedCustomerRec : relatedCustomersList) {
            this.RelatedCustomerList.add(new RelatedCustomer(relatedCustomerRec, accountIdToRelationMap));
        }
        
        for(Customer_Owned_Unit__c couRec : couList) {
            this.CustomerOwnedUnitList.add(new CustomerOwnedUnit(couRec));
        }
        
        for(CO_Header__c coh : ActiveSalesOrdersList) {
            this.ActiveSalesOrderList.add(new ActiveSalesOrder(coh));
        }
        
        for(Contact contactRec : customerContactList) {
            this.ContactList.add(new CustomerContact(contactRec));
        }
        
        for(CO_Header__c coh : AllCustomerOrdersList) { // Added by richa 26/01/2017 for retrieving all CO's for a customer 
            this.AllCustomerOrderList.add(new ActiveSalesOrder(coh));
        }
        
        for(Store_Credit__c sc : storeCreditList){
            this.StoreCreditList.add(new StoreCredit(sc));
        }

        Map<Id, List<String>> salesTaxItemIdToAppliesToList = getAppliesToList(taxExemptionList);
        for(Tax_Exemption__c taxExemptionRec : taxExemptionList) {
            this.TaxExemptionList.add(new TaxExemptions(taxExemptionRec, salesTaxItemIdToAppliesToList.get(taxExemptionRec.Sales_Tax_Item__c)));
        }
        
        for(Sales_Tax__c applicableTaxRec : applicableTaxList) {
            this.ApplicableTaxList.add(new ApplicableTax(applicableTaxRec));
        }
        
        ActiveOrder.RelatedListPaginationSorting pageSort = new ActiveOrder.RelatedListPaginationSorting();
        pageSort.activeOrdersCurrentPage = 1;
        pageSort.activeOrdersPageSize = 1;

        this.ActiveOrderList = ActiveOrder.getAllActiveOrdersForCustomer(customerRec.Id, system.JSON.serialize(pageSort));
        if(businessProfileList.size() > 0) {
            this.CompanyName = new Company(businessProfileList[0]);
        } else {
            this.CompanyName = new Company(new Business_Profile__c());
        }
        
        SMSMessageList = new List<CustomerDetail.MessageHistory>();
        for(Message_History__c smsRec : msgList) { 
            SMSMessageList.add(new CustomerDetail.MessageHistory(smsRec));
        }
    }
    
    /**
     * Name: parse
     * Desc: Method to Parse JSON String to class instance
     * @param:  (1) JSONString - String - JSON String 
     * @return: CustomerDetail - Class Object
    **/
    public static CustomerDetail parse(String json) {
        return (CustomerDetail) System.JSON.deserialize(json, CustomerDetail.class);
    }
    
    public static Map<Id, List<String>> getAppliesToList(List<Tax_Exemption__c> taxExemptionList) {
        Set<Id> salesTaxItemIdSet = new Set<Id>();
        for(Tax_Exemption__c taxExemptionRec : taxExemptionList) {
            salesTaxItemIdSet.add(taxExemptionRec.Sales_Tax_Item__c);
        }
        
        if(salesTaxItemIdSet.size() == 0) {
            return new Map<Id, List<String>>();
        }
        
        Map<Id, List<String>> salesTaxItemIdToAppliesToList = new Map<Id, List<String>>(); 
        if(AccessControl.ifObjectIsAccessible('Applicable_Taxes__c') == false ){throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE);}
        List<Applicable_Taxes__c> appTaxList = [select Sales_Tax_Item__c, Sales_Tax__c, Sales_Tax__r.Name__c from Applicable_Taxes__c
                                                    where Sales_Tax_Item__c IN: salesTaxItemIdSet];
        
        for(Applicable_Taxes__c appTaxRec : appTaxList) {
            if(appTaxRec.Sales_Tax__c != null) {
                List<String> appliesToList;
                if(!salesTaxItemIdToAppliesToList.containsKey(appTaxRec.Sales_Tax_Item__c)) {
                    salesTaxItemIdToAppliesToList.put(appTaxRec.Sales_Tax_Item__c, new List<String>());
                }
                salesTaxItemIdToAppliesToList.get(appTaxRec.Sales_Tax_Item__c).add(appTaxRec.Sales_Tax__r.Name__c);
            }
        }
        return salesTaxItemIdToAppliesToList;
    } 

    public class Company {
         
        public String Address1 {get; set;} 
        public String Address2 {get; set;}
        public String State {get; set;}
        public String PostalCode {get; set;}
        public String Country {get; set;}
        public String City {get; set;} 
        public String Address {get; set;}
        public String CompanyName {get; set;} 
        public String BusinessPhone {get; set;}
        public String FormattedBusinessPhone {get;set;}
        public String BusinessEmail {get; set;}
        public String TaxId {get; set;}
        
        public Company(Business_Profile__c businessProfileRec) {
    		this.Address1 = businessProfileRec.Business_Street_Address1__c != null ? (businessProfileRec.Business_Street_Address1__c).replace(',', ' ') : '';
    		this.Address2 = businessProfileRec.Business_Street_Address2__c != null ? (businessProfileRec.Business_Street_Address2__c).replace(',', ' ') : '';
            this.City = businessProfileRec.Business_City__c;
            this.State = (businessProfileRec.Business_State__c != null) ? businessProfileRec.Business_State__r.Name__c : '';
            this.PostalCode = businessProfileRec.Business_Postal_Code__c;
            this.Country = (businessProfileRec.Business_Country__c != null) ? businessProfileRec.Business_Country__r.Name__c : '';
            this.CompanyName = (businessProfileRec.Business_Name__c != null) ? businessProfileRec.Business_Name__c : '';
            this.BusinessPhone = (businessProfileRec.Business_Phone__c != null) ? businessProfileRec.Business_Phone__c : '';
            this.FormattedBusinessPhone = (businessProfileRec.Formatted_Business_Number__c != null) ? businessProfileRec.Formatted_Business_Number__c : '';
            this.BusinessEmail = (businessProfileRec.Business_Email__c != null) ? businessProfileRec.Business_Email__c : '';
            this.TaxId = Configurations__c.getOrgDefaults().Tax_Id__c == null ? '' : Configurations__c.getOrgDefaults().Tax_Id__c;
            this.Address = '';
            if(this.Address1 != null) {
                this.Address += this.Address1 + ', ';
            }
            if(this.Address2 != null) {
                this.Address += this.Address2 + ', ';
            }
            if(this.City != null) {
                this.Address += this.City + ', ';
            }
            if(this.State != null) {
                this.Address += this.State + ', ';
            }
            if(this.Country != null) {
                this.Address += this.Country + ', ';
            }
            if(this.PostalCode != null) {
                this.Address += this.PostalCode + ', ';
            }
            if(this.Address.length() > 1) {
                this.Address = this.Address.subString(0, this.Address.length() - 2).replace(',', ' ');
            }
        }
    }
    
    
    public class ApplicableTax {
        public String Id;
        public String ApplicableTaxName;
        
        public ApplicableTax(Sales_Tax__c applicableTaxRec) {
            this.Id = applicableTaxRec.Id;
            this.ApplicableTaxName = applicableTaxRec.Name__c;
        }
    }
    
    public class MessageHistory {
        public String Id;
        public String Activity;
        public String SentBy;
        public String SentTo;
        public String SentToId;
        public String Text;
        public String SentTime;
        public String InvoiceNumber;
        public String COHeaderNumber;
        
        public MessageHistory(Message_History__c messageRec) {
            this.Id = String.isNotBlank(messageRec.Id) ? messageRec.Id : '';
            this.Activity = messageRec.Activity__c;
            this.SentBy = messageRec.Sent_By__r.Name; 
            this.SentTime = (messageRec.CreatedDate != null) ? BPUtility.getFormatedDateAndTime(messageRec.CreatedDate) : null;
            this.SentToId =  messageRec.Sent_To__c; 
            this.Text = messageRec.Text__c; 
            if(messageRec.Activity__c == 'Text Message') {
                this.SentTo =  messageRec.Formatted_Phone__c; 
            } else {
                this.SentTo =  messageRec.Email__c; 
                if(messageRec.CO_Invoice_Header__c != null) {
                    this.InvoiceNumber = messageRec.CO_Invoice_Header__r.Invoice_Number__c;
                    this.COHeaderNumber = messageRec.CO_Invoice_Header__r.CO_Header__c;
            }
        }
    }
    }
    
    public static List<String> getMessageFieldList(){
        List<String> msgFieldList = new List<String>{'Activity__c',
                                                    'Sent_By__r.Name',
                                                    'Sent_To__c',
                                                    'Text__c',
                                                    'Phone__c',
                                                    'Formatted_Phone__c',
                                                    'Email__c',
                                                    'CO_Invoice_Header__r.Invoice_Number__c',
                                                    'CO_Invoice_Header__r.CO_Header__c',
                                                    'CreatedDate'
                                                };
        return msgFieldList;
    } 
}