Blackpurl/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Purchase_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Accounts (Purchase Tax)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Active__c = TRUE, &apos;Active&apos; , &apos;InActive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Compliance_Date__c</fullName>
        <label>Compliance Date</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Of_1st_Rego__c</fullName>
        <label>Year Of 1st Rego</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Serial__c</fullName>
        <label>Registration Serial</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cylinders__c</fullName>
        <description>Number of cylinders in unit</description>
        <label>Cylinders</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Factory_Order_No__c</fullName>
        <description>Factory order number of unit</description>
        <label>Factory Order No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make_Name__c</fullName>
        <formula>Unit_Make__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Make Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Detail__c</fullName>
        <formula>Model_Name__c &amp; &apos; &apos; &amp; Sub_Model__r.Sub_Model_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Detail</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of unit based on unit type</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Traded</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stock_Id__c</fullName>
        <description>This will contain the stock id</description>
        <label>Stock Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Stocked_In_DateTime__c</fullName>
        <label>Stocked In DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sub_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Model</label>
        <referenceTo>Unit_Sub_Model__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submodel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sub model of unit</description>
        <label>Unit SubModel</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Customer Owned Units (Submodel)</relationshipLabel>
        <relationshipName>Customer_Owned_Units1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Total Cost</description>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Model of unit</description>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <formula>IF( Unit_Id__c != null, Unit_Id__c , Stock_Id__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN_Number__c</fullName>
        <description>This VIN number is used. Please ignore previous VIN__c.</description>
        <label>VIN Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Owned Units (Vendor)</relationshipLabel>
        <relationshipName>Customer_Owned_Units1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>Model year of the unit</description>
        <label>Unit Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Deal__c.object
<CustomObject>
    <description>Unit Deal on Customer Order</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Deal_Item__c.object
<CustomObject>
    <description>Junction between deal and unit</description>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to cou</description>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Deals_Units_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to deal</description>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Deal_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name</description>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Model</label>
        <referenceTo>Unit_Sub_Model__c</referenceTo>
        <relationshipLabel>Deals Items</relationshipLabel>
        <relationshipName>Deals_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <formula>IF( $Setup.Configurations__c.Tax_Included_Pricing__c , ( Agreed_Value__c - ( Agreed_Value__c / ( 1 + Default_Unit_Sales_Tax_Percentage__c) ) ), Agreed_Value__c * Default_Unit_Sales_Tax_Percentage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Model of unit</description>
        <label>Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Deal_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>Model year of the unit</description>
        <label>Unit Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Deal Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Sales_Tax__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Active__c , &apos;Active&apos;, &apos;Inactive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Unit_Model__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Model</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Model__c</fullName>
        <label>Sub-Model</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Unit Model</label>
    <nameField>
        <displayFormat>UM-{0000000}</displayFormat>
        <label>Unit Model Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Unit_Price_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Unit lookup with Customer Owned Unit</description>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Ordered_Unit_Price_Cost__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Ordered Unit Price Cost</label>
        <referenceTo>Unit_Price_Cost__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Total cost of unit</description>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Unit Price &amp; Cost</label>
    <nameField>
        <displayFormat>UNP-{00000000}</displayFormat>
        <label>Unit Price &amp; Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Prices &amp; Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Unit_Sub_Model__c.object
<CustomObject>
    <fields>
        <fullName>Sub_Model_Name__c</fullName>
        <label>Sub Model Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Unit Sub Models</relationshipLabel>
        <relationshipName>Unit_Sub_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Sub Model</label>
    <nameField>
        <displayFormat>USM-{0000000}</displayFormat>
        <label>Unit Sub Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Sub Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/classes/UnitOrderingWrapper.cls
public with sharing class UnitOrderingWrapper {
 	
 	public class VendorWrapper{
 		public String VendorName;
 		public String VendorId;
 		public Integer UnitCount;
 		
 		public VendorWrapper(){}
 		public VendorWrapper(Account acc){
 			this.VendorId = acc.Id;
 			this.VendorName = acc.Name;
 			if(acc.Customer_Owned_Units1__r != null){
 				this.UnitCount = acc.Customer_Owned_Units1__r.size();
 			}
 		}
 		
 		public List<VendorWrapper> convertToWrapperList(List<Account> vendorsList){
 			List<VendorWrapper> vendorList = new List<VendorWrapper>();
	    	for(Account acc : vendorsList){
	    		vendorList.add(new VendorWrapper(acc));
	    	}
	    	return vendorList;
 		}
 	}   
 	
 	public class UnitOrderWrapper{
 		public String UnitId;
 		public String UnitNumber;
        public String StockNumber;
        public String VIN;
 		public Decimal Year;
 		public String Make;
 		public String Model;
 		public String ModelName;
 		public String FactoryOrder;
 		public String Status;
 		public String CreatedDate;
        public String StockedInDateTime;
 		public Decimal TotalCost;
        public Decimal SalesTax;
        public Decimal TotalWithTax;
        public String InvoiceNumber;
        public String DealItemId;
        public String CoNumber;
        public String MakeName;
        public String MakeId;
        public String ModelId;
        public String SubModelName;
        public String SubModelId;
        public Decimal Cylinders;
        public String ComplianceDate;
	    public String YearOf1stRego;
	    public String RegistrationSerial;
 		
 		public UnitOrderWrapper(){}
 		public UnitOrderWrapper(Customer_Owned_Unit__c unit){
 			this.UnitId = unit.Id;
 			this.UnitNumber = unit.Unit_Number__c;
            this.StockNumber = unit.Stock_Id__c;
            this.VIN = unit.VIN_Number__c;
 			this.Year = unit.Year__c;
 			this.Make = unit.Make_Name__c	;
 			this.MakeName = unit.Make_Name__c;
            this.Model = unit.Model_Detail__c;
 			this.ModelName = (unit.Unit_Model__c != null) ? unit.Unit_Model__r.Name__c : '';
 			this.SubModelName = (unit.Sub_Model__c != null) ? unit.Sub_Model__r.Sub_Model_Name__c : '';
 			this.FactoryOrder = unit.Factory_Order_No__c == null ? '- - - - - - - - -' : unit.Factory_Order_No__c ;
 			this.Status = unit.Status__c;
 			this.CreatedDate = (unit.CreatedDate != null) ? 
								BPUtility.getFormatedDateTime(datetime.newInstance(unit.CreatedDate.year(), unit.CreatedDate.month(), unit.CreatedDate.day())) : '' ;
            this.StockedInDateTime = (unit.Stocked_In_DateTime__c != null) ? 
                                BPUtility.getFormatedDateTime(datetime.newInstance(unit.Stocked_In_DateTime__c.year(), unit.Stocked_In_DateTime__c.month(), unit.Stocked_In_DateTime__c.day())) : '' ;
            this.TotalCost = ((unit.Total_Cost__c != null) ? unit.Total_Cost__c : 0);
            this.SalesTax = unit.Vendor__r.Purchase_Tax__r.Rate__c;
            this.TotalWithTax = this.TotalCost + (unit.Tax_Amount__c != null ? unit.Tax_Amount__c : 0);
            this.InvoiceNumber = unit.Invoice_Number__c;
            this.DealItemId = unit.Deals_Units_Junction__r.size() > 0 ? unit.Deals_Units_Junction__r[0].Id: null;
            this.CoNumber = unit.Deals_Units_Junction__r.size() > 0 ? (unit.Deals_Units_Junction__r != null ? unit.Deals_Units_Junction__r[0].Deal__r.CO_Header__r.Name : null) : null;
            this.Cylinders = unit.Cylinders__c;
	    	this.ComplianceDate = unit.Compliance_Date__c;
	    	this.RegistrationSerial = unit.Registration_Serial__c;
	    	this.YearOf1stRego = unit.Year_Of_1st_Rego__c;
 		}
 		
 		public List<UnitOrderWrapper> convertToWrapperList(List<Customer_Owned_Unit__c> couList){
 			List<UnitOrderWrapper> unitList = new List<UnitOrderWrapper>();
	    	for(Customer_Owned_Unit__c unit : couList){
	    		unitList.add(new UnitOrderWrapper(unit));
	    	}
	    	return unitList;
 		}
 	}
 	
 	public class UnitDetailsWrapper{
 		public UnitWrapper.UnitInfoWrapper UnitInfo;
		public List<UnitWrapper.PriceAndCostTrackingWrapper> PriceAndCostTrackingWrapperList;
		
		public UnitDetailsWrapper(Customer_Owned_Unit__c unitRec){
			this.UnitInfo = new UnitWrapper.UnitInfoWrapper(unitRec);
			this.PriceAndCostTrackingWrapperList = new List<UnitWrapper.PriceAndCostTrackingWrapper>();
			for(Unit_Price_Cost__c unitPriceAndCostRec : unitRec.Unit_Prices_Costs__r){
				this.PriceAndCostTrackingWrapperList.add(new UnitWrapper.PriceAndCostTrackingWrapper(unitPriceAndCostRec));
	    	}
		}
 	}
    
    public class SortingAttrs {
        
        public String FieldLabel;
        public String SortingOrder;
    }
    
    public static Map<String, String> fieldLabelToFieldAPINameMap = new Map<String, String> {
                                                                          'UnitNumber' => 'Unit_Number__c',
                                                                          'Make' => 'Make_Name__c',
                                                                          'Year' => 'Year__c',
                                                                          'Model' => 'Model_Detail__c',
                                                                          'FactoryOrder' => 'Factory_Order_No__c',
                                                                          'CreatedDate' => 'CreatedDate',
                                                                          'StockedInDateTime' => 'Stocked_In_DateTime__c',
                                                                          'TotalCost' => 'Total_Cost__c',
                                                                          'Status' => 'Status__c'
              };
}