Blackpurl/src/objects/Cash_Drawer__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Cash Drawer</label>
    <nameField>
        <label>Cash Drawer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Drawers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Cash_Drawer_Reconciliation__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Drawer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cash Drawer</label>
        <referenceTo>Cash_Drawer__c</referenceTo>
        <relationshipLabel>Cash Drawer Reconciliations</relationshipLabel>
        <relationshipName>Cash_Drawer_Reconciliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cash_Reconciliation__c</fullName>
        <label>Cash Reconciliation</label>
        <referenceTo>Cash_Reconciliation__c</referenceTo>
        <relationshipLabel>Cash Drawer Reconciliations</relationshipLabel>
        <relationshipName>Cash_Drawer_Reconciliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cash Drawer Reconciliation</label>
    <nameField>
        <displayFormat>CDR-{000000}</displayFormat>
        <label>Cash Drawer Reconciliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Drawer Reconciliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Cash_Reconciliation__c.object
<CustomObject>
    <fields>
        <fullName>Reconciliation_Date__c</fullName>
        <label>Reconciliation Date</label>
        <type>Date</type>
    </fields>
    <label>Cash Reconciliation</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Cash Reconciliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Reconciliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Cash_Reconciliation_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Drawer_Reconciliation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cash Drawer Reconciliation</label>
        <referenceTo>Cash_Drawer_Reconciliation__c</referenceTo>
        <relationshipLabel>Cash Reconciliation Payments</relationshipLabel>
        <relationshipName>Cash_Reconciliation_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cash_Reconciliation__c</fullName>
        <label>Cash Reconciliation</label>
        <referenceTo>Cash_Reconciliation__c</referenceTo>
        <relationshipName>Cash_Reconciliation_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cash Reconciliation Payment</label>
    <nameField>
        <displayFormat>CRP-{00000}</displayFormat>
        <label>Cash Reconciliation Payments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Reconciliation Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/CO_Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cash_Drawer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cash Drawer</label>
        <referenceTo>Cash_Drawer__c</referenceTo>
        <relationshipLabel>CO Deposits</relationshipLabel>
        <relationshipName>CO_Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Deposit</label>
    <nameField>
        <displayFormat>CODN-{00000000}</displayFormat>
        <label>CO Deposits Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Deposits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/CO_Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Drawer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cash Drawer</label>
        <referenceTo>Cash_Drawer__c</referenceTo>
        <relationshipLabel>CO Invoice Payments</relationshipLabel>
        <relationshipName>CO_Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reverse_Payment_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reverse Payment From</label>
        <referenceTo>CO_Invoice_Payment__c</referenceTo>
        <relationshipLabel>CO Invoice Payments</relationshipLabel>
        <relationshipName>CO_Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Invoice Payment</label>
    <nameField>
        <displayFormat>COIP-{00000000}</displayFormat>
        <label>CO Invoice Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/classes/CashDrawerSOQLUtil.cls
public with sharing class CashDrawerSOQLUtil {
	
    /** 
     * Name: getAvailableQueryRowsLimit
     * Desc: Getter method which returns available  limit of query rows which can be returned by a SOQL in the context
     * @param:
     * @return: Integer - Available query rows limit  
    **/ 
    public static Integer getAvailableQueryRowsLimit() {
        return Limits.getLimitQueryRows() - Limits.getQueryRows();   
    }  
    
    public static List<Cash_Drawer__c> getAllCashDrawerList(Boolean isIncludeInactive) {
    	String query = 'SELECT ';
        for(String fieldName : CashDrawerWrapper.getCashDrawerFieldsList()) {
        	fieldName = BPUtility.escapeSingleQuotes(fieldName);
            query += fieldName + ', ';  
        }
        query = query.substring(0, query.length()-2);
        query += ' FROM Cash_Drawer__c ';
        if(!isIncludeInactive) {
        	query += ' WHERE Active__c = true ';
        }
        query += ' ORDER BY Name ASC';
        if(AccessControl.ifObjectFieldIsAccessible('Cash_Drawer__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        return Database.query(query);
    }
    
     public static List<Cash_Drawer__c> getCashDrawerDetailsByFieldValues(DateTime dtValue, String cashDrawerId) {
        String query = 'SELECT '; 
        for(String fieldName : CashDrawerWrapper.getCashDrawerFieldsList()) {
            query += fieldName + ', ';
        }
        // Invoice Payments child query
        query += '(SELECT ';
        for(String fieldsName : ReconciliationWrapper.getCOInvoicePaymentfieldsList()) {
            query += fieldsName + ', ';
        }
        query = query.substring(0, query.length()-2);
        query += ' FROM ' + 'CO_Invoice_Payments__r';
        query += ' WHERE Payment_Date__c >= ' + dtValue.format('yyyy-MM-dd');
        query += ' AND Payment_Date__c < ' + dtValue.addDays(1).format('yyyy-MM-dd') + ' ), ';
        
        // Deposits child query
        query += '(SELECT ';
        for(String fieldsName : ReconciliationWrapper.getCODepositFieldsList()) {
            query += fieldsName + ', ';
        }
        query = query.substring(0, query.length()-2);
        query += ' FROM ' + 'CO_Deposits__r';
        query += ' WHERE Payment_Date__c >= ' + dtValue.format('yyyy-MM-dd');
        query += ' AND Payment_Date__c < ' + dtValue.addDays(1).format('yyyy-MM-dd') + ' ), ';
        
        // Child Query
        query += '(SELECT ';
        for(String fieldsName : CashDrawerReconcilationWrapper.getCashDrawerReconciliationFieldsList()) {
            query += fieldsName + ', ';
        }
        query = query.substring(0, query.length()-2);
        query += ' FROM ' + 'Cash_Drawer_Reconciliations__r';
        query += ' WHERE Cash_Reconciliation__r.Reconciliation_Date__c = ' + dtValue.format('yyyy-MM-dd') + ')';
        
        query += ' FROM ' + 'Cash_Drawer__c';
        if(String.isNotBlank(cashDrawerId)) {
        	query += ' WHERE Id =: cashDrawerId';
        }
        query += ' ORDER BY Name ASC LIMIT ' + getAvailableQueryRowsLimit();
        if(AccessControl.ifObjectFieldIsAccessible('Cash_Drawer__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        List<Cash_Drawer__c> cashDrawers = Database.query(query);
        return cashDrawers;
    }
    
    public static List<Cash_Drawer_Reconciliation__c> getCashDrawerReconciliationByFieldValues(Map<String, String> fieldNameToValueMap) {
        String query = 'SELECT Id, '; 
        for(String fieldName : CashDrawerReconcilationWrapper.getCashDrawerReconciliationFieldsList()) {
            query += fieldName + ', ';
        }
        // Invoice Payments child query
        query += '(SELECT ';
        for(String fieldsName : ReconciliationWrapper.getReconciliationPaymentFieldList()){
            query += fieldsName + ', ';
        }
        query = query.substring(0, query.length()-2);
        query += ' FROM ' + 'Cash_Reconciliation_Payments__r)';
        
        query += ' FROM ' + 'Cash_Drawer_Reconciliation__c ';
        if(fieldNameToValueMap != null && fieldNameToValueMap.size() > 0) {
        	boolean isWhereClauseAdded = query.contains('WHERE');
            for(String fieldName : fieldNameToValueMap.keySet()) {
                fieldName = BPUtility.escapeSingleQuotes(fieldName);
                if(!isWhereClauseAdded) {
	                query += 'WHERE ';
	                isWhereClauseAdded = true;
	            } else {
	                query += 'AND ';
	            }
                
                if(fieldName == 'Cash_Reconciliation__r.Reconciliation_Date__c') {
	                query += fieldName + ' = ' + fieldNameToValueMap.get(fieldName) + ' ';
	            } else {
	                query += fieldName + ' = \'' + fieldNameToValueMap.get(fieldName) + '\' ';
	            }
            }
        }
        query += ' ORDER BY Name ASC LIMIT ' + getAvailableQueryRowsLimit();
        if(AccessControl.ifObjectFieldIsAccessible('Cash_Drawer_Reconciliation__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        List<Cash_Drawer_Reconciliation__c> cashDrawerReconciliationList = Database.query(query);
        return cashDrawerReconciliationList;
    }
    
    public static List<Cash_Reconciliation_Payment__c> getReconciliationPaymentsList(Map<String, String> fieldNameToFieldValueMap) {
        String query = 'SELECT Id, '; 
        for(String fieldName : ReconciliationWrapper.getReconciliationPaymentFieldList()){ 
            query += fieldName + ', ';
        } 
        query = query.substring(0, query.length()-2);
        query += ' FROM Cash_Reconciliation_Payment__c '; 
        Boolean isWhereClauseAdded = false;
        for(String fieldName : fieldNameToFieldValueMap.keySet()) {
            if(!isWhereClauseAdded) {
                query += 'WHERE ';
                isWhereClauseAdded = true;
            } else {
                query += 'AND ';
            }
            if(fieldName == 'Cash_Reconciliation__r.Reconciliation_Date__c') {
                query += fieldName + ' = ' + fieldNameToFieldValueMap.get(fieldName) + ' ';
            } else {
                query += fieldName + ' = \'' + fieldNameToFieldValueMap.get(fieldName) + '\' ';
            }
        }
        query += ' ORDER BY CreatedDate DESC';
        query += ' LIMIT ' + getAvailableQueryRowsLimit();
        if(AccessControl.ifObjectFieldIsAccessible('Cash_Reconciliation_Payment__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); } 
        List<Cash_Reconciliation_Payment__c> reconciliationPaymentList = Database.query(query);
        return reconciliationPaymentList;
    }
}