Blackpurl/src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Vendor_Order_Header__c.object
<CustomObject>
    <label>Vendor Order Header</label>
    <nameField>
        <displayFormat>VO-{00000000}</displayFormat>
        <label>Vendor Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Vendor_Order_Line_Item_Group__c.object
<CustomObject>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Vendor Order Line Item Groups</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Item_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Order Header</label>
        <referenceTo>Vendor_Order_Header__c</referenceTo>
        <relationshipLabel>Vendor Order Line Item Groups</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Item_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Order Line Item Group</label>
    <nameField>
        <displayFormat>VOG-{00000000}</displayFormat>
        <label>Vendor Order Line Item Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Line Item Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/classes/VendorOrderExportCtrlTest.cls
@isTest 
public class VendorOrderExportCtrlTest {
	
	@testSetup
    private static void setupTestData() {
    	IFW_IntegrationConfig__c ifwIntegration = TestUtil.createIFWConfigForXero(); 
		IFW_IntegrationConfigItem__c ifwConfigItem = TestUtil.createIFWConfigItemForXero('Journal Entry', ifwIntegration.Id);
        Account vendorRec = TestDataFactory.createVendor('Test Vendor');
        Vendor_Order_Header__c vOHeaderRec = TestDataFactory.createVendorOrderHeader(vendorRec.Id);
        Category__c categoryRec = TestDataFactory.createCategory('Test category');
        
        Part__c partRec = TestDataFactory.createPart(vendorRec.Id, 10, 10, 10, 10, 2, categoryRec.Id);
        Vendor_Order_Line_Item_Group__c vendorOrderLineItemGroupRec = TestDataFactory.createVendorOrderLineItemGroup(vOHeaderRec.Id, partRec.Id);
    }
      
    @isTest
    private static void genericVendorOrderExportCtrlTest() {
    	Vendor_Order_Header__c vOHeaderRec = [SELECT Id from Vendor_Order_Header__c LIMIT 1];
    	PageReference pageRef = Page.VendorOrderExport;
  		pageRef.getParameters().put('id', String.valueOf(vOHeaderRec.Id));
  		pageRef.getParameters().put('type', 'Generic');
  		Test.setCurrentPage(pageRef);
  		VendorOrderExportCtrl vendorOrderExportCtrl = new VendorOrderExportCtrl();
  		system.assertEquals(vendorOrderExportCtrl.contentType, 'text/csv#Vendor Order.csv');
    }
    
    @isTest
    private static void partsCanadaVendorOrderExportCtrlTest() {
    	Vendor_Order_Header__c vOHeaderRec = [SELECT Id from Vendor_Order_Header__c LIMIT 1];
    	PageReference pageRef = Page.VendorOrderExport;
  		pageRef.getParameters().put('id', String.valueOf(vOHeaderRec.Id));
  		pageRef.getParameters().put('type', 'Parts Canada');
  		Test.setCurrentPage(pageRef);
  		VendorOrderExportCtrl vendorOrderExportCtrl = new VendorOrderExportCtrl();
  		system.assertEquals(vendorOrderExportCtrl.contentType, 'text/csv#Vendor Order.csv');
    }
    
    @isTest
    private static void hDnetAustraliaVendorOrderExportCtrlTest() {
    	Vendor_Order_Header__c vOHeaderRec = [SELECT Id from Vendor_Order_Header__c LIMIT 1];
    	PageReference pageRef = Page.VendorOrderExport;
  		pageRef.getParameters().put('id', String.valueOf(vOHeaderRec.Id));
  		pageRef.getParameters().put('type', 'HDnet Australia');
  		Test.setCurrentPage(pageRef);
  		VendorOrderExportCtrl vendorOrderExportCtrl = new VendorOrderExportCtrl();
  		system.assertEquals(vendorOrderExportCtrl.contentType, 'text/plain/#Vendor Order.txt');
    }
    
    @isTest
    private static void bossWebVendorOrderExportCtrlTest() {
    	Vendor_Order_Header__c vOHeaderRec = [SELECT Id, Name from Vendor_Order_Header__c LIMIT 1];
    	PageReference pageRef = Page.VendorOrderExport;
  		pageRef.getParameters().put('id', String.valueOf(vOHeaderRec.Id));
  		pageRef.getParameters().put('type', 'BossWeb');
  		Test.setCurrentPage(pageRef);
  		VendorOrderExportCtrl vendorOrderExportCtrl = new VendorOrderExportCtrl();
  		system.assertEquals(vendorOrderExportCtrl.contentType.contains('.txt'), true);
    }
}