Blackpurl/src/objects/CO_Header__c.object
<CustomObject>
    <fields>
        <fullName>CO_Type__c</fullName>
        <description>Customer order types</description>
        <label>CO Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Cash Sale</fullName>
                </value>
                <value>
                    <fullName>Internal Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CO Headers</relationshipLabel>
        <relationshipName>CO_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selling_Group__c</fullName>
        <label>Selling Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CO_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Part Sale</fullName>
                </value>
                <value>
                    <fullName>Service Order</fullName>
                </value>
                <value>
                    <fullName>Unit Deal</fullName>
                </value>
                <value>
                    <fullName>Cash Sale</fullName>
                </value>
                <value>
                    <fullName>Internal Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/CO_Invoice_Header__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Invoice Headers</relationshipLabel>
        <relationshipName>CO_Invoice_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CO Invoice Header</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>CO Invoice Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/CO_Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>CO Invoice Payments</relationshipLabel>
        <relationshipName>CO_Invoice_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reverse_Payment_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reverse Payment From</label>
        <referenceTo>CO_Invoice_Payment__c</referenceTo>
        <relationshipLabel>CO Invoice Payments</relationshipLabel>
        <relationshipName>CO_Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Invoice Payment</label>
    <nameField>
        <displayFormat>COIP-{00000000}</displayFormat>
        <label>CO Invoice Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Blackpurl/src/objects/Service_Order_Header__c.object
<CustomObject>
    <description>Object used to handle service related section on Customer order header</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Number</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Status__c</fullName>
        <label>Work Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Signed Out</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Order Header</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Blackpurl/src/classes/Customer_Service.cls
public with sharing class Customer_Service {
	
    public static String addCustomerToCO(String coId, String customerId) {
    	try{
    		coId = String.isBlank(coId) ? BPUtility.getDecodedString(BPGlobalHeaderCtrl.createCustomerOrder()) : coId;
            coId = BPUtility.escapeSingleQuotes(coId);
            
            if(isPaymentAddedByCustomer(coId)) {
                throw new BlackPurlException(BlackPurlException.getErrorMessage(Label.Changing_Customer_With_Payment_Error_Message, null));
            }
            CO_Header__c coHeaderRec = new CO_Header__c(Id = coId, Customer__c = customerId, Selling_Group__c = Constants.PART_SALE);
            updateCOWithCustomer(new List<CO_Header__c>{coHeaderRec}, customerId);
            return COService.getCOHeaderDetailsByGridName(coId, 'Customer Info');
    	}catch(Exception e){
            throw new BlackPurlException(BlackPurlException.getErrorMessage(e.getMessage(), e.getStackTraceString()));
        }
    }
    
    private static void updateCOWithCustomer(List<CO_Header__c> coHeaderRecList, String customerId) {
        if(coHeaderRecList.size() == 0 ) {
            return;
        }
        CO_Header__c coHeaderRec = coHeaderRecList[0];
    	if(String.isBlank(customerId)) {
            coHeaderRec.CO_Type__c = Constants.CASH_SALE;
            coHeaderRec.Selling_Group__c = Constants.CASH_SALE;
        } else {
        	if(AccessControl.ifObjectFieldIsAccessible('CO_Header__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        	if(AccessControl.ifObjectFieldIsAccessible('Service_Order_Header__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
            List<CO_Header__c> coHeaderList =[Select Id, CO_Type__c, Customer__c, (Select Id from CO_Invoice_Headers__r where Invoice_Status__c = 'Closed'), (Select Id, Work_Status__c, Customer_Owned_Unit__c from Service_Order_Headers__r) from CO_Header__c where Id = :coHeaderRec.Id];
            
            if(coHeaderList.size() > 0  && coHeaderList[0].CO_Type__c == Constants.INTERNAL_SERVICE){
                throw new BlackPurlException(BlackPurlException.getErrorMessage(Label.Customer_On_Internal_Service_CO, null));
            } else if(coHeaderList.size() > 0 && coHeaderList[0].CO_Invoice_Headers__r.size() > 0) {
                throw new BlackPurlException(BlackPurlException.getErrorMessage(Label.Changing_Customer_After_Invoicing_Error_Message, null));
            }
            
            if(coHeaderList.size() > 0  && coHeaderList[0].CO_Type__c == Constants.CASH_SALE){
                coHeaderRec.Selling_Group__c = Constants.PART_SALE;
            }
            if(coHeaderList.size() > 0  && ((String.isNotBlank(coHeaderList[0].Customer__c)) && 
            				(coHeaderList[0].Customer__c != customerId)) && coHeaderList[0].Service_Order_Headers__r.size() > 0) {
            	for(Service_Order_Header__c soHeaderRec : coHeaderList[0].Service_Order_Headers__r) {
            		if(String.isNotBlank(soHeaderRec.Work_Status__c) && soHeaderRec.Work_Status__c == Constants.SERVICE_ORDER_STATUS_TO_CHECKOUT) {
            			throw new BlackPurlException(BlackPurlException.getErrorMessage(Label.Cannot_Change_Customer_With_Service_Job_Completed_Error_Message, null));
            		}
            		soHeaderRec.Customer_Owned_Unit__c = null;
            	}
            	update coHeaderList[0].Service_Order_Headers__r;
            }
            coHeaderRec.CO_Type__c = Constants.CHECKOUT_TYPE_CUSTOMER;
        }
        updateCOPricingAndTax(new List<CO_Header__c> {coHeaderRec}, customerId, true);
    }
    
    private static Boolean isPaymentAddedByCustomer(String coId) {
    	if(AccessControl.ifObjectFieldIsAccessible('CO_Invoice_Header__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
    	if(AccessControl.ifObjectFieldIsAccessible('CO_Invoice_Payment__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        List<CO_Invoice_Header__c> coInvoiceHeaderList = [select Id, (select Id, Amount__c from CO_Invoice_Payments__r)
                                                                    from CO_Invoice_Header__c 
                                                                    where Invoice_Status__c = 'Active' AND CO_Header__c =:coId];
        Decimal totalPayment = 0;
        if(coInvoiceHeaderList.size() > 0) {
        	for(CO_Invoice_Payment__c payment: coInvoiceHeaderList[0].CO_Invoice_Payments__r) {
            	totalPayment += (payment.Amount__c != null ? payment.Amount__c : 0);
            }
        }
        
        if(coInvoiceHeaderList.size() > 0 && totalPayment != 0) {
        	return true;
        }
        return false;
    }
    
    private static void updateCOPricingAndTax(List<CO_Header__c> COHeaderRecList, String customerId, Boolean isCalculatePLandTax){ 
            
        if(AccessControl.ifObjectFieldIsUpdateable('CO_Header__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_UPDATEABLE); }
        if(AccessControl.ifObjectFieldIsAccessible('CO_Header__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        try{
        	CO_Header__c COHeaderRec;
        	if(COHeaderRecList.size() > 0){
        		COHeaderRec = COHeaderRecList[0];
        	}
        	COTriggerHelper.isCalculatePLandTax = isCalculatePLandTax; 
            update COHeaderRec;

            COLineItemTriggerHelper.isTotalCalculated = false;
            //COKH_Recalcualtion.AddCustomerCoForKititemUpdate(customerId, COHeaderRec.Id);
            COKH_Recalcualtion.changePriceWhenCustomerIsChanged(COHeaderRec.Id);
            //SO_KLI_Recalculation.SOPriceCalcultaionByPriceLevel(customerId, COHeaderRec.Id);
            SO_KLI_Recalculation.changePriceWhenCustomerIsChanged(new Set<Id>(), COHeaderRec.Id);
            DealKH_Recalculation.changePriceWhenCustomerIsChanged(customerId, COHeaderRec.Id);
        }catch(Exception e){
            throw new BlackPurlException(BlackPurlException.getErrorMessage(e.getMessage(), e.getStackTraceString()));
        }
    }
}