Blackpurl/src/objects/Shop_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>For storing the shop business hours on each day of week</description>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Time__c</fullName>
        <label>From Time</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Working__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Working</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Time__c</fullName>
        <label>To Time</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Shop Settings</label>
</CustomObject>

Blackpurl/src/classes/ShopSettingWrapper.cls
public class ShopSettingWrapper {
    public String Id;
    public String Day;
    public Boolean IsWorking;
    public String FromTime;
    public String ToTime;
    
    public ShopSettingWrapper(Shop_Settings__c shopSettingInstance) {
    	this.Id = shopSettingInstance.Id;
    	this.Day = shopSettingInstance.Day__c;
    	this.IsWorking = shopSettingInstance.Is_Working__c;
    	this.FromTime = shopSettingInstance.From_Time__c;
    	this.ToTime = shopSettingInstance.To_Time__c;
    }
}